### ISSUE TITLE
Issue updating ODK - cdno-odk.yaml doesn't exist

### ISSUE THREAD

**Issue by LilyAndres** [INCATools/ontology-development-kit#1061]
Hi ODK team, I am trying to update ODK following the "[Updating ODK](https://oboacademy.github.io/obook/howto/odk-update/)" workflow. When I run the command
`sh run.sh make update_repo`
`sh run.sh make update_repo`

It says:

<img width="941" alt="Screen Shot 2024-05-17 at 10 14 03 pm" src="https://github.com/INCATools/ontology-development-kit/assets/25215773/4ecef24f-12f9-4759-b0c0-ca27a514837f">

I feel like maybe I missed one release? But I updated ODK in February... I hope you can help me. Thanks.

**Comment by anitacaron** [comment]
Hi @LilyAndres, could you double-check if you have a file in `src/ontology/cdno-odk.yaml` that looks like [this one](https://github.com/pato-ontology/pato/blob/master/src/ontology/pato-odk.yaml)?

**Comment by anitacaron** [comment]
Have you seen this file? How did you set up this repository?

**Comment by LilyAndres** [comment]
I started my repo in 2021, following ENVO workflows. I don't remember this yaml file...

**Comment by anitacaron** [comment]
Could you please share the ENVO workflows? It might need some updates.

**Comment by LilyAndres** [comment]
I am sorry, I can't find it anymore, it was ages ago. I am just having a look at ENVO and FoodOn and I can't see that file either... Not sure where can be found apart from src/ontology or the the top level of the repo.

**Comment by LilyAndres** [comment]
Maybe is not easy to solve at the moment, I am just having trouble to run my workflow and I thought it could be because of the new ODK release.

**Comment by anitacaron** [comment]
That's fine. You can create the `cdno-odk.yaml` with the desired configuration and run `update_repo`.

**Comment by anitacaron** [comment]
>  I am just having trouble to run my workflow

If you want to create another issue, we can discuss your problem there 😄

**Comment by LilyAndres** [comment]
Thanks a lot @anitacaron, I will create the file and create another issue later, for my other big problem :) I think we can close this issue now.
