### ISSUE TITLE
Add pipeline for pre-commit reasoner diffs

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-development-kit#107]
A developer may want to know: what is the impact of my latest change on inferences? For example, they may be editing some core subclass axioms, or they may be rebuilding an import module.

For GO, we have a complicated section of the Makefile:

https://github.com/geneontology/go-ontology/blob/c84008a509bf336cd32927f6aae3a3d4b084f7fc/src/ontology/Makefile#L449-L495

This is used to create a daily report sent to ontology developers highlighting entailment diffs.

For the odk we'd like to have something similar, but less complex.

The main challenge here is getting the artefact to diff against. The current GO job has an awkward dependency on Jenkins here.

One possible workflow is:

 1. get the last commit id, e.g. with `git log | head -1`
 2. `git stash`
 3. Build a `entailed_axioms` file using `reason`, call this `e1`
 4. pop the stash
 5. Build a `entailed_axioms` file as above, call this `e2`
 6. Diff e1 and e2

For diffing, robot diff could be used, OR I find that diffing on an obo file using unix diff is pleasant.

I'm not totally sure about messing around with git stash, seems easy for things to go wrong? Have to make sure the pop always works even if the reason step fails, we don't want to end up in a state where users appear to have lost their work.

An alternative would be to have a convention whereby the derived entails file is always checked in. This has some advantages, such as always having an audit trail of changes to entailments. But this too can get a bit awkward. Curators will sometimes have to resolve conflicts. Forgetting to commit the entailed file could result in confusion.

A 3rd alternative is to diff against the latest snapshot release of the ontology, but this relies on the ontology making snapshots available (like GO); or diffing against the latest released version.

**Comment by matentzn** [comment]
Wouldnt it be more sensible to diff with master rather than the last commit, assuming we are working on a branch? I would also advocate an ontology diff tool (be it Robot or something else) to avoid serialisation specific ordering issues. I am against 3 as the main diff mechanism, as release cycles (or even snapshot cycles) can be long, and reviewing should be happening every time a PR is about to be merged. I think comparing the branch against master is the most natural. 

+1 for making this a priority! Would be happy to add stuff to the ODK once we decided on a procedure.

**Comment by jamesaoverton** [comment]
I would be happy to see ROBOT diff improved, e.g. https://github.com/ontodev/robot/issues/360

**Comment by cmungall** [comment]
Additional note: there are two scenarios

 1. User has uncommitted changes and wants to reasoner-diff to HEAD
 2. User commits and pushes to branch, travis should reasoner-diff between HEAD and HEAD-2

The stash-pop workflow would be used for 1

**Comment by cmungall** [comment]
Replaced by #432
