### ISSUE TITLE
Slack access

### ISSUE THREAD

**Issue by Superraptor** [INCATools/ontology-development-kit#1072]
Hello! Just requesting Slack access.

**Comment by matentzn** [comment]
Shall I use your yale address?

**Comment by matentzn** [comment]
Bounced. Do you still have my email?

**Comment by Superraptor** [comment]
I moved institutions recently, just sent you an email (to your gmail) with my new email!

**Comment by matentzn** [comment]
Done! Welcome to OBO community slack!
