### ISSUE TITLE
Add comment in output that make command succeeded

### ISSUE THREAD

**Issue by marijane** [INCATools/ontology-development-kit#110]
Per the instructions in the editors readme file, I ran build.sh in my src/ontology directory.

I can't tell if it succeeded.  There's a bunch of errors, but it seems like it completed?  I don't know what to look for here.  I'm attaching a capture of my terminal output, hopefully someone can advise.
[build.sh.output.txt](https://github.com/INCATools/ontology-development-kit/files/2439980/build.sh.output.txt)

**Comment by matentzn** [comment]
As far as I can see, the conversion to OBO is indeed the last thing that happens, so it looks like it works. One test would be to check the latest update timestamp on your credit.obo and credit.owl classes.

**Comment by matentzn** [comment]
I will see whether I can add something to the output to make this clearer. 

BTW: Your process is pretty good for updating your ODK (re-create branch, create REPO etc). Maybe it is worth thinking about how we can make this yet a bit easier.

**Comment by marijane** [comment]
Thanks.  I think it did work.  An output message sounds like a good idea, something that communicates successful completion and perhaps also indicates what was built so it can be examined for correctness.

**Comment by matentzn** [comment]
Agreed! Thanks for the feedback! Will leave this ticket open until we have this in place.

**Comment by matentzn** [comment]
There is an output for a while now!
