### ISSUE TITLE
The ODK should take care of generating documentation for DOSDP patterns

### ISSUE THREAD

**Issue by gouttegd** [INCATools/ontology-development-kit#1101]
The CL custom Makefile includes a rule to generate some documentation pages from the DOSDP patterns:

```Makefile
pattern_docs:
	dosdp document -i ../patterns/dosdp-patterns/ -o ../../docs/patterns/ -d ../patterns/data/matches/
```

Given that the standard ODK Makefile already contains rule for about every task related to patterns (validation, query, generation), it should also include a rule for generating their documentation, without asking users to create their own rule like CL does above.

**Comment by gouttegd** [comment]
After toying with this idea a bit, I find that `dosdp document` crashes on too many pattern files for such a command to be of any use.

**Comment by balhoff** [comment]
@gouttegd have you tried `dosdp-tools docs`?

**Comment by gouttegd** [comment]
No, because I didn’t know the `docs` subcommand existed. Thanks!

Copying GO’s full command for reference:

```sh
$(DOSDP_TOOLS) docs --obo-prefixes=true --batch-patterns="$(ALL_PATTERN_NAMES)" --template=../design_patterns --outfile=../../docs/patterns --infile=../design_patterns --data-location-prefix='https://github.com/geneontology/go-ontology/tree/master/src/design_patterns/' --ontology=reasoned.owl --catalog=catalog-v001.xml
```
