### ISSUE TITLE
Travis says "make: robot: Command not found"

### ISSUE THREAD

**Issue by marijane** [INCATools/ontology-development-kit#111]
See build log: https://travis-ci.org/data2health/credit-ontology/builds/436408637

**Comment by matentzn** [comment]
Hmm, this is strange. Just as a test, can you add 

./run.sh 

right in front of the make test command (like [so](https://github.com/INCATools/ontology-development-kit/commit/b6327403da54017b54894385a8aedc42e1236782#diff-61487b96713b3af63ed3b962b32e8096)).

Chris recently removed the docker wrapper, maybe that was the problem?

**Comment by dougli1sqrd** [comment]
It looks like in the world @cmungall  is trying to set up, we need to do a little more in the travis config: 
https://docs.travis-ci.com/user/docker/#using-a-docker-image-from-a-repository-in-a-build

**Comment by marijane** [comment]
@matentzn Looks like that worked: https://travis-ci.org/data2health/credit-ontology 

Thanks!

**Comment by matentzn** [comment]
Old issue, closing.
