### ISSUE TITLE
Relax SubClassOf axioms by default

### ISSUE THREAD

**Issue by gouttegd** [INCATools/ontology-development-kit#1114]
ROBOT’s `relax` command has a [`--include-subclass-of` option](https://robot.obolibrary.org/relax#include-subclass-of) to relax _SubClassOf_ axioms where the superclass is an intersection, e.g. to turn

> CL:0000104 **SubClassOf:** CL:0000540 _and_ (RO:0000053 _some_ PATO:0070026)

into

> CL:0000104 **SubClassOf:** CL:0000540
> CL:0000104 **SubClassOf:** RO:0000053 _some_ PATO:0070026

That option should be enabled by default in the ODK-generated standard pipelines, given that (1) the two forms are exactly equivalent (contrary to the relaxing of **EquivalentTo** axioms, where the relaxed form is a weaker assertion), and (2) the non-relaxed form is known to cause downstream issues, for example when converting to the OboGraphs JSON or OBO formats.

**Comment by matentzn** [comment]
I agree, should be default!

**Comment by gouttegd** [comment]
Side note regarding @cmungall ’s comment: Sounds like this could also be a topic for the OBOOK at some point.
