### ISSUE TITLE
Requesting access to Slack!

### ISSUE THREAD

**Issue by RubenPeeters** [INCATools/ontology-development-kit#1133]
Hi! I've recently started using ODK to develop ontologies and it would be amazing if I could be part of the relevant Slack community. My email is ruben.peeters@kuleuven.be

Let me know if you need any more information!

**Comment by matentzn** [comment]
@RubenPeeters welcome, and I have sent you an invite.. I suggest you edit your comment and obfuscate your email now; I don't think it makes a difference in today's day and age but one less public place with an email could mean 5 less spam emails down the line!
