### ISSUE TITLE
Standard Makefile should define a REASONER variable

### ISSUE THREAD

**Issue by gouttegd** [INCATools/ontology-development-kit#1139]
The ODK configuration file allows to specify the reasoner to use for the entire project, for example:

```yaml
reasoner: WHELK
```

In the standard, ODK-generated Makefile, all ROBOT commands that require a reasoner will automatically use the reasoner specified in the configuration file. But this is done by injecting the name of the reasoner for every single command, as in:

```Makefile
reason_test: $(EDIT_PREPROCESSED)
        $(ROBOT) reasoner --input $< --reasoner {{ project.reasoner }} ...
```

Instead, the Makefile should contain a single `REASONER` variable at the top:

```Makefile
REASONER = {{ project.reasoner }}
```

which should then be used in all reasoner-requiring commands:

```Makefile
reason_test: $(EDIT_PREPROCESSED)
        $(ROBOT) reasoner --input $< --reasoner $(REASONER) ...
```

There would be two benefits:

(1) It would make it very easy for a project to quickly test a different reasoner, by simply overriding the `REASONER` variable, instead of having to change their ODK configuration and re-generate the standard Makefile.

(2) When a project has some custom workflows in the `$(ONT).Makefile`, they would be able to automatically use the same reasoner as the standard workflows without having to even think about it, and without having to update their workflows if the project decides to change their reasoner.

**Comment by matentzn** [comment]
Sounds good!
