### ISSUE TITLE
Add SQLite/SemSQL as an export format

### ISSUE THREAD

**Issue by gouttegd** [INCATools/ontology-development-kit#1142]
The ODK should allow to produce release artefacts that are SQLite files conforming to the [INCATools/semantic-sql schema](https://github.com/INCATools/semantic-sql), alongside the other “traditional” formats (OWL, OBO, etc.).

`semsql` itself and the tools it depends on (`rdftab`, `relation-graph`) are already part of the ODK, so it should be relatively straightforward (I hope I won’t regret writing that!).

(`rdftab` and `relation-graph` are only present in _ODKFull_, though – that’s annoying if we want the SemSQL artefacts to be produced by default, because I am keen to keep the standard workflows depending only on ODKLite.)

**Comment by cmungall** [comment]
I regret to inform you that there hasn't been much progress on:

 - https://github.com/INCATools/semantic-sql/issues/41

Which would make this easier

**Comment by gouttegd** [comment]
Well, as I said, the tools we need are already there anyway (we build `rdftab` from source and we have a running version of `relation-graph`). Making those tools easier to install would still be a good thing overall (for other users), but for the ODK it’s too late. :)

Now we _just_ need to use them.
