### ISSUE TITLE
`use_context` creates the context file at the wrong place

### ISSUE THREAD

**Issue by gouttegd** [INCATools/ontology-development-kit#1146]
When the `use_context` config option is enabled, the `_dynamic_files.jinja2` template creates a default context file in `config/context.json`:

```jinja2
{%- if project.use_context %}
^^^ config/context.json
{
	"@context": {
		"obo": "http://purl.obolibrary.org/obo/",
		"oboInOwl": "http://www.geneontology.org/formats/oboInOwl#",

		"rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
		"rdfs": "http://www.w3.org/2000/01/rdf-schema#",
		"rdfa": "http://www.w3.org/ns/rdfa#",
		"xml": "http://www.w3.org/XML/1998/namespace",
		"xsd": "http://www.w3.org/2001/XMLSchema#",
		"owl": "http://www.w3.org/2002/07/owl#",

		"dc": "http://purl.org/dc/terms/",
		"foaf": "http://xmlns.com/foaf/0.1/",
		"prov": "http://www.w3.org/ns/prov#",
		"skos": "http://www.w3.org/2004/02/skos/core#",
		"void": "http://rdfs.org/ns/void#"
	}
}
{%- endif %}
```

But the Makefile expects that file to be under `src/ontology/config/context.json`:

```jinja2
{%- if project.use_context %}
CONTEXT_FILE =              config/context.json
{%- endif %}
```

One of those two templates is wrong.

(Or both of them: for what it’s worth, I think the `config` subdirectory should be under `src`, not under `src/ontology`, so the context file should be under `src/config/context.json`)

**Comment by gouttegd** [comment]
@matentzn Any preference as to where should the context file be located:

* `config/context.json`
* `src/config/context.json`
* `src/ontology/config/context.json`

?

My own preference goes to the second option, but I don’t really mind either way.

**Comment by matentzn** [comment]
I follow your nose, I personally like `src/ontology/config/context.json` but I am also happy with `src/config/context.json`.

**Comment by gouttegd** [comment]
You said elsewhere that you were already using `src/ontology/config/`, so no reason to change. Since it’s not a big deal either way, let’s use what already exists.
