### ISSUE TITLE
`sparql_test` does not cover components

### ISSUE THREAD

**Issue by gouttegd** [INCATools/ontology-development-kit#1154]
The standard Makefile includes a `sparql_test` target (executed as part of the `test` target) which runs a bunch of SPARQL-based checks using `robot verify`:

```Makefile
sparql_test: $(EDIT_PREPROCESSED) | $(REPORTDIR)
        $(ROBOT) verify -i $(EDIT_PREPROCESSED) --queries $(SPARQL_VALIDATION_QUERIES) -O $(REPORTDIR)
```

Those checks only operate on the contents of the (preprocessed) `-edit` file; they do _not_ cover any imported ontology (actual ODK imports and components). This may not be explicitly documented in ROBOT’s manual, but a [brief look at the code](https://github.com/ontodev/robot/blob/35b830fac23056203c89b3b1984902b61cd07e58/robot-command/src/main/java/org/obolibrary/robot/VerifyCommand.java#L116) shows this is the normal behaviour of the `verify` command, and that this behaviour is not configurable:

```java
// Load into dataset without imports
Dataset dataset = QueryOperation.loadOntologyAsDataset(state.getOntology(), false);
```

I don’t think it is correct for the `sparql_test` to cover only the contents of the `-edit` file. Of course it is fine to exclude _imports_ (in the ODK sense) from the SPARQL tests (we may not want those tests to fail because of something coming from an external ontology), but _components_ (and I include under that umbrella the pattern-derived `definitions.owl` file) are merely parts of the “local” ontology that just happen to be in different files -- I see no reason for excluding them from the SPARQL tests.

Therefore, and since `verify` will not follow OWL imports declarations, I believe the `sparql_test` should be executed over the `$(SRCMERGED)` file (in which components, that is, all files listed as `$(OTHER_SRC)`, have been explicitly merged in) rather than `$(EDIT_PREPROCESSED)`.

**Comment by matentzn** [comment]
You are right. The default could be changed to SRC_MERGED

**Comment by gouttegd** [comment]
Note that this may wreak havoc in existing repos when such a change lands in a released version…

Currently, in all existing ODK setups, the contents of components is _not_ checked, so any kind of violations may have crept up in components without ever being caught. All of a sudden, components _will_ be checked, and ontologies that previously passed the `sparql_test` check may now very well fail it.

**Comment by matentzn** [comment]
I thought of that as well, but there is no great way around it.

1. Any QC we have configured is in fact designed to apply to components
2. People can manually shut the QC off if they so want to rather than fix stuff

I am fine with the fallout

**Comment by gouttegd** [comment]
> I thought of that as well, but there is no great way around it.

Agree. If any pipeline fails because of that change, it will ultimately be because the components contain (possibly have always contained) errors. The new ODK will merely reveal those problems, not cause them.

**Comment by matentzn** [comment]
Maybe make sure to add a strong node in Changelog so we remember making a strong node when we publish 1.6
