### ISSUE TITLE
Using the ODK with non-OBO ontologies?

### ISSUE THREAD

**Issue by marijane** [INCATools/ontology-development-kit#116]
So over at data2health, we have this project created with the ODK:
https://github.com/data2health/credit-ontology

Because this is an OWL implementation of CASRAI's work, we decided we didn't want to submit it to the OBO Foundry and we're using a w3id instead.  What I'm wondering is what I might need to do to make sure the project refers to the w3id instead of purl.obolibrary.org?  I notice when I open the project in Protege that the Active Ontology chooser is showing an obolibrary.org URI.

**Comment by cmungall** [comment]
All I can suggest for now  is a global search and replace at the text level on the OWL file.

hacker's tip:

```
perl -pi -ne 's@http://purl.obolibrary.org/obo/MYONT_@http://w3id/myont/@' myont-edit.owl
```

It's a bit hard for us to make the ODK seed script more general than what is standard for OBO right now. The general guideline is that things should still work, but will need ad-hoc adaptation.
