### ISSUE TITLE
Add integration tests

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-development-kit#118]
As well as self-contained unit tests, new ontologies should be tested for consistency against some to be defined merged set of base files of core OBOs

**Comment by matentzn** [comment]
@cmungall +1 
can you give a little bit more detail? I assume the tests should be conducted as part of the pre_release/release cycle, and should be implemented right where these SPARQL tests are happening (no equivalent, unsat classes etc). which ontologies where you thinking to test against?

**Comment by cmungall** [comment]
There are a few possibilities, not mutually exclusive. We also to have to take into account considerations like tractable travis builds.

Current thinking:

as part of each RO release N we build a merged set of base ontologies, to be in the set you should be using RO in a meaningful way. This ro-users ontology can be released as part of the RO release, but just logical axioms, and zipped. Not intended for general consumption.

Then, for each travis build on each snapshot / candidate release N+1, we download ro-users and test the combo of ro_users + ro_edit.

Occasionally we will hit deadlock situations, when we need to introduce a breaking change. Here we work with the upstreams and then release a new ro-users, when we can break the deadlock.

**Comment by cmungall** [comment]
Doomed to repeat myself: https://github.com/owlcs/owlapi/issues/375#issuecomment-112939222

**Comment by cmungall** [comment]
The test I am envisioning above is just coherency.

But would be good to have a proper test framework, where we can state expected outcomes of inference

**Comment by matentzn** [comment]
For now, we test against the imports, but we will revive this issue anyways when the time for COB comes.
