### ISSUE TITLE
Seed new repo with ODK and uberon import creates a massive (13K axiom) uberon module

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#131]
Reproduce:
```
 ./seed-via-docker.sh -c  -d uberon ro pato -u cmungall -t "Triffid Behavior ontology" triffo
```
and then
```
open target/triffid-behavior-ontology/src/ontology/imports/uberon_import.owl 
```

I believe the problem lies in a weird interaction with some unsatisfiable classes in uberon and the SLME, where axioms are being extracted even if the seed is empty, but I am not sure. 

@cmungall @balhoff 

one way to deal with this, which is brutal and I would object slightly, is to force the mirrored uberon to be coherent by dropping all axioms mentioning all unsatisfiable classes from it. This will result in hugely incomplete modules - but at least we can be sure that the empty or disjoint seed does not export a big module for no reason.

It is also possible that I am wrong and the module is extracted due to some weirdness in the default seed we add to the ODK (we should really rethink that approach).

**Comment by cmungall** [comment]
Well #126 will help as we can have default configs for some ontologies such that only base modules are pulled

**Comment by matentzn** [comment]
Not an ODK problem.
