### ISSUE TITLE
Add ammonite to docker image

### ISSUE THREAD

**Issue by balhoff** [INCATools/ontology-development-kit#133]
Is there any opposition to adding [Ammonite](http://ammonite.io/#Ammonite) to odk-full? It would be handy to run standalone Scala scripts this way.

**Comment by balhoff** [comment]
The scripts are standalone in the sense that they only depend on Ammonite to run—they import library dependencies from Maven Central on the fly, e.g. https://github.com/balhoff/ammonite-scripts/blob/master/explain_ontology_inference_diff.sc uses external libraries (see $ivy imports) but these don't need to be in the docker image (python needs something like this!)

Will look into image size.

**Comment by matentzn** [comment]
Yeah, I also wanted to ask the same, because I need to add pandas to the python packages for some of the curation pipelines I developed for XPO and ZP. Alternatively, I have my own container for those; its just another container in the end. Does adding ammonite grow the image size?

**Comment by balhoff** [comment]
Adding ammonite increases the image size by 60 MB (1.42GB to 1.48GB).

**Comment by cmungall** [comment]
Let's add it!

(should have known, those ammonoids are highly buoyant)

**Comment by balhoff** [comment]
One wrinkle: now that I've tested this out, I see that every time you run a script with `amm` in the docker container, it re-downloads all the Java dependencies, since it doesn't make use of the local Ivy cache. What gets downloaded depends on what's in the script, but it can transitively be sizable. For a typical script I'm using it's a couple minutes added to the startup. In a non-docker situation this would normally be cached really well. It's awesome that ammonite scripts can specify their own dependencies, but this is kind of annoying.

**Comment by balhoff** [comment]
I'm going to see if I can work out how to make use of the user's `.ivy2` cache during the run, I guess with some application of `-v`. If any of you already know how to do it, let me know. :-)

**Comment by balhoff** [comment]
@matentzn can we add ammonite? I don't think this ever went in.

**Comment by matentzn** [comment]
Of course. Do you mind working out the pull request and assign me to review? Does it have anything consequences for anything else? Image size difference reasonable?

**Comment by matentzn** [comment]
@balhoff do you still want this: :P I am very happy for this to be added if you can make a PR!

**Comment by matentzn** [comment]
Fixed in https://github.com/INCATools/ontology-development-kit/pull/307
