### ISSUE TITLE
DOSDP too strongly tied into ODK

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#136]
The Makefile is too dependent on the DOSDP pipeline, in particular the generation of definitions.owl, which is not optional anymore. We need to make sure that the new version of the ODK decouples patttern generation again from normal ODK release business.

**Comment by cmungall** [comment]
See the pr for jinja templates should solve all this

**Comment by matentzn** [comment]
@cmungall you cant by any chance make tomorrows ODK meeting slot and give us a brief walk through what you have done? I lost a bit of track :)

**Comment by matentzn** [comment]
New ODK takes care of that
