### ISSUE TITLE
Extend and test new ODK yaml config to enable the inclusion of base products where appropriate

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#143]
When generating imports and use_base_for_imports=TRUE, look for PURL/hp-base.owl and if exist, use this for generating the module, if not, use hp.owl. Makes sense? @cmungall @balhoff

**Comment by balhoff** [comment]
I think that sounds great. My only reservation is that I feel like we need to come up with some approach for pointing out missing transitive imports. Like maybe base files should always be annotated with the imports used, so that this can be parsed and logged.

**Comment by cmungall** [comment]
So this would be a dynamic lookup, at the time of running `make`? I worry this would lead to non-deterministic or unpredictable behavior.

What I had in mind was an option that would explicitly be set in the yaml for each imported ontology. The disadvantage is that it forces the maintainer to do a bit of homework and this can all seem a bit abstruse to some.

**Comment by matentzn** [comment]
Oh forgot about that.  That is of course preferrable! Renaming ticket.
