### ISSUE TITLE
Python version in Dockerfile is different than what odk.py expects causing tests to fail

### ISSUE THREAD

**Issue by dougli1sqrd** [INCATools/ontology-development-kit#145]
The Dockerfile in `ontology-development-kit` installs python3 `RUN apk add --no-cache python3`. This installs python version 3.5:

```
docker run -v $PWD/:/work -w /work --rm -ti obolibrary/odkfull python3 --version
Python 3.5.3
```

Travis, runs `make test`, which at a certain point runs `odk.py`. This file uses the mypy type annotation style for variables only added in python 3.6: `memory_gb : Optional[int] = None` (from line 41 in odk.py).

This document here: https://mypy.readthedocs.io/en/latest/cheat_sheet_py3.html indicates that this syntax feature is only available in python 3.6. 

This is causing unrelated odk changes to fail the travis build. How this passed travis builds in the first place is an unknown, but this should be fixed so new PRs can pass Travis checks.

**Comment by cmungall** [comment]
It's possible the yaml PR was failing originally - is there an easy way to use python3.6 in alpine?

**Comment by matentzn** [comment]
Was fixed by the above.
