### ISSUE TITLE
Report gives a lot of duplicate labels, but I cant confirm any

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#148]
Report of new ODK shows a lot of errors because of 'duplicate_label', but I cannot confirm any of them.

ERROR | duplicate_label | HP:0004828 | rdfs:label | Refractory anemia with ringed sideroblasts
-- | -- | -- | -- | --
ERROR | duplicate_label | HP:0000143 | rdfs:label | Rectovaginal fistula
ERROR | duplicate_label | HP:0002035 | rdfs:label | Rectal prolapse
ERROR | duplicate_label | HP:0002974 | rdfs:label | Radioulnar synostosis

same with some 'duplicate_definition' errors.

**Comment by rctauber** [comment]
What ontology are you running this on? I'll look into it.

**Comment by matentzn** [comment]
https://github.com/obophenotype/human-phenotype-ontology/tree/odk-hp/src/ontology

if you prefer the merged artefact for testing:
https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/odk-hp/hp.owl

(its on a branch)

**Comment by rctauber** [comment]
Ah, I found the problem 😃 

The query checks that `?entity` is not blank, but it does not check that `?entity2` is not blank. HP has some blank nodes that have the duplicate labels. The fix would be to make sure `?entity2` is not blank as well. We are doing a review of ROBOT report with the OBO ops committee and will probably be making some updates for that. I'll make sure this gets added to my list.

**Comment by matentzn** [comment]
cheers thanks! :) Can you just post a revised query once you have it? I could chip in a bit on the report feature, if you could link the right ROBOT issue that would be great. :)

**Comment by rctauber** [comment]
It's a pretty easy fix, the new dup label query would be:
```
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?entity ?property ?value WHERE {
  VALUES ?property {rdfs:label}
  ?entity ?property ?value .
  ?entity2 ?property ?value .
  FILTER (?entity != ?entity2)
  FILTER (!isBlank(?entity))
  FILTER (!isBlank(?entity2))
}
ORDER BY DESC(UCASE(str(?value)))
```

And the dup definition query would be:
```
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?entity ?property ?value WHERE {
  VALUES ?property { obo:IAO_0000115 }
  ?entity obo:IAO_0000115 ?value .
  ?entity2 obo:IAO_0000115 ?value .
  FILTER NOT EXISTS { ?entity owl:deprecated true }
  FILTER NOT EXISTS { ?entity2 owl:deprecated true }
  FILTER (?entity != ?entity2)
  FILTER (!isBlank(?entity))
  FILTER (!isBlank(?entity2))
}
ORDER BY DESC(UCASE(str(?value)))
```
I haven't opened an issue for the updates yet, but as soon as I do, I'll loop you in. I appreciate the offer to help! It's more about waiting on feedback now, as the queries themselves are pretty easy to change...
