### ISSUE TITLE
New approach of merging the main release file (ontology.owl) scratches GitHub file-size limits

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#149]
the new hp.owl ([link](https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/odk-hp/hp.owl) to branch) is hovering dangerously close to the 100MB margin. If this policy of merging release ontologies is set to continue, we need to start thinking what to do with files larger than 100MB. We absolutely need a check in the ODK QC to look for files exceeding that limit in any case; accidentally committing a large file is a massive pain. 

But what should be the default behaviour? I think ODK should deal with this somehow, no?
@cmungall @balhoff @dosumis

**Comment by balhoff** [comment]
GitLab is one git-based option, e.g. https://gitlab.com/phenoscape/vto/blob/master/releases/vto.owl

**Comment by matentzn** [comment]
Yeah, interesting. Am I correct in assuming that we are all tied to GitHub mainly because of workflow and culture? There is not really a technical reason (travis etc), right?

What is your suggestion to progress on the issue?
1. If a file is larger than 100MB, git rm and git ignore it
2. Store it somewhere manually (we will see about ideas where later, and how to automate)
3. Edit the purl.yml config and redirect the purl of that particular file to its new location?

**Comment by cmungall** [comment]
For MONDO this is our current procedure

We attach the files as downloads e.g.https://github.com/monarch-initiative/mondo/releases/tag/v2019-08-28

script to automate this (could be moved to odk)

https://github.com/monarch-initiative/mondo/blob/master/src/utils/make-release-assets.py

But @matentzn and @kltm favor using Zenodo

**Comment by cmungall** [comment]
for DrOn @hoganwr gets around this by using atlassian/bitbucket he may be interested in this thread

**Comment by matentzn** [comment]
I will close this;

We are now using GitHub releases for all such cases.
