### ISSUE TITLE
Making sure ROBOT query for seeds includes imports

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#158]
We make a lot of use of ROBOT query (Makefile). Now I had a lot of problems when using base-imports, because query does not take into account imports by default. I suggest to replace the current incantations by:

```
$(ROBOT) query --use-graphs true --catalog catalog-v001.xml -f csv -i $< --query ../sparql/terms.sparql $@
```
essentially adding

```
--use-graphs true --catalog catalog-v001.xml
```

Does this make sense @rctauber @cmungall

**Comment by rctauber** [comment]
You shouldn't need to specify the catalog as ROBOT is pretty good about guessing that, unless you have a catalog in a different folder or with a different name. Does it work correctly if you *only* add `--use-graphs true`?

**Comment by matentzn** [comment]
I think it should! Thanks for the clarification :)
