### ISSUE TITLE
There are two instances where ROBOT query ignores imports

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#164]
In 2 cases, ROBOT query ignores imported ontologies. If you want imported ontologies to be taken into account, we need to add --use-graphs true in both cases.
1:
```
subsets/%.tsv: subsets/%.owl
	$(ROBOT) query -f tsv -i $< -s ../sparql/labels.sparql $@
```
2:
```
all_reports_onestep: $(SRC)
	$(ROBOT) query -f tsv -i $< $(SPARQL_EXPORTS_ARGS)
```

**Comment by cmungall** [comment]
I think the intended behavior in most cases is to query base. It may be useful in some cases, e.g. when writing edge lists to do lookups on labels in imported ontologies. 

Maybe there should be two sets of reports, one for base, one for full graph
