### ISSUE TITLE
Travis test uses odk.py from dockerhub which leads to circularities

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-development-kit#167]
I think we need to add something to the docker run such that /work/odk/odk.py (local) takes priority over /tools/odk.py (container)

**Comment by cmungall** [comment]
oh wait we do this already in the Makefile

```
CMD = ./odk/odk.py seed
```

So I'm confused by the apparent circularity mentioned by @matentzn in #166

**Comment by matentzn** [comment]
Oh, I never paused to think whether it was just the ODK.py file itself;
during the last set of changes, I had to touch quite a few files, starting
from the jinja templates to the various make files; one of them, but I
can’t know for sure which, required rebuilding the docker image in order to
correctly execute the new functionality. It’s possible i confused this with
some other issue at the time though :/

**Comment by ramonawalls** [comment]
This issue seems to be causing me problems. I am not able to run several make targets that require /tools/odk.py, such as `make update_repo`.

**Comment by ramonawalls** [comment]
Thanks, Nico. I've tried make update repo command at least 10 times, and it still gives me the error:

```
../scripts/update_repo.sh: line 14: /tools/odk.py: No such file or directory
make: *** [update_repo] Error 1

I've tried copying the odk.py file to my computer to various locations, but that does not seem to help. I'm not sure where it is looking for it.

I'm running make directly, not from within a container.

**Comment by ramonawalls** [comment]
I just figure out how to fix this, by running `sh run.sh make update.repo`. It created the tools directory.

It still does not work without using the shell script, but I can run things via that script now that I have added it to my repo.

**Comment by matentzn** [comment]
Yeah, right now, there is no guarantee of _anything_ working in the ODK code base outside the context of the ODK container - you will always have to go through the container (run.sh). Copying odk.py certainly will give problems - you should not need that at all. 

I also wrote a new tutorial for getting started with ODK in OBO Academy: https://oboacademy.github.io/obook/tutorial/setting-up-project-odk/

**Comment by ramonawalls** [comment]
Thank you, Nico. And happy new year! I think this ticket can be closed now.

**Comment by matentzn** [comment]
Happy New Year Ramona! :)
