### ISSUE TITLE
Template travis job currently runs 'make test': there is AFAICS no goal test

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#172]
@cmungall What is the correct goal to run during in travis? make? make all? 

We also still have the problem of [travis not picking up docker](https://github.com/INCATools/ontology-development-kit/issues/111)

**Comment by cmungall** [comment]
this is for an ontology, not the ODK itself?

There should be a test target, perhaps it was accidentally omitted during the jinja refactor.

The best test is to do a complete dry run of a release, but this may take a long time for some ontologies, so maybe we want to provide `test` and `full_test` with the default being to run reason on the ontology plus robot report, but no rebuilding of imports or downstream products

**Comment by matentzn** [comment]
yeap, for ontology. Will take care of this.
