### ISSUE TITLE
Policy for overwriting standard Makefile goals

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#173]
Some ontology developers have very specific ideas of how their main deployed artefacts should look like. For example, HP does not want inferred axioms in their deployed artefacts for now. In the interest of extensibility, do we need to extend the odk to allow more fine grained configuration of the main goals, like inferred=true, etc etc? @cmungall 

Or can we somehow overwrite existing targets using the second Makefile? 

For now, I will manually overwrite their Makefile goals (so we move forward). Let me know what you think the way forward is here.

**Comment by cmungall** [comment]
HPO is hopefully the only outlier here, and hopefully short-lived.

What about just passing a "SubClass-only" reasoner? I think HPO will still want things like redundancy removal

**Comment by matentzn** [comment]
I will instead update the README with instruction on how to update the ODK makefile I think (and give them their own OBO and OWL goals). For political reasons :) I will lobby for the OWL version to be moved to inferred; seb has already agreed to go with merged!

**Comment by cmungall** [comment]
Given that OLS applies Elk, stopping the reasoning at this stage is just a
stopgap and a potentially confusing one, as people will get different
results in different browsers.

Really we just need to get things in a state where inference is not wrong,
even if incomplete

**Comment by matentzn** [comment]
I will elevate implementing the inference review method in terms of priority.
