### ISSUE TITLE
Travis failure on first release attempt.  Help?

### ISSUE THREAD

**Issue by marijane** [INCATools/ontology-development-kit#176]
I attempted today to release the Contributor Role Ontology for the first time.  Everything seemed fine when I ran the build.sh and prepare_release.sh scripts, but once I pushed to GitHub, the Travis build failed, and I'm not sure why.  Can someone help me debug?

The Travis build details are at https://travis-ci.org/data2health/contributor-role-ontology/builds/497217532

**Comment by matentzn** [comment]
Hey @marijane 

Seems to me this was bad luck! Maybe dockerhub was offline or something. Can you try to trigger the Travis job again?

Thanks!

**Comment by marijane** [comment]
@matentzn Thank you!  It totally worked the second time.  I wish I had realized that was the problem!  Oh well, live and learn. =)
