### ISSUE TITLE
Need an odkfull docker release

### ISSUE THREAD

**Issue by balhoff** [INCATools/ontology-development-kit#179]
Is there any reason not to make a docker release for odkfull from master? We need to get the latest owltools for GO.

**Comment by matentzn** [comment]
It just adds an extra layer of security; I quite like it know. But I am open, if everyone votes for dynamic built, I can change that as well. Slight tendency to the manual approach now.

I just built and pushed a new version up, but you can always do this yourself by simply running `make docker-publish` in the root directory of the odk.

**Comment by balhoff** [comment]
Thanks @matentzn! I think I was unclear: I didn't mean to push for a totally dynamic build; just wanted to make sure there wasn't anything in progress on master that shouldn't be released. For some reason the newest owltools didn't get into this image. I will try to figure it out.

**Comment by matentzn** [comment]
Oh! Yeah let me know what you find! That is important! The build log said that something related to dosdp and owl tools was downloaded.

**Comment by cmungall** [comment]
At the moment the dockerfile uses the owltools built on Jenkins maybe that
didn't build?

**Comment by balhoff** [comment]
I ran the Jenkins build yesterday. I downloaded it directly a few minutes ago to check the version. Seems okay.

**Comment by matentzn** [comment]
well the only thing I can think off is that docker-build skips the step where the owltools is installed. have you tried running make docker-build locally and then test the odk?

**Comment by balhoff** [comment]
Doing it now!

**Comment by matentzn** [comment]
And?

**Comment by balhoff** [comment]
I rebuilt and published and the new owltools seems to have gotten in.
