### ISSUE TITLE
Document protocol for Windows users of ODK

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-development-kit#181]
Proposed docs for Windows users:

IF you have Windows 10 PROFESSSIONAL, then follow the same instructions as mac/linux

IF you do not have Windows 10 professional, then unfortunately we cannot support you at this time; we recommend

 - For seeding a new repo, borrow access to a linux/mac. Fortunately this does not need to be done frequently
 - For managing releases, install Cygwin, install ROBOT, install dosdp-tools, and then run `make release`. I believe this process currently works for @pbuttigieg , testing now with @kaiiam

**Comment by cmungall** [comment]
@matentzn curious of all the people in the pheno group, who is making their own releases, and are they all mac-based?

**Comment by matentzn** [comment]
Yeah, all Mac! @srobb1, @chris-grove do their own releases already, @seger and @drseb soon as well; All are afaikt mac based.

**Comment by matentzn** [comment]
This is now documented extensively here https://oboacademy.github.io/obook/howto/odk_setup/
