### ISSUE TITLE
docker windows quickstart terminal complains when trying to remove _dynamic_files

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-development-kit#183]
@matentzn we discussed this earlier, @kaiiam and I have a solution...

**Comment by cmungall** [comment]
hmm, doesn't seem to work

**Comment by matentzn** [comment]
I have a vague intuition that it might work if you compiled the template dir in a directory inside the container and then copy it to the target directory when it is done. :P But this is just a vague theory.

**Comment by matentzn** [comment]
We have never encountered this again, please reopen if still and issue.
