### ISSUE TITLE
make test should run reasoner only

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-development-kit#19]
Currently `make test` is the same as `make all`

 - rebuilding imports may be quite expensive on travis
 - odd timing issues can mean that reasoner is not executed (noticed by @marieALaporte )

By default, make test should run reasoner checks over whatever the latest version of the edit file is without attempting to rebuild imports.

**Comment by cmungall** [comment]
Timing issues: in general the reasoner should always be executed so long as foo.owl is less recent than foo-edit.owl

What can happen sometimes is:

 - A release is made with a coherent ontology on t1
 - various other things change at t2, but foo-edit.owl remains unchanged
 - these external changes render the ontology incoherent

If this happens, the travis build will always say success. We would rather it fails fast

**Comment by matentzn** [comment]
Is this still current?
