### ISSUE TITLE
Run report over the base artefact instead the merged full ontology

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#195]
@cmungall I think it is a no brainer, but wanted to get permission. Currently running on merged owl, which raises too many errors unrelated to the ontology at hand.

**Comment by matentzn** [comment]
I think this makes sense. I will switch to that, if you disagree, I will revert it :)

**Comment by matentzn** [comment]
Maybe I was wrong. Thousands of missing label and definition ERRORs, of course, if this is done on the base file. Maybe it needs to be the edit file after all.

**Comment by cmungall** [comment]
See comments here: https://github.com/ontodev/robot/pull/267#issuecomment-390515372

But maybe the proposal there is too complex

Ultimately I want to release a good product at the end of the day, so if an upstream module is failing some checks it is my responsibility to either work with the upstream or find some alternative.

**Comment by jamesaoverton** [comment]
ROBOT `report` supports custom profiles. I'm happy to ship more than one profile with ROBOT, as long as we can be very precise about different requirements for edit/base/full -- good progress is being made in #194. But my current thinking is that it's better to specify the profile externally (i.e. in the `Makefile`) than internally (i.e. in the OWL file).

**Comment by matentzn** [comment]
This has been configurable for a while now.
