### ISSUE TITLE
Create a readthedocs for ODK

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-development-kit#198]
This could be a combination of

 - using ODK to set up a repo
 - editors guide adapted from https://go-ontology.readthedocs.io/en/latest/

**Comment by matentzn** [comment]
@cmungall I am very willing to start contributing! Is there already a readthedocs for odk anywhere?

**Comment by cmungall** [comment]
https://github.com/INCATools/ontology-development-kit/tree/master/docs

**Comment by matentzn** [comment]
Oh without knowing about that this is readthedocs, i already started adding some stuff there. 

I assume this is the deploy location:
https://ontology-development-kit.readthedocs.io/en/stable/README.html?highlight=ontology%20development%20kit#

Can you make it that: 
https://ontology-development-kit.readthedocs.io/

redirects to some overview pages of the docs? Right now it redirects to some GO related docs.. Also if it is not too much trouble, how can I update the read the docs pages? I made some changes a while ago (added a page, ReleaseArtefacts.md), but they dont show up yet :/ Sorry new to this.

**Comment by cmungall** [comment]
Sorry haven't got round to this yet

**Comment by matentzn** [comment]
Widely implemented feature now.
