### ISSUE TITLE
Video Tutorial Series for Ontology Curation and release management with Robot, DOSDP and ODK

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#206]
It becomes increasingly important to train curators to write basic QC components for their ontologies, release their ontology using the ODK and managing their definitions using the DOSDP pattern system. With Robot, it has become easier than ever to write your own QC modules and fiddle them into the release pipeline. 

I propose a joint OBO-Monarch seminar series with short video tutorials covering the most important use cases for curation, release management, quality control and pattern based development. I am happy to do the actual recordings, but I would like some help with the following tasks: 

1. Collecting the most common scenarios for which it would be beneficial to record a tutorial
2. Managing a bespoke Youtube or whatever channel to manage the series
3.  Produce the videos (I would supply raw recordings, which would need to be could and merged and get some kind of OBO/Monarch/ROBOT credits thingy in the end).

What do you think?

**Comment by LCCarmody** [comment]
Yes, definitely.  Obsoleting (terms, synonyms, etc), merging, developing patterns, the difference between in part and in part of ;), and building ontologies are among the tops of my list.

**Comment by jpgourdine** [comment]
Yes, it will be helpful.

**Comment by diatomsRcool** [comment]
I would definitely use such a thing. Maybe drafting a "cheat sheet"?

**Comment by chris-grove** [comment]
Yes, this would certainly be helpful. In particular, QC components, ontology building best practices, ODK basics, pattern development, and how patterns are used to infer desired tree outputs after reasoning (to better design patterns intentionally)

**Comment by rctauber** [comment]
+1 - and happy to help with the ROBOT tutorial materials. 😄

**Comment by nicolevasilevsky** [comment]
Yes, I love this idea and am happy to help.

**Comment by sbello** [comment]
Love this idea and am happy to be a test user

**Comment by matentzn** [comment]
@nicolevasilevsky @monicacecilia

I like Camtasia, and even have an old license. It costs around 300 quit though, and I believe iMovie for Mac may be sufficient for us. Maybe we can start a very crude workflow like this. We both have iMovie installed. We have a shared dropbox. I create a folder for each tutorial, and create a very preliminary arrangement in iMovie. Save it in folder. Ping you. Then you go and cut and clean it, and post it somewhere. As Monarch pays for this and the tooling is OBO foundry, I would like a 3-second credit slide in the end with the Monarch and OBO foundry logos and a suitable blurp that assigns credit. Shall we try that @nicolevasilevsky ?

**Comment by matentzn** [comment]
We can start with 3 test videos, get some feedback from @sbello and @chris-grove and iterate until we find a style that works.

**Comment by monicacecilia** [comment]
@matentzn @nicolevasilevsky  Alright. Let's give it a try with iMovie. 
In my experience, the best way to create a tutorial is:
1. Start with a script: type everything you want to say and how you want to emphasize it. 
2. Either prepare a screen recording or still images to tell **that** story. 
3. Record the voice over separately - quiet room, use mic, and in the absence of a sound booth, place a piece of cloth over your head to make it a 'dry' sound. 
4. Edit content together and do a happy dance. :bowtie: 

I have not used iMovie, but I imagine it may work similarly to Camtasia - (btw, I think the @cmungall Lab has licenses; perhaps we could use one for Monarch work). @nicolevasilevsky, please let me know if I can help getting you started. 🎥

**Comment by cmungall** [comment]
No license, sorry!

>

**Comment by monicacecilia** [comment]
ack! too bad. 😞 
thanks for checking!

**Comment by nicolevasilevsky** [comment]
@monicacecilia - yes, some help with iMovie would be great. Should we wait until @matentzn has created some videos for us to edit?

@matentzn if you would like help writing the scripts, let me know

**Comment by matentzn** [comment]
This has been realised largely by OBOOK. No further action required.
