### ISSUE TITLE
seed-via-docker fails on MacOS

### ISSUE THREAD

**Issue by mconlon17** [INCATools/ontology-development-kit#209]
I recently setup the INCA tools on macOS 10.14.4 with a new install on Docker, following the README.  I tried seed-via-docker.sh using the sample triffo.yaml as described in the README. 

Here's triffo.yaml:

    $ cat triffo.yaml
    id: triffo
    title: Triffid Behavior ontology 
    github_org: cmungall
    repo: triffo
    import_group:
      products:
        - id: ro
        - id: bfo
        - id: pato

Here's the error from the script:

    $ ./seed-via-docker.sh -C triffo.yaml
    /tools/odk.py:445: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
      obj = yaml.load(config_file)
    Traceback (most recent call last):
      File "/tools/odk.py", line 679, in <module>
        cli()
      File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
        return self.main(*args, **kwargs)
      File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
        rv = self.invoke(ctx)
      File "/usr/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
        return callback(*args, **kwargs)
      File "/tools/odk.py", line 635, in seed
        save_project_yaml(project, tgt_project_file)
      File "/tools/odk.py", line 470, in save_project_yaml
        with open(path, "w") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'target/triffo/project.yaml'

Looks like the script wants target directories and files created before it is run?  Which ones? Or perhaps there is a permission problem and Docker was unable to create the directories and files needed? I have Docker Desktop for Mac installed.  Do I need Docker Toolbox?  I created the requested file and a subsequent run was able to replace its's contents, but then failed on other missing directories (src/ontology).

Suggestions?

**Comment by matentzn** [comment]
I think the problem is that the place your script is located must be known to docker. Can you try adding the location using docker preferences?

**Comment by mconlon17** [comment]
Okay.  /Users was mounted as a filesystem for Docker and Docker has file system permissions.  I removed /Users from the list of mounted filesystems for Docker and added the specific path for the directory I am running the script from.

That failed with docker looking for .gitignore in my home directory

I then set the export filesystem for Docker to my home directory, my script is two levels down, and that failed with the original reported error.

**Comment by matentzn** [comment]
Sorry, its a bit trial and error. But can you try to create a directory named ‘target’ in the same directory as your seed script and try again?

**Comment by matentzn** [comment]
(What always worked for me is cloning the odk from github and run the script from in there by the way, but that should not be necessary.)

**Comment by mconlon17** [comment]
That worked.  I cloned the repo and ran seed-via-docker.sh from the clone with my yaml file and got a nice repo.  See https://github.com/mconlon17/academic-degree-ontology

Thanks for the help!

**Comment by matentzn** [comment]
Ok, I think I fixed it now; if you do a docker pull to get the latest odk, and then just run the seed script from anywhere (outside the ODK directory), as long as the dir is known to docker, it should work.
