### ISSUE TITLE
/bin added to version control

### ISSUE THREAD

**Issue by pbuttigieg** [INCATools/ontology-development-kit#21]
When @kaiiam was [testing out the OSK](https://github.com/kaiiam/KaiO) and when we [ran it to create MESO](https://github.com/EnvironmentOntology/meso), the `/bin` directory was added to the versioning flow and owtools, robot, etc were committed and pushed.

Like `/mirror`, this should probably be ignored

**Comment by cmungall** [comment]
Can you check this? I think this has been resolved.

**Comment by matentzn** [comment]
Hey, closing this issue due to long inactivity. Please re-open if necessary.
