### ISSUE TITLE
OBO validator into ODK

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#214]
Transferring an email thread into a ticket.

OBO files are typically 'terminals' in our release chains - i.e. final release products. It is very common to **hack** OBO files into shape after they are produced by the OWL API based tools such as ROBOT or owltools. For example:

- owl-axioms are stripped out (all ODK ontologies). Example:
```
$(ONT)-base.obo: $(ONT)-base.owl
	$(ROBOT) convert --input $< --check false -f obo $(OBO_FORMAT_OPTIONS) -o $@.tmp.obo && grep -v ^owl-axioms $@.tmp.obo > $@ && rm $@.tmp.obo
```
- date annotations are added manually (Disease Ontology):

```
annotate --version-iri "$(OBO)doid/releases/$(DATE)/$(notdir $@)"\
	 --output $(basename $@)-temp.obo && \
	grep -v ^owl-axioms $(basename $@)-temp.obo | \
	grep -v ^date | \
	perl -lpe 'print "date: $(TS)" if $$. == 3'  > $@ && \
	rm $(basename $@)-temp.obo && echo "Created $@"
```

and many more.  Moreover, some interactions between ROBOT remove and specific annotation properties (such as subset and synonym) can cause problems as well. Since after serialisation, no tools are touch these files until ingest downstream, we dont catch when we accidentally break them; which causes annoyances in our stakeholders (MODs, canto, intermine, AGR ingest and more), which we should and can avoid. 

The preliminary cause of action is this:

1. Include the [FastOBO](https://github.com/althonos/fastobo/) validator into the ODK (@althonos + @matentzn)
2. Make sure that the FastOBO validation process catches the most common errors that are flagged up on ingest (date/xref formatting issues, missing annotation defs, missing ontology annotations etc)
3. Add another round of ROBOT qc on the FINAL (post-hacked) OBO artefact
4. We will share the additional QC with pipelines that are not using the latest ODK (@rctauber DO, ECO; GENO; SEPIO etc)

While we are working on this in the next weeks, @sbello has agreed to keep us updated:

Whenever an OBO ingest on the AGR side fails, add a comment here with the reason of failure, affected ontology and ideally the tool affected. Everyone else who has issues like that is of course invited to add their ingest failures to this issue as well! Much appreciated! @dosumis @cmungall @chris-grove

**Comment by althonos** [comment]
I made binary releases of a FastOBO CLI app built against musl (hence compatible with Alpine Linux or virtually any Linux distro or Docker container) on [Bintray](https://bintray.com/fastobo/fastobo-validator/x86_64-linux-musl). The latest stable release can be downloaded from [https://dl.bintray.com/fastobo/fastobo-validator/stable/:fastobo_validator-x86_64-linux-musl.tar.gz](https://dl.bintray.com/fastobo/fastobo-validator/stable/:fastobo_validator-x86_64-linux-musl.tar.gz).

I only implemented the syntax check (and ISBN static check) but I will add some more (like checking for mandatory and/or recommended OBO clauses, etc.).

**Comment by matentzn** [comment]
@althonos For me to quickly bake this into the odk, would you mind creating a PR installing fast obo here: 

https://github.com/INCATools/ontology-development-kit/blob/master/Dockerfile

and then post complete the following (fictional) goal for include it into the release pipeline:

```
x.obo: x.owl
  $(ROBOT) convert --check false -i $< -f obo -o $@.tmp.obo \ 
  && fastobo validate $@.tmp.obo \
  && mv $@.tmp.obo $@; 
```

**Comment by sierra-moxon** [comment]
thanks in advance! :) 

[java] 5531 - ERROR: Error while parsing Obo file
[java] Error: Badly formatted creation date: 2017-09-14T09:19:19
 
[java] 8994 - ERROR: Error while parsing Obo file
 [java] Error: Attempted to specify obsolete value obsolete drug:proton antiporter activity for consider tag.
 [java] on line: 117050
 [java] charnum: -1
 [java] line: consider: GO:0015307

Version: OntologyMetadata{name='eco', order=16, defaultNamespace='eco', oboVersion='null', dataVersion='null', date='September 8, 2017', savedBy='rctauber', generatedBy='null', remark='null'}
[java] Exception in thread "main" org.zfin.ontology.datatransfer.InvalidOBOFileException: Aborting load due to invalid OBO file. Report this as a bug to the ontology developer:
[java] Term with id Subset has no name attribute
[Term]
id: Subset
is_a: IAO:0000102 ! data about an ontology part
 
I think you can find issues on the DO tracker for those submitted by Alliance folks: Sue Bello or Yvonne Bradford.  

Definitely not trying to highlight specific ontologies or specific errors, but more broadly the issue of validation before distribution at the foundry (seems to be the goal here too -- awesome! :) ) ?   I think you might already know about a lot of the individual issues ? ie: []( https://github.com/orgs/fastobo/projects/2)

**Comment by matentzn** [comment]
@sierra-moxon 
This is great! Keep them coming. Thanks..

@althonos From eyeballing those, which ones does fast-obo actually NOT catch?

**Comment by sierra-moxon** [comment]
[java] Error: Attempted to specify obsolete value obsolete negative regulation of growth of symbiont in host for consider tag.
     [java] on line: 199542
     [java] charnum: -1
     [java] line: consider: GO:0044130

**Comment by dosumis** [comment]
I suspect this one is legal OBO (according to 1.4 spec).  It is definitely something we need a check for. Unfortunately it looks like this check is baked into the OBO -  OWL conversion - whereas it should probably be an ODK test.

**Comment by balhoff** [comment]
@dosumis the current OWL API OBO format code isn't bothered by those. It seems like the OBO-Edit parsing library.

**Comment by matentzn** [comment]
As an aside: is there a good place where we can document OBO-OWL conversion issues? @cmungall @balhoff ?

**Comment by balhoff** [comment]
I think the OBO format code has been absorbed into OWL API.

**Comment by balhoff** [comment]
Is there any way we can just provide some support for folks to move away from OBO format? I will happily provide guidance on reading the needed info using OWL API.

**Comment by matentzn** [comment]
I wish, but it wont happen quickly enough. The mods dont have the resources to switch at the moment; I think we should try to gently influence everyone to use OWL (I am), but while we are doing it at least document some of the discussions and decision we are making regarding OBO-OWL in order to not go back over it again and again..

**Comment by althonos** [comment]
@balhoff : as long as the Gene Ontology is developed in OBO, this won't happen, and you'll have some ontologies kept in that format.
@matentzn : if they are issues with the code, the [`owlapi`](https://drive.google.com/file/d/1U2jwsSZRndXNUCPU9PPBk3931dm9YYbm/view) repo, if they are semantic issue, [`oboformat`](https://github.com/owlcollab/oboformat/).

**Comment by matentzn** [comment]
Perfect, thanks @althonos

**Comment by sierra-moxon** [comment]
*Caused by: Error: Undefined category ro-eco.
on line: 992 of file:/opt/intermine/zebrafish/zeco/zeco.obo
charnum: 7
line: subset: ro-eco

**Comment by cmungall** [comment]
I think even if the OWL libraries in Python and R were mature (which they are unfortunately not), it would be a big ask to have bioinformaticians use an OWL-level library as it's a different level of abstraction than their use cases, e.g. relational graphs. Note we have provided OWL for GO and other ontologies for a while and you would not believe the kinds of mistakes people make when using these. Unfortunately most developers have not studied all of the relevant W3C documents and instead just code up things based on a bunch of half-baked assumptions.

it's more realistic to have people move towards a JSON format that supports relational graphs as first-class entities, e.g.

https://douroucouli.wordpress.com/2016/10/04/a-developer-friendly-json-exchange-format-for-ontologies/

There is not as much uptake as I'd like as it's easier for people to just keep using their hacked obo parser. But with the json being a standard odk output it will be easier for people to switch as their favorite ontology will be available in that format without having to do an additional conversion

ontobio natively supports obograph json. It does external conversion of obo or owl on the fly but will soon have native support thanks to fastobo.

**Comment by matentzn** [comment]
I think @sierra-moxon observation comes from [this issue](https://github.com/INCATools/ontology-development-kit/issues/261). 

I will fix this for Zeco, more in the other ticket.

**Comment by matentzn** [comment]
Thanks for the report @sierra-moxon
- ZECO should be fixed again. Please test and let me know!
- In response to the @cmungall suggestion: take a look at the amazing [OBO JSON](https://raw.githubusercontent.com/ybradford/zebrafish-experimental-conditions-ontology/master/zeco.json) we now offer for zeco! Using this will preclude many problems in the future (we hope to establish this as better supported alternative to the OBO format)

**Comment by sierra-moxon** [comment]
Hooray for an OBOJSON file!! :D  I just noticed this for GO and was chatting with @ktlm about the GO OBO JSON file.  This is great!!

**Comment by matentzn** [comment]
Ping me your wish list if ontologies for which you want Jason whenever you feel like it!

**Comment by matentzn** [comment]
I would rather have everyone use ODK and generate standard relrelease artefacts including Jain by default.. I have moved about 20 over now; and I am happy to slowly continue.

**Comment by sierra-moxon** [comment]
Awesome!! :) 
Here's the list that we use (a combo of ontologies in use at Alliance and ZFIN): GO, SO, DOID, MI, ZFA, ZFS, WBBT, CL, FBBT, FBCV, MMUSDV, BSPO, MMO, WBLS, EMAPA, MA, ECO, UBERON, ECOMAP, PATO, MPATH, CHEBI, UBERON  (basic.obo), ZECO.

**Comment by sierra-moxon** [comment]
Also, is this the JSON schema for OBO JSON? https://github.com/geneontology/obographs/blob/master/schema/subschemas/obographs-graph-schema.json

**Comment by cmungall** [comment]
Yep, that's it

**Comment by sierra-moxon** [comment]
@matentzn - taking a look at the JSON for zeco - I remember reading about URIs and IDs etc... awhile back, but can you give me the short primer on why we don't list the ZECO id in this kind of format in the JSON spec?  ZECO:0000126 
I'd like to move away as much as possible from parsing out substrings -- is this what ontobio does?

**Comment by althonos** [comment]
@sierra-moxon `ZECO:0000126` is only a shortcut notation for `http://purl.obolibrary.org/obo/ZECO_0000126` which is the actual id! 

Depending on the translation tool, you may be able to retrieve the compact identifier using the `oboInOwl:shorthand` annotation property!

**Comment by sierra-moxon** [comment]
@althonos - ok, so in a perfect world of ID-maintenance, it is prefered that data in actual data stores, were keyed off of that long-form id?  

In the JSON for ZECO provided above, I can't find a key for either 'oboInOwl' nor 'shorthand' -- in the interest of moving us off of obo, changing IDs to the long form might be a bit of a blocker.

**Comment by sierra-moxon** [comment]
Basically I'm asking for that the JSON provide both the IRI and the short-form ID in the file itself.

**Comment by matentzn** [comment]
@sierra-moxon to answer your question to @althonos: YES. 100% you should be using the long IRIs and not the short form. There is no canonical representation for any CURIE style id outside the OBO world; you will find ORPHA:001, orphaNet:001, and many other notations, and this is an unnecessary risk for applications relying on linking across resources reliably! 

The obo:shorthand tag has its own problems, I personally would prefer that ontologies maintain their own OBO IDs as annotation properties, which some ontologies like MP and HP do in a very incompletele manner. I believe one of the purposes of obojson is to finally rid ourselves of this curies! So I would rather doubt you will have your wish fulfilled and get the curies in there. But if you want to try, make a ticket [here](https://github.com/geneontology/obographs/). Sorry I can't be more helpful on this matter; but I have a somewhat religious believe that OBO curies like ZECO:001 cause is to lose a lot of interesting connections between resources, and hamper interoperability and standardisation.

**Comment by cmungall** [comment]
While Nico is correct, we have to be pragmatic, bioinformaticians generally don't use the semantic web stack. The community that Sierra and others have to serve expect short identifiers.

> There is no canonical representation for any CURIE style id outside the OBO world; you will find ORPHA:001, orphaNet:001, and many other notations

This is true, but with the exception of OBO we also lack standard permanent URIs too. We are actually much closer to having standard CURIE-form prefixed identifiers than we are having standard URIs for genes, genomic and entities, thanks to efforts such as https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml (now adopted by the Alliance). 

In contrast look at our best-effort attempt to standardize URIs [in dipper](https://github.com/monarch-initiative/dipper/blob/cff0d01299e982183a5345b8a7eb00094ed05257/dipper/curie_map.yaml) - 19 cases of `cgi` in the URI!!! These are unstable web URLs for humans to look at web pages, not PURLs suitable use as an identifier!!! 

Having said all that, I think that obograph json should follow json-ld and allow an explicit context that unambiguously maps CURIEs to URLs.

**Comment by matentzn** [comment]
Wohoo. :P I didnt know that! I was kind of naive I guess about IRIs.. :) 

> Having said all that, I think that obograph json should follow json-ld and allow an explicit context that unambiguously maps CURIEs to URLs.

This would be a good compromise! I also hear your "bioinformaticians dont use" argument. Hopefully one nice day in the future...

**Comment by dosumis** [comment]
identifiers.org ?

**Comment by cmungall** [comment]
We use this for gene IDs in GO, as they are guaranteed to be stable (no
cgi, .pl, etc). Although there is no guarantee that later on there won't be
something that takes precedence. There is still the question of what the
semantics of the identifiers.org URL is. But I think it would improve the
Monarch prefixes immensely by replacing the genes with id.org
cc @TomConlin.

**Comment by matentzn** [comment]
This has become a huge ticket, but the original request, to enable to run fastobo-validation using the odk, has been fulfilled:

```
sh run.sh fastobo-validator wbphenotype.obo
```

I will close the issue for now, so unfortunately, open questions will have to be put into a new issues.

**Comment by cmungall** [comment]
https://github.com/fastobo/fastobo-validator/releases/download/v0.4.0/fastobo_validator-x86_64-linux-musl.tar.gz

**Comment by cmungall** [comment]
@althonos 

```
 => ERROR [10/24] RUN wget https://dl.bintray.com/fastobo/fastobo-validator/v0.4.0/fastobo_validator-x86_64-linux-musl.tar.gz -O- | tar xzC /tools && chmod +x /tools/fastobo-validator                    0.7s
------                                                                                                                                                                                                          
 > [10/24] RUN wget https://dl.bintray.com/fastobo/fastobo-validator/v0.4.0/fastobo_validator-x86_64-linux-musl.tar.gz -O- | tar xzC /tools && chmod +x /tools/fastobo-validator:                               
#15 0.548 --2021-05-17 22:10:25--  https://dl.bintray.com/fastobo/fastobo-validator/v0.4.0/fastobo_validator-x86_64-linux-musl.tar.gz                                                                           
#15 0.555 Resolving dl.bintray.com (dl.bintray.com)... 34.218.153.129, 52.41.30.229, 34.223.170.36, ...                                                                                                         
#15 0.570 Connecting to dl.bintray.com (dl.bintray.com)|34.218.153.129|:443... connected.
#15 0.665 HTTP request sent, awaiting response... 403 Forbidden
#15 0.688 2021-05-17 22:10:25 ERROR 403: Forbidden.
#15 0.688 
#15 0.689 
#15 0.689 gzip: stdin: unexpected end of file
#15 0.690 tar: Child returned status 1
#15 0.691 tar: Error is not recoverable: exiting now
------
executor failed running [/bin/sh -c wget https://dl.bintray.com/fastobo/fastobo-validator/$FASTOBO_VALIDATOR/fastobo_validator-x86_64-linux-musl.tar.gz -O- | tar xzC /tools && chmod +x /tools/fastobo-validator]: exit code: 2
make: *** [docker-build] Error 1
```

looks like it has gone from bintray?

```bash
$ wget https://dl.bintray.com/fastobo/fastobo-validator/stable/:fastobo_validator-x86_64-linux-musl.tar.gz
--2021-05-17 15:13:55--  https://dl.bintray.com/fastobo/fastobo-validator/stable/:fastobo_validator-x86_64-linux-musl.tar.gz
Resolving dl.bintray.com (dl.bintray.com)... 35.161.90.47, 52.43.227.140, 34.215.99.236, ...
Connecting to dl.bintray.com (dl.bintray.com)|35.161.90.47|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-05-17 15:13:55 ERROR 403: Forbidden.
```

**Comment by cmungall** [comment]
Looks like grabbing:
https://github.com/fastobo/fastobo-validator/releases/download/v0.4.0/fastobo_validator-x86_64-linux-musl.tar.gz

works fine? any reason not to do this @matentzn @althonos ?

**Comment by cmungall** [comment]
oh it looks like I need to rebase this has been fixed

**Comment by balhoff** [comment]
Bintray shut down: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by althonos** [comment]
Exactly, @cmungall @balhoff Bintray closed down so I'll put the binaries on the GitHub release page from now on :+1:
