### ISSUE TITLE
Bundle all tooling using docker

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-development-kit#22]
This isn't very scalable

https://github.com/INCATools/ontology-starter-kit/blob/master/.travis.yml#L8-L13

Used all over, with variations:

https://github.com/geneontology/go-ontology/blob/master/.travis.yml#L14-L22

Would it make sense to have a Dockerfile that provided an environment that included

 * owltools
 * robot cc @jamesaoverton
 * dosdp-tools cc @balhoff 
 * dosdp python checkers cc @dosumis
 * anything else we add to the chain, e.g. blazegraph loader

This would primarily be for running validating checks on an ontology repo (including reasoner checks, sparql checks, pattern checks) in travis, but may be useful in other contexts

cc @kltm

**Comment by kltm** [comment]
For the GO, our ideal is to have a runtime environment with most of the tools as part of a release as a Dockerfile, made available for (*nix-y) people who want to use the environment without all the setup. If done correctly, this can simplify things. It can also become yet another distribution to be maintained as the typical root-oriented environment of Docker may work slightly differently than user environments of some of the user base.

**Comment by cmungall** [comment]
Some progress on this

There is a Dockerfile for ROBOT: https://github.com/ontodev/robot/pull/148

In this repo we have a branch with Docker experiments
https://github.com/INCATools/ontology-starter-kit/blob/docker/docker/Dockerfile

Need to test this with OSK

**Comment by cmungall** [comment]
A Dockerfile that will fire up an OLS instance for your local ontology:
https://github.com/HumanCellAtlas/ontology

"We’ve found this useful for evaluating ontologies we are developing with users, especially for quickly getting them hosted on an EC2 instance.  Also useful for viewing partonomies. I thought this might be something to add to the ontology starter kit, there is zero config required, you just need the name of the ontology and some optional metadata fields in the /ols directory, which is basically the OBO yaml format anyway. You can see an example in the human cell atlas ontology we are developing"

From @simonjupp

v cool, thanks!

**Comment by dosumis** [comment]
Python script to check patterns against schema is here:

https://github.com/dosumis/dead_simple_owl_design_patterns/blob/master/src/simple_pattern_tester.py

Is it worth putting something so small into a container?

**Comment by cmungall** [comment]
not into its own container, but it can go into the https://hub.docker.com/r/obolibrary/osk/ container, so it's a one stop shop

**Comment by cmungall** [comment]
simple_pattern_tester.py is now included in oskfull

**Comment by cmungall** [comment]
Doing some tests on triffid ontology

Using the old-school .travis.yml (where each component was wgetted):
https://travis-ci.org/cmungall/triffid-behavior-ontology/builds/274895935

takes 6-7 mins to grab everything:

![image](https://user-images.githubusercontent.com/50745/43050517-d961d806-8dbe-11e8-84c4-4e1dc86df4cf.png)

Using docker:
https://travis-ci.org/cmungall/triffid-behavior-ontology/builds/406928013

takes 1m, nice!

![image](https://user-images.githubusercontent.com/50745/43050572-371e77a0-8dc0-11e8-9dc3-1914397e4ac0.png)

**Comment by matentzn** [comment]
Hey, closing this issue due to long inactivity. Please re-open if necessary.
