### ISSUE TITLE
Critical: Increasing numbers of 503 errors during ODK ontology builds

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#222]
We are getting an increasing number of 503 errors when resolving imports that are located on GitHub. I have no clue how to debug this: But of the 14 HPO travis builds in the last 4 days that failed, 5 (!!) [failed because of that error](https://travis-ci.org/obophenotype/human-phenotype-ontology/builds), for example [this one](https://travis-ci.org/obophenotype/human-phenotype-ontology/builds/536598042). The "phenotype" of the problem is always robot loading an ODK edit file (hp-edit.owl), and then throwing an UnloadableImportException. This is what we know:

1. For these 5 HP build failures related to this error in the last 4 days, the culprit imports were: once uberon, twice GO, twice chebi; so seems they are the bigger ones. Example
```
robot report -i hp-edit.owl --profile qc-profile.txt --fail-on none -o hp_report
org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <http://purl.obolibrary.org/obo/hp/imports/go_import.owl> Cause: Server returned HTTP response code: [503](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503) for URL: https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/master/imports/go_import.owl
```
What I find particularly stunningly weird here is that the imports resolution should be local in this case (there is a catalog.xml file!).
2. It did not happen only in ROBOT (and not consistently there either on the same command), it happened also in owltools during some other things I tried to do (outside of Travis!). So level seems OWL API.
3. Running the same exact build right after each other can result in one successful and one bad run.
4. The frequency increased drastically in the last weeks. The only commit I performed that could be in any way relevant (I cant see how though) is the one where I added openssl](https://github.com/INCATools/ontology-development-kit/commit/478fed6fe8fb60fd7a9b3ff373692df6f0c00e3d) to the alpine image.

Thats it. I would really apprectiate some help on this.

**Comment by dosumis** [comment]
Have you tried a simple test of GitHub reliability, e.g. python script running periodic `requests.get` against file & recording http response?

**Comment by jamesaoverton** [comment]
Are you sure that the catalog you want is being used? In https://github.com/obophenotype/human-phenotype-ontology/tree/master/src/ontology I see a `default-catalog.xml`. ROBOT will automatically detect a catalog file matching `catalog-v001.xml` when it's in the same directory as the input file. But ROBOT doesn't scan the whole directory for catalogs. To the best of my knowledge, ROBOT behaves the same as Protege in this respect. I can't find any other ontologies on GitHub that use a `default-catalog.xml`.

However ROBOT lets you specify a catalog file with the `--catalog <file>` option: http://robot.obolibrary.org/global#xml-catalogs

**Comment by matentzn** [comment]
Thanks all! @jamesaoverton you were right (big thanks)! HP build was ignoring the catalog; we never noticed because there were local copies of the file available on our machines (and .gitignored). But still, even if the imports were resolved through URLs rather than local, the overall problem persists.

I will keep an eye on breaking pipelines and paste them here. In the meantime, I would still like to know what could be the cause of this; I mean, having github just giving 503s under load seems a bit unbelievable, so I still want to think it has something to do with the ODK.. 

@dosumis now, but I have submitted about 40 jobs in 3 weeks that all showed occasional signs of this.. Maybe a more systematic script monitoring the behavior will be necessary. For at all, just let me know when pipelines fail elsewhere with 503s.

**Comment by matentzn** [comment]
@drseb observed the same behaviour (503s) trying to directly wget http://purl.obolibrary.org/obo/hp/imports/chebi_import.owl outside of the ODK; and I think I did as well.

**Comment by kltm** [comment]
@matentzn While not directly related, we often have pipeline trouble with GH-delivered files, sometimes causing pipeline runs to go bad after many many hours. To bring out one of my hobby horses, GH in not really a very good file delivery system in our experience. It may be good to start looking at a better backplane for this infrastructure.

**Comment by balhoff** [comment]
Related?

https://www.githubstatus.com/incidents/kv978bsgr4kb

**Comment by cmungall** [comment]
It's not insane that an ssl library could be somehow implicated.

It sounds like we have some wiggle room in that it shouldn't need the
external OWL if you add the catalog. In fact an ontology make test job
should not have any network dependencies, we want tests to be repeatable,
and any network connection introduces nondeterminism (even when the network
is working I bet you sometimes got weird bugs from the downloaded OWL being
different from the local import on the branch).

But Seth's point still stands, we are using GH as a file delivery mechanism
which may not be the best use of it. However, it is free, free to
administer, and administration scales to N autonomous independent ontology
groups. We can explore using S3 for key ontologies if we still encounter
issues.

**Comment by matentzn** [comment]
Didnt happen again so closing for now
