### ISSUE TITLE
Running docker as user make it easier to use as a user on unix

### ISSUE THREAD

**Issue by bjonnh** [INCATools/ontology-development-kit#225]
Using something like:
```
FROM obolibrary/odkfull
ENV UID 1000
RUN addgroup -S appgroup && adduser -S appuser -G appgroup -u $UID

USER appuser
```

one can run:
docker build --build-arg UID=${UID} -t bjonnh/odkfull .
docker run --rm -v ${HOME}/.gitconfig:/home/appuser/.gitconfig:ro -v ${PWD}:/work -w /work --rm -ti bjonnh/odkfull /tools/odk.py seed "$@"    # similar to the seed script provided, just added :ro and changed the container name

The advantages of this approach:
- Tasks don't run as root
- gitconfig is not writable in the container
- Rights are set to the current user UIDs

**Comment by matentzn** [comment]
Thanks @bjonnh 
As this seems to be a nice suggestion for some of the more technical users, maybe this should make its way into the future documentation of the ODK. However, I would really like advantage 2 and 3 to be somehow incorporated into the main ODK; If you have an idea to do that which does not require the user to actually built to odk.. Let me know.

**Comment by gouttegd** [comment]
Since ODK 1.5, processes within the ODK container are run under a non-privileged account by default.
