### ISSUE TITLE
Always use an explicit --catalog option when using robot

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-development-kit#226]
https://github.com/ontodev/robot/issues/493

In theory this will make no difference as with a standard layout the only time the `-i` points to a subdir is for things in `imports` or `mirror` when we don't require the catalog. But still, being explicit will limit possibilities of future hard to track bugs

**Comment by matentzn** [comment]
All ROBOT calls in Makfile should be amended like:
```
$(ONT)-non-classified.owl: $(SRC) $(OTHER_SRC)
	$(ROBOT) merge --catalog $(CATALOG) --input $< \
		annotate --ontology-iri $(ONTBASE)/$@ --version-iri $(ONTBASE)/releases/$(TODAY)/$@ --output $@.tmp.owl && mv $@.tmp.owl $@
```
and $(CATALOG) configurable by the project config yaml?

**Comment by matentzn** [comment]
Fixed by https://github.com/INCATools/ontology-development-kit/pull/246
