### ISSUE TITLE
Should we remove owl:Nothing by default from all the release artefacts?

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#228]
Currently, we have many ontologies that are released with sad, isolated owl:Nothing references in the top level of the ontology. I am inclined to do a hard remove owl:Nothing on any owl release artefacts, but I understand some people are using it in their modelling for QC. What are the views? Yet another 'configurable' option?

**Comment by balhoff** [comment]
It's only showing up when it's been specifically referenced, right? Sometimes (or maybe always) this comes from a disjointness pattern in Uberon. I think @cmungall said there was some workflow issue which prevents updating these axioms to just be DisjointClasses.

**Comment by matentzn** [comment]
Thanks @balhoff probably you are right; so lets say that is the case; what would be your inclination? retain or drop? its just a nuissance to see this class being used in releases of ontologies; IMHO, it should not be used for modelling at all, but there are some reasons, so I am not sure i want to open pandoras box and get UBERON to remove all those axioms..

**Comment by balhoff** [comment]
I think we should peek in Pandora's box. :-)
