### ISSUE TITLE
How to handle duplicate names in OBO files?

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#230]
Currently, if we have duplicate labels in owl, and convert to OBO, we get two name tags in our OBO files. The serialiser seems to allow this; the parser not. I have dealt with this recently by running a perl post-process that randomly deletes one of the name tags;

```
x.obo: y.obo
	cat $< | perl -0777 -e '$$_ = <>; s/name[:].*?\nname[:]/name:/g; print' | perl -0777 -e '$$_ = <>; s/def[:].*?\ndef[:]/def:/g; print' > $@
```

That is ugly, and incomplete (think three name tags). Is there a way to force the obo file into compliance with a fast-obo command? If not, do you have any other idea how I can make sure that if I save ab OBO file, I can actually load it again without a parse error?

 @althonos @cmungall

**Comment by althonos** [comment]
I'm in the process of adding that validation step to the validator CLI: this way you'll be able to check if clauses have the right cardinality. 

I'm not sure if there is a point in writing a script or program that would merge them, since there is ambiguity in how to do that: only take the first name ? merge the three names in the same clause ? etc.

**Comment by matentzn** [comment]
From a formal standpoint I agree with you; but it seems so annoying that our serialisers spit out OBO they cant parse again; so I would favour a bit of non-determinism plus some warnings here to create a workable solution, at least in the context of the ODK.. The parser should just fail to write.

**Comment by matentzn** [comment]
Actually no: The default solution should be to push one of the double names (non-deterministically) into the owl-axioms section!

**Comment by balhoff** [comment]
> Actually no: The default solution should be to push one of the double names (non-deterministically) into the owl-axioms section!

Deterministically would be even better! Like keep the lowest alphabetically for `name`.

**Comment by balhoff** [comment]
Pushing into owl-axioms is a great idea! We're having this problem now when folks try to save go-plus as OBO and then re-parse it.

**Comment by matentzn** [comment]
@cmungall Where should this ticket go? OWL API?

**Comment by matentzn** [comment]
moved to https://github.com/owlcs/owlapi/issues/861
