### ISSUE TITLE
ROBOT report fails on MICRO

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-development-kit#231]
May be related to: https://github.com/carrineblank/MicrO/issues/22

```
$ robot report -vvvv -i /tmp/micro.owl -o micro.rpt
...
2019-06-23 19:15:56,594 ERROR org.apache.jena.riot - [line: 1266, col: 60] Unrecognized keyword: has
[line: 1266, col: 60] Unrecognized keyword: has
Use the -vvv option to show the stack trace.
Use the --help option to see usage information.
```

Something to do with the bridging from OWLAPI into Jena, possibly caused by weirdnesses in the micro.owl file

**Comment by jamesaoverton** [comment]
ROBOT `report` uses SPARQL. The first step is to serialize the input ontology as Turtle and load it into Jena. So I ran `robot convert -i micro.owl -o micro.ttl` and looked at `micro.ttl` line 1266: `rdfs:label has sodium chloride percentage of .` (with no quotes). That's deeply weird. It looks like another instance of https://github.com/carrineblank/MicrO/issues/22, and fixing that should fix this. On the other hand, OWLAPI should not be spitting out Turtle like this.

**Comment by rctauber** [comment]
In addition to the one that Chris pointed out, both 'has sodium chloride percentage of' (`MICRO:00001211`) and 'has pH value' (`MICRO:0001603`) labels have datatype `xsd:decimal`. All other labels have `xml:lang="en"`. I fixed the labels and ran `robot convert` and we get valid Turtle for this:

```
###  http://purl.obolibrary.org/obo/MICRO_0001179
<http://purl.obolibrary.org/obo/MICRO_0001179> rdf:type owl:DatatypeProperty ;
                                               rdfs:label "has cell width"@en .
```

'R2A agar' (`MICRO:0000543`), 'R2A medium' (`MICRO:0000541`), 'anaerobe basal agar' (`MICRO:0001571`), and 'DSMZ Medium 77' (`MICRO:0001781`) all have a property (`IAO:0000119`) with `xml:lang="25 °c ..."`. It looks like these were meant to be other annotations. I changed these to `xml:lang="en"` and ran `report` again and it completes:
```
$ robot report --input micro.owl --output report.tsv
Violations: 8350
-----------------
ERROR:      105
WARN:       3760
INFO:       4485
```

**Comment by matentzn** [comment]
I will close this issue here, please feel free to open again!
