### ISSUE TITLE
add date annotation to the release artefacts

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#256]
Is there a way I can do it in with ROBOT, no matter how hacky?

@jamesoverton 

Basically I would like what appears in OBO as 
```
date: 2019-01-11
```

To appear in all the (OBO) release artefacts, not just embedded in the version IRI..

**Comment by jamesaoverton** [comment]
Is this bit of the OBI Makefile what you want?

https://github.com/obi-ontology/obi/blob/master/Makefile#L114

**Comment by matentzn** [comment]
That’s is exactly perfect! Thanks!

@cmungall @jamesaoverton @dosumis I will make it an option to add the date to all release artefacts! If I don’t hear you scream, I will make the default NO DATE to not break with the existing way of doing things. Let me know if you want the default to be dated!

**Comment by balhoff** [comment]
I tested the OBI approach and the date didn't go into the `date` field. It came out like this instead:

`property_value: owl:versionInfo "2019-07-24" xsd:string`

There was a request for this in BSPO: https://github.com/obophenotype/biological-spatial-ontology/issues/15

**Comment by balhoff** [comment]
Okay, I did this:

OBODATE=$(shell date +'%d:%m:%Y %H:%M')

`robot annotate -i $< --ontology-iri $(PREFIX)/$(ONT)-base.owl --version-iri $(RELEASEPREFIX)/$(ONT)-base.owl --annotation oboInOwl:date "$(OBODATE)" -o $@`

**Comment by matentzn** [comment]
Thx Jim. Perfect

**Comment by matentzn** [comment]
Works perfect now!
