### ISSUE TITLE
Vote: OBO release artefact ontology: tag

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#259]
Please vote on the following once and for all (we have done it 10 times so far, but never quite finished the discussion):

In the OBO format, for any specific release file such as fbcv-base.owl, should the ontology tag say

Option 1
```
ontology: fbcv
```

So that when the OBO file is loaded, subset iris resolve correctly to 
http://purl.obolibrary.org/obo/fbcv#subset_x

or shall we say 

Option 2:
```
ontology: fbcv/fbcv-base
```

which is the result of the OWL2OBO converter, requires no hacking, but will cause subset iris to link to:

http://purl.obolibrary.org/obo/fbcv/fbcv-base#subset_x

(i.e. downstream tools cannot recognise that they were the originally referring to the same subset)

Use the thumbs up for OPTION 1 and thumbs down for OPTION 2.

**Comment by matentzn** [comment]
Note that of course, option 2 can be combined with a fix to the OBO format converter, but that is not the issue now; this is purely the question of what ODK should do.

**Comment by balhoff** [comment]
I don't think I totally understand. I don't think we should publish OBO format base ontologies. Or does this question apply also to simplified artifacts like `$ONT-basic.obo`?

**Comment by matentzn** [comment]
Yeah yeah, sorry. I meant simple, basic and asserted; everything that is not the main release.

**Comment by balhoff** [comment]
The `ontology` issue only comes up if someone loads one of these files as OWL, right? And you would like the ontology IRI to resolve to the "same" ontology they are looking at?

In reality wouldn't anyone using one of these files NOT use OWL? So they would use some other OBO parser and not care about the translation back to OWL.

**Comment by matentzn** [comment]
Yeah, any tool based on OWL API will do that.

I generally agree with that; but the confusion cometh when pipelines actually have some intermediate OBO (think obo edit files, think some very specific hack me into shape scripts that delete rows etc from obo files). 

As you can see, we have hit one of the few points where David and I actually disagree. I am more of an idealist saying: since it is broken, OBO files should simply not be used in an OWL-API context. I also like the ontology iri to say fbcv-basic if it is the basic file. David is more pragmatic. He says "OBO files are used, and will continue to be used, in all sorts of intermediate steps of pipelines (even those involving OWLAPI)". Which is, of course, true; so he wants the id to be that of the original ontology (the source of the simple version if you will), to not mess up the default (like subset) IRIs. Both positions are equally valid in my opinion. My main argument is to just leave things as they are and avoid extra work (with new, unknown consequences) and not bother too much. David is probably are bit more "right", if pipeline resilience is the goal.
