### ISSUE TITLE
Add option to include default gitattributes for using git-owl-tools

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-development-kit#26]

**Comment by matentzn** [comment]
Can we get some details please?

**Comment by cmungall** [comment]
@ShahimEssaid can't seem to find your repo any more

**Comment by ShahimEssaid** [comment]
@cmungall I made it public again. I had too many partially developed repositories and most of them weren't that usable anyway. I became a paid member and made everything private to see if anyone notices :)  You are the first!

**Comment by matentzn** [comment]
Closing as not actionable.
