### ISSUE TITLE
Inject metadata to header of ontology

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-development-kit#296]
See also #67 

Similar ticket for robot https://github.com/ontodev/robot/issues/6 - however, robot will not always have full information, only the wrapping call knows

E.g. %-base.owl should be stamped with http://purl.obolibrary.org/obo/IAO_8000001

I suggest *not* using rdf:type. Something like dc:type?

**Comment by wdduncan** [comment]
Yes. This would be an annotation on the ontology. Do we also want to annotate each class in the ontology as being a base class?

**Comment by wdduncan** [comment]
@cmungall I have modified my local repo include annotation in base ontology.  
Can you give me permission to push now branch?

**Comment by matentzn** [comment]
@wdduncan what happened with this ticket? Forgot about it!

**Comment by matentzn** [comment]
Just saw this was merged long ago. closing (use #67 for further requests).

**Comment by wdduncan** [comment]
Thanks for closing.
