### ISSUE TITLE
Why is license URL represented as a string in examples?

### ISSUE THREAD

**Issue by jamesaoverton** [INCATools/ontology-development-kit#308]
Looking at <https://github.com/INCATools/ontology-development-kit/blob/master/docs/License.md> I can't understand why the CC-BY 3 URL for the `terms:license` is always represented as an `xsd:string` instead of a URL. I worry that I'm missing something.

**Comment by matentzn** [comment]
You are totally right, should be either just a resource as @beckyjackson did with DO (I changed the [license example page](https://github.com/INCATools/ontology-development-kit/blob/master/docs/License.md) to that now) or xsd:anyUri. Has this ever been decided - maybe should be added to docs if so.

**Comment by jamesaoverton** [comment]
Decided by whom, and added to which docs? It just seems like common sense to me. That's why I'm worried that I'm missing something.

**Comment by matentzn** [comment]
Oh I meant the obo foundry's docs, and actually, its already been documented there pretty clearly in the examples section:

http://obofoundry.org/principles/fp-001-open.html

You have not missed anything :P Just me! OBOFoundry Docs evolving fast at the moment!
