### ISSUE TITLE
travis test for this repo is fake

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-development-kit#313]
The .travis.yml for odk (i.e the one in the top level, NOT the templated one) does not actually test the code in the repo. It tests the docker container on dockerhub.

It seems it has always been this way...?

**Comment by matentzn** [comment]
Yes, we had discussed this before.. I basically run all tests locally before merging a branch into master or making a release. I agree we should fix this;

**Comment by matentzn** [comment]
This is now fixed by: https://github.com/INCATools/ontology-development-kit/blob/0dd8ddbc48281535c31de379d187881e36c59609/.travis.yml#L10
