### ISSUE TITLE
Create a Jupyter environment for running releases

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-development-kit#33]
After an ontology developer creates a repo using OSK, they typically do things now via the command line to trigger make builds, usually `make all`.

There may be some value in allowing a release to be executed via a local Jupyter notebook. This would allow the release manager to interactively explore intermediate reports that are generated as part of the release. These could easily be visualized.

This would work by having a lightweight python library that wraps makefile commands (or maybe switching to snakemake would work here).

An additional possibility is to do this via mybinder.org, obviating the need for the release manager to install robot, owltools, etc. The main challenge here would be authorization to make the push to GH.

**Comment by matentzn** [comment]
This issue has not seen much activity, and I am doubtful how useful it would be. Please reopen if you feel different!
