### ISSUE TITLE
In Dockerfile, remove dependencies on old jenkins

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-development-kit#332]
https://github.com/INCATools/ontology-development-kit/blob/0dd8ddbc48281535c31de379d187881e36c59609/Dockerfile#L37

old Jenkins down. This was never a good idea anyway. There are multiple other sane things we can do instead:

 - add the jar/owltools cli to owltools releases on GH
 - release on mvncentral https://github.com/owlcollab/owltools/pull/175
 - build on a different jenkins
 - build as part of docker build (no longer a prob now we are no longer alpine)
 - any number of other things

note: since old jenkins down many old travisses will fail since they directly grabbed owltools and robot from there... but this is good, will force a switch to odk!

cc @kltm @matentzn

**Comment by kltm** [comment]
Okay, this is a hack, but we actually publish all the software that we use in the pipeline at the moment. E.g.: http://release.geneontology.org/2020-03-25/bin/ .
That can be used as an immediate drop-in to prevent failure until a better pick-up point is made.

**Comment by matentzn** [comment]
I would prefer `add the jar/owltools cli to owltools releases on GH` and will do that before the next ODK release..

**Comment by dougli1sqrd** [comment]
I made a new owltools release here: https://github.com/owlcollab/owltools/releases/tag/2020-04-06

**Comment by matentzn** [comment]
This release is missing a bunch of jar files I am used to from the old Jenkins: https://github.com/INCATools/ontology-development-kit/blob/0cd1a1e2e613e4658f4fb40611295f9ce81d321c/Dockerfile#L37

Can we somehow add them as part of the release?

**Comment by matentzn** [comment]
http://build.berkeleybop.org/userContent/owltools/owltools http://build.berkeleybop.org/userContent/owltools/ontology-release-runner
http://build.berkeleybop.org/userContent/owltools/owltools-oort-all.jar

Were previously available.. :) sorry

**Comment by cmungall** [comment]
@dougli1sqrd can you add these? Thanks!

**Comment by balhoff** [comment]
Oops, sorry I already did this. Commented on two other tickets but missed this one.

**Comment by matentzn** [comment]
Done. https://github.com/INCATools/ontology-development-kit/pull/334
