### ISSUE TITLE
Lack of order in all_pattern_terms.txt causes excessive diffs

### ISSUE THREAD

**Issue by jseager7** [INCATools/ontology-development-kit#337]
I've noticed that `src\patterns\all_pattern_terms.txt` doesn't seem to enforce any sorting on the terms it contains, except maybe for the source ontology. That means that you get a huge amount of diffs on every release due to the lines being reordered (example below). This makes it difficult to tell at a glance which external terms have been added. Other files, like `src\patterns\ontologyterms.txt`, don't have this problem.

I presume this file is meant to be versioned in the first place: if so, could some form of sorting be added during the release process so the diffs are more readable?

- - -

![all_term_diff](https://user-images.githubusercontent.com/37659591/80470580-20d28f00-893a-11ea-866a-682ea569fdd5.png)

**Comment by matentzn** [comment]
Thanks @jseager7 

In the new ODK (1.2.22), I have added many more files to .gitignore, including this one.

https://github.com/INCATools/ontology-development-kit/blob/master/template/.gitignore.jinja2

I would recommend to just through all these files in your own git ignore, git rm them all and that's it!
