### ISSUE TITLE
Ontologies should be stamped with versionInfo

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-development-kit#338]
See https://github.com/ncbo/bioportal-project/issues/168

**Comment by jonquet** [comment]
I would complement the issue by: 
- ontologies version information should be stamped with the  owl:versionInfo property
- ontologies version IRI or URI should be stamped with the owl:versionIRI property 

The first property can be used to describe the version with a string e.g., "3.0 (beta)" and the second is an IRI.

**Comment by matentzn** [comment]
@jonquet Not sure I exactly understand what you are suggesting; can you provide an example? You mean an annotation assertion on an annotation assertion?

**Comment by jonquet** [comment]
I was suggesting to use 2 properties one to descrive versionIRI and the other one to describe version. 
For instance: 
`
<http://purl.myorganization.org/myonto> 
	rdf:type 			owl:Ontology ;
	dct:title 			"My super cool ontology"@en;
	owl:ontologyIRI	http://purl.myorganization.org/myonto ;
	owl:versionIRI 		http://purl.myorganization.org/myonto-v2.3/
	dct:identifier		http://doi.org/anexternalidentifier ;
	owl:versionInfo	"2.3" ;
	omv:status		"beta" ;
	owl:deprecated	false ;
	owl:priorVersion	http://purl.myorganization.org/myonto-v2.2/
.
`
I allow myself to include a few other metadata annotation properties that I think are also useful to track versioning of ontologies.

**Comment by balhoff** [comment]
I like the idea of using `owl:priorVersion`.

**Comment by matentzn** [comment]
Ok ODK currently encourages (add templates for) these:

```
<owl:Ontology rdf:about="http://purl.obolibrary.org/obo/hp/hp-base.owl">
        <owl:versionIRI rdf:resource="http://purl.obolibrary.org/obo/hp/releases/2020-03-27/hp-base.owl"/>
        <dc:description>The Human Phenotype Ontology (HPO) provides a standardized vocabulary of phenotypic abnormalities and clinical features encountered in human disease.</dc:description>
        <dc:title>Human Phenotype Ontology</dc:title>
        <terms:license>https://hpo.jax.org/app/license</terms:license>
    </owl:Ontology>
```

So we can think about the rest:

- owl:ontologyIRI http://purl.myorganization.org/myonto -> Should be covered by the above rdfxml, right? Its just syntactic variation of `<owl:Ontology rdf:about="http://purl.obolibrary.org/obo/hp/hp-base.owl">`
- dct:identifier (should probably be optional, but makes sense to me!)
- owl:versionInfo "2.3" makes sense
- omv:status "beta" -> needs to go into OMO if we wanna do that but then, yes, also makes sense. In fact, good idea, given the number of `beta` versions of ontologies out there.
 - owl:deprecated false -> Not sure this makes very much sense, who would publish a new version of a deprecated ontology?
- owl:priorVersion -> nice idea. But very hard to automate in the context of ODK.. would have to be set manually I think, which puts additional strain on people that have automated their release pipeline.. Or do you see a way to reliable automate this @balhoff

**Comment by jonquet** [comment]
owl:ontologyIRI http://purl.myorganization.org/myonto -> Should be covered by the above rdfxml, right? Its just syntactic variation of <owl:Ontology rdf:about="http://purl.obolibrary.org/obo/hp/hp-base.owl">
=>Yes in principle. I think this is just another way to explicitly declare this. 

dct:identifier (should probably be optional, but makes sense to me!)
=> We have explicitly added another fied for ID in AgroPortal after request from some users to be able to have another identifier (typically a DOI) field for the ontontology

owl:versionInfo "2.3" makes sense
omv:status "beta" -> needs to go into OMO if we wanna do that but then, yes, also makes sense. In fact, good idea, given the number of beta versions of ontologies out there.
=> OMV was a vocabulary to describe ontologies. We are reusing the properties in [MOD now](https://github.com/sifrproject/MOD-Ontology).  I am not in favour of creating another metadata 
ontology (OMO) as I have expressed in the OMO issue discussion. 

owl:deprecated false -> Not sure this makes very much sense, who would publish a new version of a deprecated ontology?
=> totally right. This property take all its sense the day developers change the "false" by a "true" and then its super useful !! So I would recommend to have it just to make ontology developper aware this property exist and should one day maybe/eventually turn to true. 

owl:priorVersion -> nice idea. But very hard to automate in the context of ODK.. would have to be set manually I think, which puts additional strain on people that have automated their release pipeline.. Or do you see a way to reliable automate this @balhoff
=> True. But in one sense this kind of metadata property (as many useful other ones) can be automatically computed.

**Comment by matentzn** [comment]
Ok thanks for the input @jonquet 

I will look into this - in the context of the ODK, I can only really add mandatory fields (so deprecated and id can be added to the documentation as recommended properties, but not as mandatory), so I will start by adding the owl:versionInfo. I would be interested in the omv:status and owl:priorVersion as well; lets see whether we can find a way to do these right. Let's keep the OMO discussion elsewhere :P I am just wondering whether omv:status should simply be added to OMO as is (using the OMV IRI) and that's that (that is independent of whether OMO is a good idea or not).

**Comment by cmungall** [comment]
Yep, ODK already handles versionIRI, but it the workflow doesn't do versionInfo yet

**Comment by jonquet** [comment]
Complementary response to @matentzn 
>I am just wondering whether omv:status should simply be added to OMO as is (using the OMV IRI)

Indeed, this is also what we do in MOD which is a set of metadata properties relevant to describe ontologies. Note that also IDOT and ADMS provide a property that could also be used
https://github.com/sifrproject/MOD-Ontology/blob/master/mod-v1.4_profile.rdfs#L367

**Comment by matentzn** [comment]
moved the status discussion to OBO foundry. https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1213

**Comment by matentzn** [comment]
Moved the priorVersion discussion here: https://github.com/INCATools/ontology-development-kit/issues/342
