### ISSUE TITLE
No rule to make target 'imports/ecocore_import.owl'

### ISSUE THREAD

**Issue by nleguillarme** [INCATools/ontology-development-kit#343]
Hi, I am a new user of the ODK, trying to understand the ontology development workflow.

I would like to import a subset of the ECOCORE ontology. I  created a _ecocore_terms.txt_ file in the _imports_ folder, and would like to automatically create the corresponding _ecocore_import.owl_ file.

I understand that I should use ROBOT extract command for that, but should I call ROBOT from the command line, or can I use the `./run.sh make imports/ecocore_import.owl` command to create the owl file from the terms file ? When I try the second alternative, I have an error 

> make: *** No rule to make target 'imports/ecocore_import.owl'.  Stop.

I probably missed something. I would appreciate any help.

**Comment by matentzn** [comment]
Hey @nleguillarme :) Nice to meet you.

How have you created the repo in the first place? did you use a yaml file?

To add an import, you need to actually configure it when you create the repo. The ODK repo seeding pipeline will generate a new Makefile for you (and also an updated catalog.xml, imports files (the ones you have generated here by hand - you shouldn't have to). If you are down with taking it slow, I will walk you through it step by step!

**Comment by nleguillarme** [comment]
Hi, thank you for your help.
If I understand, I have to choose the ontologies I want to import when creating the repo.
But what if I want to update an ontology in an existing repo by importing a subset of a new ontology ? Is there any way to do that without regenerating the repo ?

**Comment by matentzn** [comment]
There is, with the latest two versions of the ODK. If you open the Makfile,
and scroll to the end, so you see update_repo? If so, edit the file
ont-odk.yaml in src/ontology with your imports and run ‘sh run.sh make
update_repo’. Then add the import to ont-edit.owl, and catalog.xml, and you
should be god to go. Let me know how it goes!

**Comment by nleguillarme** [comment]
Hi. It works like a charm.
I am still struggling with the ontology design workflow according to odk (and with ontology reuse in general).
I use BOT method to extract a module of the ecocore ontology given a list of terms which are relevant for my ontology. However, this module still contains a lot of concepts I do not need.
How should I proceed to obtain some kind of 'minimal subset' of ecocore tailored to my needs ? (is it even possible ?)
The only way to do it that I can think of right now is to implement a script that removes all irrelevant classes from ecocore-import.owl
Any best practice for this task ?

**Comment by matentzn** [comment]
MIREOT is not directly supported, but you can use the overwrite functionality of ODK:

open the file called `myont.Makefile`. This file basically functions as an extension to Makefile - everything you put in there will overwrite whatever you have in Makefile. Add a new goal (here I put an example of when I wanted to do some additional processing on the EFO module, but you get the picture. Just adjust this to extract MIREOT instead, and rename to `imports/ecocore_import.owl`):

```
imports/efo_import.owl: mirror/efo.owl imports/efo_terms_combined.txt
	@if [ $(IMP) = true ]; then $(ROBOT) extract -i $< -T imports/efo_terms_combined.txt --force true --method BOT \
		remove --base-iri http://www.ebi.ac.uk/efo/EFO_ --axioms external --exclude-term IAO:0000117 --exclude-term IAO:0000119 --preserve-structure false --trim false \
		query --update ../sparql/inject-subset-declaration.ru \
		remove -T imports/efo_terms_combined.txt --select complement --select "classes individuals" \
		annotate --ontology-iri $(ONTBASE)/$@ --version-iri $(ONTBASE)/releases/$(TODAY)/$@ --output $@.tmp.owl && mv $@.tmp.owl $@; fi
.PRECIOUS: imports/efo_import.owl
```

Let me know how this goes.

**Comment by matentzn** [comment]
Check for full example of somthing like that: https://github.com/EBISPOT/covoc/blob/master/src/ontology/covoc.Makefile

**Comment by nleguillarme** [comment]
Thank you, your example was very helpful.
I managed to import just the subset of ECOCORE which was relevant for my ontology, and to remove some concepts of RO which were irrelevant.

**Comment by matentzn** [comment]
Thats great! I will close this issue here, but feel free to open a new one whenever you need something!
