### ISSUE TITLE
What is the best way to cite ODK?

### ISSUE THREAD

**Issue by srobb1** [INCATools/ontology-development-kit#344]
Hello,

What is the best way to cite ODK? Also, if I am using ODK and following good ontology building practices that we all try to uphold, what else should I cite? I have

- DOSDP (Osumi-Sutherland et al., 2017)
- ROBOT (Jackson et al., 2019)
- MIRO (Matentzoglu et al., 2018)

I don't want to miss anything.

Thanks,
Sofia

**Comment by matentzn** [comment]
As always diligent and perfect! That's exactly the right papers; ODK does not have a paper, so you can use the link to the GitHub repo.
