### ISSUE TITLE
Include default github actions and delete .travis.yml

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-development-kit#346]
the template folder could have a `.github/workflows` folder with a workflow that simply runs make all. This could be used for deploying ontologies automatically. 

see also
https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1224

**Comment by matentzn** [comment]
Can you give us the step by step workflow
you envision here? No human review of release artefacts anymore?

**Comment by cmungall** [comment]
I think this ticket should now be clear, we are using gh actions more universally (we should make a separate ticket about releases)

we can use the GO ones as a template, we do these awesome PR diffs via actions:

 https://github.com/geneontology/go-ontology/pull/21221#commitcomment-48760499

**Comment by matentzn** [comment]
all of this is already done (since you can now configure which CI system you want to use) - basically you are asking to remove travis.yml from the default config. Will do that!

**Comment by matentzn** [comment]
Fixed in 1.2.27
