### ISSUE TITLE
Any advice for modular ontology architecture ?

### ISSUE THREAD

**Issue by nleguillarme** [INCATools/ontology-development-kit#347]
Hi everybody, here is what I'd like to do.

I am working on an ontology to help create soil trophic webs, and I would like to use a modular approach. So I created an ontology of trophic resources and an ontology of trophic groups using ODK, and my plan is to create an ontology that imports both and defines some axioms to link groups to resources.

Is this approach feasible using ODK ? Is that even a good approach ? I am wondering how I can import my groups and resources modules into the trophic web ontology using ODK. Should I request and IDSPACE from OBO for both modules, then a third IDSPACE for the full trophic web ontology ?

Thank you for your help.

**Comment by matentzn** [comment]
That is exactly what the ODK is there for! Modular development is often a good approach, especially if you expect the different ontology modules to be used separately in various contexts. Independent of whether you get an IDSPACE from the obofoundry, you can simply link an import to an arbitrary URL like so:

https://github.com/INCATools/ontology-development-kit/blob/4c01ef1e7cba7010f1658ccd1d2844775eed45b9/configs/fbcv-odk.yaml#L23

Note that modular development adds complexity. Not only do you have to request multiple namespaces (or manage ID ranges by saying: trophic groups get 0-4000000, and trophic resources get 4000001-99999999), but you also have to manage separate files, separate repos. So I would think of it from a user perspective: Would they likely to to want to import them seperately, or nearly always all together?

A mediocre measure here is rule of thumb: if there are many links between both vocabs, and there are not that many terms involved, maybe its easier to manage them all in a single ontology.

**Comment by matentzn** [comment]
@nleguillarme if you need further help, just let us know! Thanks!
