### ISSUE TITLE
What's wrong with multiple equivalent classes ?

### ISSUE THREAD

**Issue by nleguillarme** [INCATools/ontology-development-kit#361]
Hi.

When trying to build my ontology, I run into several multiple_equivalent_classes errors.
I understand from [here](http://robot.obolibrary.org/report_queries/multiple_equivalent_classes) that this is normal ROBOT behavior, but I'd like to understand why asserting more than one equivalent classes is a problem in itself ?

For instance, I want to define that a bacterivore organism is both :

- heterotroph and ('capable of' some bactivory)
- eats some (Bacteria or Archaea)

**Comment by balhoff** [comment]
I think the documentation is a little misleading, since having two different equivalent classes is not necessarily the same as intersection. It could be the case that both expressions are necessary and sufficient, so in effect you are making an equivalence between the expressions as well.

In general this check is there to help enforce editing practices in OBO, where it's most typical to have only one logical definition, and it may have been an accident to assert both.

What command reports this error? Initially I was thinking of `reason`, which has options for `--equivalent-classes-allowed`, but now I think that's a different situation.

**Comment by nleguillarme** [comment]
Thank you @balhoff 

Here is the full trace :

Makefile:182: warning: ignoring old recipe for target 'stwo-full.owl'
echo "ODK Makefile version: v1.2.23 (this is the version of the ODK with which this Makefile was generated, not the version of the ODK you are running)" &&\
echo "ROBOT version (ODK): " && robot --catalog catalog-v001.xml --version
ODK Makefile version: v1.2.23 (this is the version of the ODK with which this Makefile was generated, not the version of the ODK you are running)
ROBOT version (ODK): 
ROBOT version 1.7.0
robot --catalog catalog-v001.xml merge --input stwo-edit.owl \
	reason --reasoner ELK --equivalent-classes-allowed asserted-only \
	reduce -r ELK \
	annotate --ontology-iri http://purl.obolibrary.org/obo/stwo/stwo-full.owl --version-iri http://purl.obolibrary.org/obo/stwo/releases/2020-10-21/stwo-full.owl --output stwo-full.owl.tmp.owl && mv stwo-full.owl.tmp.owl stwo-full.owl
robot --catalog catalog-v001.xml annotate --input stwo-full.owl --ontology-iri http://purl.obolibrary.org/obo/stwo.owl annotate -V http://purl.obolibrary.org/obo/stwo/releases/2020-10-21/stwo.owl --annotation owl:versionInfo 2020-10-21 \
	convert -o stwo.owl.tmp.owl && mv stwo.owl.tmp.owl stwo.owl
robot --catalog catalog-v001.xml convert --input stwo.owl --check false -f obo  -o stwo.obo.tmp.obo && grep -v ^owl-axioms stwo.obo.tmp.obo > stwo.obo && rm stwo.obo.tmp.obo
robot --catalog catalog-v001.xml remove --input stwo-edit.owl --select imports --trim false \
	merge  \
	annotate --link-annotation http://purl.org/dc/elements/1.1/type http://purl.obolibrary.org/obo/IAO_8000001 \
	--ontology-iri http://purl.obolibrary.org/obo/stwo/stwo-base.owl annotate -V http://purl.obolibrary.org/obo/stwo/releases/2020-10-21/stwo-base.owl --annotation owl:versionInfo 2020-10-21 \
	--output stwo-base.owl.tmp.owl && mv stwo-base.owl.tmp.owl stwo-base.owl
robot --catalog catalog-v001.xml convert --input stwo-base.owl --check false -f obo  -o stwo-base.obo.tmp.obo && grep -v ^owl-axioms stwo-base.obo.tmp.obo > stwo-base.obo && rm stwo-base.obo.tmp.obo
robot --catalog catalog-v001.xml convert --input stwo-full.owl --check false -f obo  -o stwo-full.obo.tmp.obo && grep -v ^owl-axioms stwo-full.obo.tmp.obo > stwo-full.obo && rm stwo-full.obo.tmp.obo
robot --catalog catalog-v001.xml verify  --catalog catalog-v001.xml -i stwo-edit.owl --queries ../sparql/equivalent-classes-violation.sparql ../sparql/trailing-whitespace-violation.sparql ../sparql/owldef-self-reference-violation.sparql ../sparql/xref-syntax-violation.sparql ../sparql/nolabels-violation.sparql -O reports/
PASS Rule ../sparql/equivalent-classes-violation.sparql: 0 violation(s)
PASS Rule ../sparql/trailing-whitespace-violation.sparql: 0 violation(s)
PASS Rule ../sparql/owldef-self-reference-violation.sparql: 0 violation(s)
PASS Rule ../sparql/xref-syntax-violation.sparql: 0 violation(s)
PASS Rule ../sparql/nolabels-violation.sparql: 0 violation(s)
robot --catalog catalog-v001.xml query -f tsv -i stwo-edit.owl -s ../sparql/basic-report.sparql reports/basic-report.tsv -s ../sparql/class-count-by-prefix.sparql reports/class-count-by-prefix.tsv -s ../sparql/edges.sparql reports/edges.tsv -s ../sparql/xrefs.sparql reports/xrefs.tsv -s ../sparql/obsoletes.sparql reports/obsoletes.tsv -s ../sparql/synonyms.sparql reports/synonyms.tsv
robot --catalog catalog-v001.xml report -i stwo-edit.owl --fail-on None --print 5 -o reports/stwo-edit.owl-obo-report.tsv
Violations: 88
-----------------
ERROR:      40
WARN:       47
INFO:       1

First 5 violations:
ERROR	multiple_equivalent_classes	ECOCORE:00000015	owl:equivalentClass	18fcb196-b9e1-45c9-91e9-c415bb0c3757genid11	
ERROR	multiple_equivalent_classes	ECOCORE:00000015	owl:equivalentClass	18fcb196-b9e1-45c9-91e9-c415bb0c3757genid15	
ERROR	multiple_equivalent_classes	ECOCORE:00000019	owl:equivalentClass	18fcb196-b9e1-45c9-91e9-c415bb0c3757genid19	
ERROR	multiple_equivalent_classes	ECOCORE:00000019	owl:equivalentClass	18fcb196-b9e1-45c9-91e9-c415bb0c3757genid23	
ERROR	multiple_equivalent_classes	ECOCORE:00000045	owl:equivalentClass	18fcb196-b9e1-45c9-91e9-c415bb0c3757genid28

**Comment by matentzn** [comment]
Yeah, I agree with @balhoff 

Just think of the risk like this:

bacterivore organism = heterotroph and ('capable of' some bactivory)
bacterivore organism = eats some (Bacteria or Archaea)

This would imply that:
```
heterotroph and ('capable of' some bactivory) = eats some (Bacteria or Archaea)
```

So we try to avoid it - there is a very high likelihood that this could go wrong (better use subclass of!)

In your case it seems the problem comes from an external ontology. The only way to handle this case is to set

```
--fail-on None
```

When ROBOT report is run (see your Makefile).

**Comment by matentzn** [comment]
http://robot.obolibrary.org/report

**Comment by matentzn** [comment]
You can also do it the right way:
1. Add [this line](https://github.com/INCATools/ontology-development-kit/blob/1a5b53818bfa384f5f1e78edef1c00b42d372f0c/configs/bto-odk.yaml#L5) to your `src/ontology/stwo-odk.yaml` file
2. In terminal: `sh run.sh make update_repo`

This will overwrite your Makefile to add that setting

**Comment by matentzn** [comment]
OH wait! You didnt fail! You already have that!

In that case, you can only ignore.. sorry! Or make a ticket on ECOCORE repo! That is the best!

**Comment by nleguillarme** [comment]
Thank you @matentzn for all these explanations and the workaround.

> Just think of the risk like this:
> 
> bacterivore organism = heterotroph and ('capable of' some bactivory)
> bacterivore organism = eats some (Bacteria or Archaea)
> 
> This would imply that:
> 
> ```
> heterotroph and ('capable of' some bactivory) = eats some (Bacteria or Archaea)
> ```

I am no expert in trophic groups but as far as I know, there is nothing wrong in this equality. It is ok for me that all individuals of "heterotroph and ('capable of' some bactivory)" be also individuals of "eats some (Bacteria or Archaea)".

But maybe I misunderstood the semantics of owl:equivalentClass. I must say that I hesitated between equivalency and subclass when starting writing these definitions (I realize I didn't tell you that the first definition of bacterivore is ECOCORE's, while the second is an addition on my part).

**Comment by matentzn** [comment]
if you use subclass, you can circumvent all the problems here.. I think this case is borderline, but you can see how easily an equivalence like that can go wrong, right? Thats why the OBO foundry decided to advice against having multiple logical definitions. There are some discussions about whether to loosen this a bit, but your case would still be flagged as an ERROR because of the risk it poses to other ontologies! ;)

**Comment by matentzn** [comment]
BTW: you should feel free to edit ECOCORE directly and make respective pull requests, if you think they missed something! Thats the OBO spirit :P

**Comment by nleguillarme** [comment]
Thank you, it's crystal clear.

> BTW: you should feel free to edit ECOCORE directly and make respective pull requests, if you think they missed something! Thats the OBO spirit :P

Actually, I am working on what could be seen as a big update of ECOCORE, but we chose to work on a separate ontology, then submit all our changes to ECOCORE.

**Comment by cmungall** [comment]
This is an interesting one

Yes, multi-equivs are frequently a bad smell and even if not directly incorrect can point to problematic modeling patterns, e.g. too many ways to say the same thing

I think they should be allowed in the hands of experts. Maybe ROBOt default should not be error.

In this case I would not weaken both to subClassOf. Intuitively 'bacteriovore organism' is a trivially compositional class, and all such classes should have logical definitions.

I am inclined to agree with @nleguillarme that all 3 class expressions are mutually equiv, but a number of things give me pause. We'd need full definitions of `eats` and `bactivory`. The implicit modal logic in `eats` is a flag.

What I think at first looks suspicious about

`heterotroph and ('capable of' some bactivory) = eats some (Bacteria or Archaea)`

is that the RHS lacks the heterotroph clause. But then I think this is justified by a crytpic axiom that anything that eats a cell is automatically a heterotroph. But there is a lot that needs unpacked here. Is being a het or autotroph a rigid quality? What about things that switch like Euglena?

What is really worrying is that I am seeing multiple ways to say the same thing, you have material entity classes like 'Xtroph', processes like Xtrophy or Xivory... maybe there are roles in there too.

**Comment by cmungall** [comment]
My recommendation would be to structure as follows:

 1. ('capable of' some bactivory) = eats some (Bacteria or Archaea)
 2. bacterivore organism = organism and capable_of some bactivory

I think this is easier to maintain, more modular, leads to better alignment of textual and logical defs (https://douroucouli.wordpress.com/2019/07/08/ontotip-write-simple-concise-clear-operational-textual-definitions/), and is easier to mentally reason over.

Better yep, templates:

 1. ('capable of' some Xory) = eats some X
 2. Xore organism = organism and capable_of some Xory

You can also add

 3. bacterivore organism subClassOf heterotroph

Or you could infer this too:

 4. heterotroph = eats some macromolecule or cellular organism or ...

The originally stated equivalence groups are then entailed

**Comment by nleguillarme** [comment]
Thank you @cmungall for your recommendations. I totally agree with you, and I am happy to read your view on over-specified genus : the fact that a bacterivore organism is defined as "heterotroph and..." is a source of difficulties for inferring diets from binary trophic interactions.

> * ('capable of' some bactivory) = eats some (Bacteria or Archaea)

I have a practical question : how do you define such anonymous classes using an editor like Protégé ? Should I create a class with a label "capable of some bactivory" ?

**Comment by matentzn** [comment]
Hey @nleguillarme you should join us in our OBO slack space! If you give me an email, I will send you an invite.. i think this discussion is interesting, but has escaped the tickets scope a bit. :) Note also that there is a big ecocore update with stuff relevant to you! Check it out when you have the time.

**Comment by nleguillarme** [comment]
Hi @matentzn, I'll be glad to join the OBO slack : nicolas.leguillarme@univ-grenoble-alpes.fr
Thank you.
