### ISSUE TITLE
synonym documentation - edits

### ISSUE THREAD

**Issue by nicolevasilevsky** [INCATools/ontology-development-kit#366]
From @paolaroncaglia 

Hi, wrt synonyms: definitely good “first edits” for new curators, and great to have some documentation! May I please add a couple of suggestions if they haven’t been covered yet: 1) please document how to best represent acronyms; 2) when adding narrow or broad synonyms, document the decision process the editor should go through i.e. considering if there’s scope/need for new terms instead of narrow/broad synonyms. For 1), consider how acronyms are often added as exact synonyms, but very often they aren’t; “related” may be too unspecific; “narrow” may be best? Would be good to adopt a consensus across ontologies. Or is there a specific annotation property that could be used? (I think I’ve seen something in Mondo) If so, should CL import it? Thanks!

**Comment by nicolevasilevsky** [comment]
@cmungall I don't see the new synonym page appearing here:
https://ontology-development-kit.readthedocs.io/en/latest/

**Comment by matentzn** [comment]
https://ontology-development-kit.readthedocs.io/en/latest/Synonyms.html
