### ISSUE TITLE
Can't find imports folder

### ISSUE THREAD

**Issue by mateolan** [INCATools/ontology-development-kit#37]
Trying to make a new ontology and it looks like at least one folders are missing, and content can't get added. 
Error:
<snip>
cp: cannot stat ‘imports/*{owl,obo}’: No such file or directory
make: *** [prepare_release] Error 1
FAILURE
EXECUTING: git add src/ontology/imports/*{obo,owl}
fatal: pathspec 'src/ontology/imports/*{obo,owl}' did not match any files
ERROR RUNNING: git add src/ontology/imports/*{obo,owl}
EXECUTING: git add triffo.{obo,owl}
fatal: pathspec 'triffo.{obo,owl}' did not match any files
ERROR RUNNING: git add triffo.{obo,owl}
EXECUTING: git add imports/*{obo,owl}
fatal: pathspec 'imports/*{obo,owl}' did not match any files
ERROR RUNNING: git add imports/*{obo,owl}
EXECUTING: git commit -m 'initial release of triffo using ontology-starter-kit' -a
</snip>

**Comment by matentzn** [comment]
Hey, closing this issue due to long inactivity. Please re-open if necessary.
