### ISSUE TITLE
EDITORS: make: robot: No such file or directory when running example

### ISSUE THREAD

**Issue by clairececchini** [INCATools/ontology-development-kit#38]
Reproduce this bug by:

```
make test1
cd target/my-ontology/src/ontology
make
```

I get:

```
make: robot: No such file or directory
```

Two questions:

1)  Aren't [line 86](https://github.com/INCATools/ontology-starter-kit/blob/master/template/src/ontology/Makefile#L86) and [line 95](https://github.com/INCATools/ontology-starter-kit/blob/master/template/src/ontology/Makefile#L95) supposed to be `$(ROBOT)` instead of `robot`?

2) Even if I correct the above issue, my terminal still doesn't find the robot command. I have already added it to the PATH and I can use it from the terminal but `make` still doesn't find it  Am I supposed to change [line 11](https://github.com/INCATools/ontology-starter-kit/blob/master/template/src/ontology/Makefile#L11) to point the ROBOT variable to where robot is on my system or is there a different way to do this?

**Comment by clairececchini** [comment]
@cmungall could you review this please? I'm not sure what I'm doing wrong. Thanks!

**Comment by clairececchini** [comment]
@cmungall any updates on this? I think it's the same problem we have in #40

**Comment by matentzn** [comment]
Hey! Closing this now due to long inactivity! Please re-open again if the problem persists.
