### ISSUE TITLE
Improve the CONTRIBUTING.md.jinja2 template

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-development-kit#380]
I like the one the energy ontology has (cc @jannahastings):

https://github.com/OpenEnergyPlatform/ontology/blob/dev/CONTRIBUTING.md

See also
https://docs.google.com/presentation/d/1nIybviEEJiRKHO2rkBMZsQ0QjtsHyU01_-9beZqD_Z4/edit#slide=id.g261c210695_0_16

https://mozillascience.github.io/working-open-workshop/contributing/

We could also eat our own dog food and improve the docs for contributing to this repo:

https://github.com/INCATools/ontology-development-kit/blob/master/CONTRIBUTING.md

**Comment by cmungall** [comment]
It would be good to take a pass at this - we really want to spread best practice as far as possible and the CONTRIBUTING.md is the best vector for this. See https://github.com/bio-ontology-research-group/unit-ontology/issues/51

**Comment by matentzn** [comment]
Look at PRs, @cthoyt just started st.

I started something more crazy for SSSOM https://github.com/mapping-commons/sssom/pull/175

**Comment by cmungall** [comment]
I see this PR:

- #598 

This is a great start. But maybe we can keep it simple. We can link out to a lot of docs. We just need to tell people the basics here and avoid the mistakes that keep happening again and again such as people not making PRs on edit files (see https://github.com/information-artifact-ontology/IAO/pull/256)
