### ISSUE TITLE
error in seed-via-docker.sh

### ISSUE THREAD

**Issue by megbalk** [INCATools/ontology-development-kit#381]
I'm getting the following error when running this script:

Traceback (most recent call last):
  File "/tools/odk.py", line 790, in <module>
    cli()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/tools/odk.py", line 688, in seed
    raise Exception('max one repo; current={}'.format(repo))
Exception: max one repo; current=('futres', 'uberon-fovt')

Is this an error in the python version?

**Comment by matentzn** [comment]
can you share your command?

you should probably use -c -C config.yaml

where the -c (lowercase) cleans the workspace (deletes the old version) first.

**Comment by megbalk** [comment]
This is the command I used: 
./seed-via-docker.sh -d uberon -d bspo -d ro futres -t "UBERON-FOVT module" uberon-fovt

**Comment by matentzn** [comment]
can you try:

```
./seed-via-docker.sh -c -d uberon -d bspo -d ro futres -t "UBERON-FOVT module" uberon-fovt
```

**Comment by matentzn** [comment]
I also think its probably a good idea not to use an ontology id with a dash - but I am not sure.. so:

```
./seed-via-docker.sh -c -d uberon -d bspo -d ro futres -t "UBERON-FOVT module" uberonfovt
```

**Comment by megbalk** [comment]
I get the same error when running the new script

**Comment by matentzn** [comment]
Maybe it's your command - why does it say futres in the middle ? Is that another obo ontology?

**Comment by megbalk** [comment]
no, that's the project folder. In the example it was cmungall, which I assumed was the git owner for where the repo will be?

**Comment by matentzn** [comment]
```
./seed-via-docker.sh -c -d uberon -d bspo -d ro -u futres -t "UBERON-FOVT module" uberonfovt
```

you were missing -u.

futures is and must be your github username or that of your organisatiom.

**Comment by megbalk** [comment]
that did the trick! thank you!
