### ISSUE TITLE
running wrapper script using terminal (not the .yaml file) 

### ISSUE THREAD

**Issue by teleaslamellatus** [INCATools/ontology-development-kit#384]
When using the wrapper script in terminal (command line):

"./seed-via-docker.sh -d po -d ro -d pato -u cmungall -t "Triffid Behavior ontology" triffo"

the x-odk.yaml file will not be created in src.

i

**Comment by matentzn** [comment]
Thank you @teleaslamellatus for the issue! Keep them coming!
