### ISSUE TITLE
Add Jena tools?

### ISSUE THREAD

**Issue by balhoff** [INCATools/ontology-development-kit#398]
Jena is very useful for working directly with RDF. Sometimes it doesn't make any sense to have ROBOT try to parse RDF into OWL. Can we add the Jena command line tools? Here's how I did it for another docker container:

https://github.com/phenoscape/pipeline-tools/blob/7d6eb2717df9a553cdae3b4063c5b9787d363ec7/Dockerfile#L44-L47

**Comment by matentzn** [comment]
Added in https://github.com/INCATools/ontology-development-kit/pull/408

**Comment by balhoff** [comment]
Thanks Nico!

**Comment by matentzn** [comment]
No problem :) If you could try and keep our jena (and owltools) versions a bit in sync (ubergraph-odk) that would help, but no sweat.
