### ISSUE TITLE
robot validate-profile using DL profile should be part of the test suite for all ontologies

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-development-kit#401]
Carried from:

https://github.com/obophenotype/uberon/issues/541

We should run `robot validate-profile -p DL -i ONT.owl` as part of test - on bth edit file and merged release file

currently ENVO fails which percolates to ontologies that import ENVO such as ECTO, and ontologies that import ECTO, such as Mondo, and so on...

**Comment by matentzn** [comment]
Yes!

**Comment by matentzn** [comment]
Added profile checking here:
https://github.com/INCATools/ontology-development-kit/pull/408


But its switched off by default
