### ISSUE TITLE
Add option to generate - relaxed product

### ISSUE THREAD

**Issue by dosumis** [INCATools/ontology-development-kit#402]
Relaxed product will named {prefix}-relaxed.owl.  It will be derived from -full.owl but with all EC axioms relaxed to SC axioms using [robot relax](http://robot.obolibrary.org/relax).

**Comment by matentzn** [comment]
How does this differ from full: https://github.com/INCATools/ontology-development-kit/blob/master/docs/ReleaseArtefacts.md#release-artefact-2-full-required

**Comment by dosumis** [comment]
Ahh - didn't realise that had a relax step.  It turns out that robot relax won't turn  EC: C and R value I -> SC: C, SC: R value I.   This is a problem for a pipeline we're running (we need "SC: R value I" to make an neo edge via owl2neo). I'll request a fix to ROBOT, but we'll need to find some other way to hack around for now.
