### ISSUE TITLE
Add relation-graph and steps to make an ubergraph-style triplestore

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-development-kit#403]
This is very useful https://github.com/balhoff/relation-graph

I'm not sure if it should be added to odk or directly to robot, cc @balhoff 

it is incredibly useful to get the inferred relational graph. I may even consider distributing this with some of my ontologies (though it can be large).

if RG is added then we can add some of the steps from here https://github.com/NCATS-Tangerine/ubergraph/blob/master/Makefile

This will give every ontology developer a useful triplestore stack with entailed inferences. This is especially nice for making importer/application ontologies using ODK.

Broader context:

https://docs.google.com/document/d/1Nr6mon6FEZAyvkAKC5OFmTLk5uANWzhoXUjxZVmOEJk/edit#

**Comment by matentzn** [comment]
- [X] Add relationgraph #529 

Lets make more differentiated tickets for the triple store question.. Feels like a mild degree of scope creep.
