### ISSUE TITLE
Run the wrapper script： Makefile:250: recipe for target 'mirror/po.owl' failed

### ISSUE THREAD

**Issue by DarkKnight0-0** [INCATools/ontology-development-kit#412]
if [ true  = true ] && [ true  = true ]; then robot --catalog catalog-v001.xml convert -I http://purl.obolibrary.org/obo/po.owl -o mirror/po.owl.tmp.owl && mv mirror/po.owl.tmp.owl mirror/po.owl; fi
org.semanticweb.owlapi.io.OWLOntologyCreationIOException: Connection refused (Connection refused)
Use the -vvv option to show the stack trace.
Use the --help option to see usage information.
Makefile:250: recipe for target 'mirror/po.owl' failed

ERROR:root:make: *** [mirror/po.owl] Error 1

Traceback (most recent call last):
  File "/tools/odk.py", line 876, in <module>
    cli()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/tools/odk.py", line 841, in seed
    runcmd("cd {}/src/ontology && make && git commit -m 'initial commit' -a && make prepare_initial_release && git commit -m 'first release'".format(outdir))
  File "/tools/odk.py", line 870, in runcmd
    raise Exception('Failed: {}'.format(cmd))
Exception: Failed: cd target/triffo/src/ontology && make && git commit -m 'initial commit' -a && make prepare_initial_release && git commit -m 'first release'

**Comment by DarkKnight0-0** [comment]
I tried many times, but do not know how to fix the 'Connection refused'.

**Comment by matentzn** [comment]
Can you share the exact steps you ran?

**Comment by DarkKnight0-0** [comment]
I just try the example on Ubuntu 18.04.4, Docker version 20.10.6, build 370c289：
git clone git@github.com:INCATools/ontology-development-kit.git
cd ontology-development-kit
./seed-via-docker.sh  -d po ro pato -u cmungall -t "Triffid Behavior ontology" triffo

**Comment by DarkKnight0-0** [comment]
When I run the script, my VPN using Anyconnect will be disconnected and reconnected after finishing running the script.
I tried just now, I cannot access http://purl.obolibrary.org/obo/po.owl  without VPN.

**Comment by matentzn** [comment]
Hm, regarding the PO issue, i cant help you - this is a problem of PO ontology, or rather your local network, as PO is hosted on GitHub! But your command is wrong - it should be:

```
 ./seed-via-docker.sh -d po -d ro -d pato -u cmungall -t "Triffid Behavior ontology" triffo
```

(mind the `-d` parameter). 

You could try this as well:

```
 ./seed-via-docker.sh -d ro -u DarkKnight0-0 -t "Triffid Behavior ontology" triffo
```

and see how it goes. Good luck!

**Comment by DarkKnight0-0** [comment]
> Hm, regarding the PO issue, i cant help you - this is a problem of PO ontology, or rather your local network, as PO is hosted on GitHub! But your command is wrong - it should be:
> 
> ```
>  ./seed-via-docker.sh -d po -d ro -d pato -u cmungall -t "Triffid Behavior ontology" triffo
> ```
> 
> (mind the `-d` parameter).
> 
> You could try this as well:
> 
> ```
>  ./seed-via-docker.sh -d ro -u DarkKnight0-0 -t "Triffid Behavior ontology" triffo
> ```
> 
> and see how it goes. Good luck!

Thanks! Still the same problem. I will try other ways.
