### ISSUE TITLE
Version IRIs for import files with a release

### ISSUE THREAD

**Issue by ramonawalls** [INCATools/ontology-development-kit#415]
When I prepare a release, the import files are copied from /src/ontology/imports to /imports, which is good, but it does not add a version IRI to the files in /imports? Is that the expected behavior? Do I need to configure my makefile differently to make this happen? Could the problem be because I make my imports manually and skip regenerating them when I make the release?

**Comment by matentzn** [comment]
The imports only get a version IRI when they are created - so its not corresponding to the ontology version (at least not if they are not run on the same day). This is, however, does make some sense. The version IRI in the module reflects when the module was last extracted. But if someone were to, say try to obtain http://purl.obolibrary.org/obo/omrse/releases/2021-03-02/imports/ogms_import.owl, they would not necessarily get the module corresponding to that tag - they would get the module which was active on the day that the ontology release happened. So they would get the module that was "the one" on the 2021-03-02; regardless of wether there version IRI is http://purl.obolibrary.org/obo/omrse/releases/2021-03-02/imports/ogms_import.owl or http://purl.obolibrary.org/obo/omrse/releases/2019-03-02/imports/ogms_import.owl.

**Comment by ramonawalls** [comment]
Baring oversight, the ontologies I manage do merge imports before release.

**Comment by ramonawalls** [comment]
Looks like I don't have the power to reopen this ticket.

**Comment by matentzn** [comment]
Hmm, this is how a module generated by a current ODK setup looks like for example:

https://github.com/pato-ontology/pato/blob/master/src/ontology/imports/chebi_import.owl

Is this not what you mean?

**Comment by matentzn** [comment]
Feel free to share a link to the ontology with me and I will help you sort it out directly!
