### ISSUE TITLE
change setup branch to "main"

### ISSUE THREAD

**Issue by wdduncan** [INCATools/ontology-development-kit#417]
After running seed, the instructions push the new repo to the `master` branch. We should setup a new repo on the `main` branch.

**Comment by matentzn** [comment]
Thanks Bill. I fixed the instructions:
https://github.com/INCATools/ontology-development-kit/commit/b2c02d98935d458e1f57a21dafd008824c2b6947

Do you think that will do it?

**Comment by wdduncan** [comment]
In order to get it work for me, I had to use two instructions:
```
git branch -M main
git push -u origin main
```
So, you may need to add:
```
print("git branch -M main\n") 
```

**Comment by matentzn** [comment]
Great, thank you @wdduncan! Done.
