### ISSUE TITLE
catalog-v001.xml import uris incorrect for components

### ISSUE THREAD

**Issue by wdduncan** [INCATools/ontology-development-kit#418]
related to https://github.com/INCATools/ontology-development-kit/pull/416

The generated `catalog-v001.xml ` file contained the import group:
```xml
 <group id="Folder Repository, directory=, recursive=false, Auto-Update=false, version=2" prefer="public" xml:base="">
        <uri name="http://purl.obolibrary.org/obo/nmdco/imports/ro_import.owl" uri="imports/ro_import.owl"/>
        <uri name="http://purl.obolibrary.org/obo/nmdco/imports/ro_import.obo" uri="imports/ro_import.obo"/>
        <uri name="http://purl.obolibrary.org/obo/nmdco/components/po.owl" uri="components/po.owl"/>
        <uri name="http://purl.obolibrary.org/obo/nmdco/components/envo.owl" uri="components/envo.owl"/>
    </group>
```
However, the uris for the `po` and `envo` ontologies in the `components` directory had the uris:
```
http://purl.obolibrary.org/obo/nmdco/releases/2021-05-03/components/po.owl
http://purl.obolibrary.org/obo/nmdco/releases/2021-05-03/components/envo.owl
```
The uris in `catalog-v001.xml` are missing **releases/2021-05-03**.

Also, the `imports/ro_import.obo` file was not generated.

**Comment by matentzn** [comment]
Are you certain that `http://purl.obolibrary.org/obo/nmdco/releases/2021-05-03/components/po.owl` was not the version IRI? That would be the mistake.. components/po.owl should have:

`http://purl.obolibrary.org/obo/nmdco/releases/2021-05-03/components/po.owl` as version iri and `http://purl.obolibrary.org/obo/nmdco/components/po.owl` as IRI, and that should be in the catalog.. If you confirm this I will fix it immediately. 

> Also, the imports/ro_import.obo file was not generated.

Yeah I removed that a few months back - we only generate OBO imports in the scenario that OBO is the format of the edit file.. There were just too many files being created and people were complaining. Do you find this odd? Would you like me obo imports to be generated even if the edit file is in OWL? If so, why? - I could make this an option if the use case is clear. :) Thanks again @wdduncan for providing feedback :)

**Comment by wdduncan** [comment]
Yes. You are right! Sorry, I was looking at the version iri :(

**Comment by matentzn** [comment]
No worries, thank you!
