### ISSUE TITLE
Allow choice of format for -edit file, including OBO

### ISSUE THREAD

**Issue by dosumis** [INCATools/ontology-development-kit#42]
Given that the OWL-API now consumes OBO with no problems and the some of us still prefer master files to be OBO format for diff/merge/patch, can seed_my_ontology_repo come with an OBO option.  Would also be nice to have a choice of other formats, including OFN.

**Comment by cmungall** [comment]
We use a no-logic template approach, so changes in filenames have to be done procedurally.. but this should be straightforward.

I note that some ontologies like cl use a filename cl-edit.owl but the syntax is ofn. Formally it should be ofn but doesn't seem to cause any confusion.

**Comment by matentzn** [comment]
OBO and OWL is allowed, this should be enough.
