### ISSUE TITLE
Issues with importing simplified version of AISM for order-specific insect ontologies

### ISSUE THREAD

**Issue by JCGiron** [INCATools/ontology-development-kit#431]
At some point @matentzn helped István Mikó to come up with a script to import a “reduced” version of the AISM (https://github.com/insect-morphology/aism), in order to use the AISM as a base for order-specific ontologies.

This was the script:
```
AISM_BASE="https://raw.githubusercontent.com/insect-morphology/aism/master/aism-base.owl"
mirror/aism-base.owl:
	if [ $(MIR) = true ] && [ $(IMP) = true ]; then $(ROBOT) convert -I "$(AISM_BASE)" -o $@.tmp.owl && mv $@.tmp.owl $@; fi
.PRECIOUS: mirror/aism-base.owl
tmp/seed_aism_base.txt: mirror/aism-base.owl
	@if [ $(IMP) = true ]; then $(ROBOT) query -i $< -q ../sparql/terms.sparql $@; fi
imports/aism_import.owl: mirror/aism.owl tmp/seed_aism_base.txt
	@if [ $(IMP) = true ]; then $(ROBOT) remove -i $< -T tmp/seed_aism_base.txt --select complement --select "classes individuals" \
		annotate --ontology-iri $(ONTBASE)/$@ --version-iri $(ONTBASE)/releases/$(TODAY)/$@ --output $@.tmp.owl && mv $@.tmp.owl $@; fi
.PRECIOUS: aism_import.owl
````
@luis-gonzalez-m and I used that to create new ontologies (https://github.com/insect-morphology/colao and https://github.com/insect-morphology/lepao) and noticed that a bunch of terms from the current version of AISM are missing from both COLAO and LEPAO. How can we make sure that at least all the AISM terms get imported by using this script?

Also, we were wondering if this script or an additional one could “clean up” both the extra object properties and annotation properties that are not used in AISM.

Thanks!

**Comment by matentzn** [comment]
I cant confirm that this term exists: http://www.ontobee.org/ontology/AISM?iri=http://purl.obolibrary.org/obo/AISM_0004165

Note that a term only exists, if it was properly released; its existence in the edit file does not matter. Did you run the 

```
sh run.sh make prepare_release
```

Pipeline on AISM?

**Comment by JCGiron** [comment]
Yes, I ran the release after that term was included (term's definition created on 2021-04-10; release on 2021-05-21).

There seems to be a problem with the incorporation of the whole AISM in OntoBee and I don't know why that is.
![image](https://user-images.githubusercontent.com/37313282/119643962-fb84ae80-bde1-11eb-9064-8ee4164f6df7.png)

The AISM is complete at OLS (https://www.ebi.ac.uk/ols/ontologies/aism/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FAISM_0004165): 
![image](https://user-images.githubusercontent.com/37313282/119644177-325ac480-bde2-11eb-9bf0-16774608ee22.png)

Aso in BioPortal (https://bioportal.bioontology.org/ontologies/AISM/?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FAISM_0004165&jump_to_nav=true):
![image](https://user-images.githubusercontent.com/37313282/119644877-055ae180-bde3-11eb-8baf-f74c1aea5d85.png)

And if you go to the file that the script is calling (https://raw.githubusercontent.com/insect-morphology/aism/master/aism-base.owl) and search for "AISM_0004165", the term is there and it is fully annotated.
![image](https://user-images.githubusercontent.com/37313282/119644390-6a620780-bde2-11eb-9b75-b469598a360c.png)

**Comment by matentzn** [comment]
Hmm. I just cloned https://github.com/insect-morphology/colao and ran:

```
sh run.sh make refresh-aism
```

And the missing term appeared. What command where you using to refresh the import?

**Comment by JCGiron** [comment]
After modifying the .Makefile to include the script I ran `sh run.sh make update_repo`, and then `sh run.sh make all_imports`.

**Comment by matentzn** [comment]
Should work, but try `sh run.sh make refresh-aism` as well, just to see. And instead of `sh run.sh make all_imports` try `sh run.sh make refresh-imports`

**Comment by JCGiron** [comment]
Yep, it worked. I'll add `sh run.sh make refresh-aism` to our workflow. Thank you, @matentzn!

Now, for the second part of this issue: "Also, we were wondering if this script or an additional one could “clean up” both the extra object properties and annotation properties that are not used in AISM."-- should I create a new issue?

Also, do you know how can we update the record in OntoBee for them to incorporate the appropriate AISM files?

**Comment by matentzn** [comment]
Unfortunately, I don't know anything about ontobees update cycle. I would email to Oliver He, or maybe try to ping him on slack.

> Also, we were wondering if this script or an additional one could “clean up” both the extra object properties and annotation properties that are not used in AISM

This is not an "issue" unfortunately.. This is part of your pipeline, and you will have to extend your pipeline to support this.. If you want to solve this, I can help you, but you will first have to do something: A ROBOT tutorial. @jamesaoverton for an end to end tutorial, is there anything you would personally recommend to do to start with?

**Comment by jamesaoverton** [comment]
The best quick overview of ROBOT is this: https://github.com/ontodev/robot-tutorial

The ROBOT webpage has reference documentation for each command: http://robot.obolibrary.org/

**Comment by matentzn** [comment]
@JCGiron let me know if you need help. Basically I would:
1. Do the entire tutorial
2. figure out how you can use `robot remove` to get rid of the properties you don't like
3. edit `src/ontology/myont.Makefile` (where myont is the name of your ontology) to include your new remove sub-command in the correct make goal.

Let me know if I can advice on anything else. Would you mind closing this issue here, or letting me know what else is required before it can be closed?

**Comment by JCGiron** [comment]
Thank you @matentzn. I will do my homework and let you know if I have any questions. Thanks for your time!
