### ISSUE TITLE
Update and unify "Set up Protege" instructions

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#437]
https://github.com/INCATools/ontology-development-kit/blob/master/docs/InitialSetup.md

@nicolevasilevsky Can you make sure these instructions are up to date, and the only place on the whole internet that has them? :-)

**Comment by nicolevasilevsky** [comment]
yes, will do!

**Comment by nicolevasilevsky** [comment]
we need documentation for Windows too

**Comment by nicolevasilevsky** [comment]
how can I edit the GO wiki? The instructions are for the ELK 0.4.3, it should be updated for ELK 0.5

**Comment by matentzn** [comment]
Lets just make perfect instructions in one place, no more GO Wiki stuff - this is what GO needs to take care of themselves. I think we should just create a centralised resource in the ODK repo for now!

**Comment by StroemPhi** [comment]
Am I understanding this right, that there should be something like this:

- install GitHub Desktop (Linux/iOS/Win)
  - clone repo, make & checkout issue branch, work and push to issue branch, make pull request
     - is this only meant for repo maintainers or also for external contributors? if latter maybe add something like, make issue in upstream repo (so it can be discussed in the right spot), work in issue branch of fork and make PR of fork/issue branch to upstream/main?
- install Protege (Linux/iOS/Win)
  - what is an ID range, how do I know which is my range and how do I set it
  - how do I set my ORCID and correct attribution metadata (=dct:contributor)

**Comment by matentzn** [comment]
@StroemPhi 

We have done quite a bit on this recently in [OBOAcademy](https://oboacademy.github.io/obook/lesson/contributing_to_obo_ontologies/) 

This issue is now taken care of there. Good you bring this up so I can close it :D
