### ISSUE TITLE
imports generation doesn't extract seed from source ontology.  It should.

### ISSUE THREAD

**Issue by dosumis** [INCATools/ontology-development-kit#44]
Looks like this is the intent:

```make
# Use ROBOT, driven entirely by terms lists NOT from source ontology
imports/%_import.owl: mirror/%.owl seed.txt
	$(ROBOT) extract -i $< -T imports/$*_terms.txt --method BOT -O $(BASE)/$@ -o $@
.PRECIOUS: imports/%_import.owl
```

Adding new terms for import to `imports/fu_terms.txt` is a bit of a faff when editing in Protege.  Easier just to add new declaration to source.  This is even more of an issue when trying to migrate an existing ontology into this framework or when working with some new application ontology built from various existing ones.  

It looks like GO handles this via a SPARQL query to generate a seed file listing classes for import:

```make
seed.txt: enhanced.owl
	$(ROBOT) query -f csv -i $< --select ../sparql/terms.sparql $@
```

I could add this myself as a pull request, but wondering ability to extract seed list will be built into ROBOT soon.

**Comment by matentzn** [comment]
This has been the case for a while now, closing.
