### ISSUE TITLE
Best way to upgrade all imports

### ISSUE THREAD

**Issue by nleguillarme** [INCATools/ontology-development-kit#450]
Hi.

I am working on a new release of my domain ontology, and I'd like this new release to import the last versions of the imported ontologies (e.g. ECOCORE, NCBITaxon, etc...).

It seems that import files are not automatically updated when running make all_imports, so I would like to know what is the best way to proceed.

Thank you.

**Comment by matentzn** [comment]
Hey @nleguillarme 

I think the command is correct. Can you run 

sh run.sh make all_imports -B


Just to see what happens? If the repo is public, would be good if I could take a look!

**Comment by matentzn** [comment]
Please feel free to reopen if necessary
