### ISSUE TITLE
Base files and base plus proposal

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#454]
We have been thinking about how to solve our dependency madness problem (CL->GO'->CL->GO'', where `GO'` is a different version than `GO''`).  Base files are defined as "the set of axioms natively defined in an ontology, and only those axioms" - which basically means: all axioms excluding those imported from elsewhere.

The system is great, but it **has a problem**: The ontology developer relinquishes control of their classification, which is arguably the most important part of the ontology. There are two important risks to consider:

1. **Important classification is lost:** For example, if `uberon.owl` (all axioms in uberon, including external ones) implies that `UBERON:arm` is a `UBERON:limb`, but this subsumption is not asserted (only inferred), there is no guarantee that downstream users of `uberon-base.owl` will see this subsumption.
2. **Unintended classification is introduced:** Downstream users inadvertently may alter the classification when combing two or more basefiles by adding axioms that lead to additional inferences between "base" entities.

Both of these reduce trust in the ontologies classification by our users - and trust IMO this is the most important thing when talking about ontologies.

We hereby propose the definition of a new kind of base (here named base-plus, but we could simply redefine "base" to be "base-plus") which is the union of
- the old base file as defined [here](https://github.com/INCATools/ontology-development-kit/blob/master/docs/ReleaseArtefacts.md)
- the complete classification between all base entities. Precisely: for each base entity, the exhaustive list of all its super classes of the form `A` (named superclasses) and `R some B` (all existential restrictions) - note that A and B are not necessarily base entities. Note that this included both `reason` and `reduce` - but probably not `relax`.
- I would also advocate for a standard axiom annotation on this classification "source: ontology-version-iri". With that, we can implement QC checks that simply look for subclass axioms that do not have a source and spit out a warning.

Once this is generally agreed, I will make sure its implemented and adopted.

**Comment by matentzn** [comment]
One practical question is which ontology the axiom 

`O2:A subClassOf R some O1:B`.

belongs to, or, more interestingly:

`R some O2:A subClassOf O1:B`

if its only inferred.

**Comment by matentzn** [comment]
Outcome from last meeting regarding base-files:

1. we will not replace base with base-plus files
1. no one likes the name base plus
1. we need to take extra care with reciprocals between certain ontologies such as CL and Uberon when defining base plus
1. we need to be careful with which inferences with shared internal/external signature go into which ontology (see comment above)
1. We need to decide how to create base: using a removal based approach (full-down) or an addition based approach (base-up). Chris wants downstream users to (be able to) do this themselves - so we should carefully document the procedure. My current feeling is `full-down` is probably easier to realise, but it will bring us into "what is an internal axiom" land again - while external axioms are not exhaustively tagged.
1. We will in any case [tag imported axioms](https://github.com/INCATools/ontology-development-kit/issues/457) from now on.
1. Eventually we need to work with OLS etc to think about how to best display base-plus.. (@matentzn is sceptical, he believes that ont-full.owl should be used by browsers, using existential graph modules instead of SLME in the release).

**Comment by matentzn** [comment]
Note that any given ontology can have multiple base namespaces, and even adopt individual terms (OBI-CHMO). We need to ensure that a reductionist approach covers this (speaks for the [flagging imported axioms](#457 )).

**Comment by matentzn** [comment]
- in discussion with @jamesaoverton: 
- "I would probably prefer a build-up approach for base, rather than reduction, seems safer (intuition rather than experience)."
- check gizmos extract for high efficiency, configurable imports
- when using a tagging based approach, think about axioms like declarations - should they be tagged
- think about axiom annotations (internal axiom annotations on external axioms)
- think about named graphs - problem owl API does not support this - but we could use other tooling to manage that. Maybe its an easier way to explain this.
- gizmos extract may be an option for implementing the existential graph module - but there is no concrete work done yet towards that end. subjects are only IRIs at the moment - needs to be extended. @jamesaoverton is using gizmos extract for PRO. some stuff is in the pipeline but maybe not immediately urgent.

adding more notes later

**Comment by matentzn** [comment]
Re naming: My problem with the "linked" name/descriptor is that the adjective is not an appropriate differentiator over the "full" release, or even the "base" release. We also do not really have an appropriate notion of "source" to differentiate from, but lets say for a moment that our current notion of "base" + "imports" constitute the source, then the module type we are trying to describe here comes with the following two properties:
- no external axioms are included (core, base, essence, etc)
- the internal axioms are fully materialised (reason, materialise, relax, reduce), i.e. "inferred", "materialised" etc, all of which would be meaningless to most users.

My suggestions for now are:
- kernel
- core module
- base-linked
- root module (in the sense of "to derive from")
- source module

**Comment by cmungall** [comment]
> Eventually we need to work with OLS etc to think about how to best display base-plus.. (@matentzn is sceptical, he believes that ont-full.owl should be used by browsers, using existential graph modules instead of SLME in the release).

Agreed about EG, but I just think the whole idea of distributing a chunk of another ontology in your release was a terrible idea, and is only going to get worse as more ontologies become stale

E.g https://www.ebi.ac.uk/ols/ontologies/ido/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0051704&viewMode=All&siblings=false

![image](https://user-images.githubusercontent.com/50745/133360270-41fc4abd-8566-4259-bd81-612e39559faf.png)

This hasn't been refreshed since 2017-11-03. This part of GO has been totally refactored since then. IDO is still marked active in OBO. There is nothing for an OLS user to indicate that they are in the wrong place.

NCRO is marked as active in OBO, yet it's GO import has not been refreshed since 2015

It's full of classes that have been obsoleted

https://www.ebi.ac.uk/ols/ontologies/ncro/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0044444

![image](https://user-images.githubusercontent.com/50745/133360745-53c83b19-a53b-44c9-b583-747229177379.png)

We need to start treating ontologies more like software

name:

> kernel

hmm, sounds too geeky, but it is descriptive

> core module

totally overloaded, otherwise this would be perfect

> base-linked

ok but one word better than two

> root module (in the sense of "to derive from")

perhaps

> source module

Too much like source code = edit module

**Comment by matentzn** [comment]
I agree the stale import in term browser issue is a big problem.. Just not one I would like to solve! I guess the way you phrase the issue, term browsers would work more like KG-OBO where all ontologies are named graphs (that could be reflected by the URL) but once you move to a term in a different space (say an UBERON term in a CL axiom), the browser switches the context to that (UBERON). In that case, you would want term browsers to only consume blink module (base-link = blink until we find a better word). 

However, I expect a lot of resistance here.. The changes to OLS and other tools may really be significant to support something like this, and also ontology developers, especially those of application ontologies, may not like that they don't have a bit of control over the shape of external terms.. Unless this proposal gets actual grant money, I don't see it happening. I have more hope for training the community to release more regularly, and OLS implementing a warning that "This entity seems to be from GO, would you like to browser it in the GO context?" or some such.. Dont want to be a buzzkill, please correct me if I am wrong.

**Comment by matentzn** [comment]
Fixed by #810
