### ISSUE TITLE
Include soufflé?

### ISSUE THREAD

**Issue by balhoff** [INCATools/ontology-development-kit#459]
I've been finding [soufflé](https://souffle-lang.github.io/index.html) incredibly useful lately, and would like to incorporate it into some workflows (for Ubergraph and for GO). Would it be too specialized to include in the ODK docker image?

They have Ubuntu install instructions here: https://souffle-lang.github.io/install  Will that work for Apple M1?

**Comment by matentzn** [comment]
I dont see why not! Feel free to make a PR; this does not look too bad to me..

**Comment by gouttegd** [comment]
Soufflé has been added to `odkfull` as part of the overhaul of the build process in PR #475.

**Comment by balhoff** [comment]
Thanks so much @gouttegd!
