### ISSUE TITLE
Consider using multi-stage builds

### ISSUE THREAD

**Issue by gouttegd** [INCATools/ontology-development-kit#466]
[Multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/) are a method to install into a Docker image files that have been prepared inside another Docker image.

Among other things, it allows to build a program in a (temporary) Docker image and copy *only* the resulting program to another (final) image, leaving all the build-time dependencies (that are only required to build the program) out of the final image. It should therefore allow to considerably reduce the size of an image.

**Comment by matentzn** [comment]
That would be so awesome..

**Comment by gouttegd** [comment]
Done with #475.
