### ISSUE TITLE
change default behavior to not include all individuals in imports

### ISSUE THREAD

**Issue by ramonawalls** [INCATools/ontology-development-kit#469]
I just spent several hours troubleshooting trying to understand why my OBI import had so many more classes than what I expected. The reason was that when you set up a project with ODK and specify the imports, it create a Robot extract command with the option `--individuals include` which has the following behavior: "--individuals include: all individuals in the input ontology and their class types (default)"

From a makefile created moments ago using ODK:
```
imports/%_import.owl: mirror/%.owl imports/%_terms_combined.txt
	if [ $(IMP) = true ]; then $(ROBOT) query -i $< --update ../sparql/preprocess-module.ru \
		extract -T imports/$*_terms_combined.txt --force true --copy-ontology-annotations true --individuals include --method BOT \
		query --update ../sparql/inject-subset-declaration.ru --update ../sparql/postprocess-module.ru \
		annotate --ontology-iri $(ONTBASE)/$@ $(ANNOTATE_ONTOLOGY_VERSION) --output $@.tmp.owl && mv $@.tmp.owl $@; fi
```

I don't think this is the behavior that most people want, and the consequence is an ontology with a bunch of unwanted classes (see BiodiversityOntologies/bco#117). Even though I can work around it by using custom imports, I would prefer the default behavior to be `--individuals minimal`.

Is there a good argument for including all individuals and their related classes by default? I would also suggest changing the default behavior in ROBOT.

**Comment by matentzn** [comment]
Hey @ramonawalls 

We recently implemented this feature.
You can just add something like this to your odk-setup:
https://github.com/ufbmi/OMRSE/blob/master/src/ontology/omrse-odk.yaml#L43

and run `sh run.sh make update_repo` (twice if you haven't done it recently).

Let me know if that works for you!

**Comment by ramonawalls** [comment]
That is excellent, @matentzn . Thank you!

Is there documentation on all the options that can go into the odk yaml file?

**Comment by matentzn** [comment]
You wont like the answer.. We need better docs, but... https://github.com/INCATools/ontology-development-kit/blob/master/schema/project-schema.json

**Comment by ramonawalls** [comment]
As one of those strange folks who is perfectly happy to reach XML and JSON, I am quite content with that answer.
