### ISSUE TITLE
Recommended way to import RO terms?

### ISSUE THREAD

**Issue by bjonnh** [INCATools/ontology-development-kit#47]
What would be the recommended way to import RO terms? 

I tried to import http://purl.obolibrary.org/obo/RO_0002217

but it seems that none of  the ro submodules are imported. Should I go through them one by one and add them  manually? ( I would probably not need that many, but that also means that whenever RO updates, I would have to go through all of it again).

Is there a way to import all the imports of ro.owl at once and work from that?

**Comment by balhoff** [comment]
If you import `http://purl.obolibrary.org/obo/ro.owl` you will get the whole ontology.

**Comment by bjonnh** [comment]
Ok turns out that the owltools command is removing all of that from the file. Taking from the URL directly works. 
I used the default command in the Makefile: $(OWLTOOLS) $(OBO)/$*.owl --remove-annotation-assertions -l -s -d --remove-dangling-annotations  -o $@

I will just do a wget for the ro.owl rule in the Makefile, unless there is a better solution.

**Comment by balhoff** [comment]
You may be interested in some of the commands [ROBOT](http://robot.obolibrary.org) provides, such as `mirror` and `merge`, if you are not already using it.
