### ISSUE TITLE
efo, npo, sio imports not generated

### ISSUE THREAD

**Issue by citmejia** [INCATools/ontology-development-kit#48]
I have found some inconsistencies when I run make imports/efo_import.owl in my terminal and when it runs on travis. In my terminal no error message arises, but both efo_import.owl and mirror/efo.owl are generated without any classes. Here is a screenshot showing that no error occurrs.

![image](https://user-images.githubusercontent.com/33327131/39219405-e66873e4-47ef-11e8-816b-b71a3284f290.png)

When it runs on travis, it raised an error that says that no branch or lower terms files were specified. However, I ran the extract command outside the Makefile with a local download of efo.owl with the same upper and lower terms files and it works. 

Here is a screenshot of the travis error.

![image](https://user-images.githubusercontent.com/33327131/39203040-58cc6562-47b9-11e8-952b-7fef87ce30d5.png)

When I toggle block comment one target at a time in the Makefile, this also occurred for NPO and SIO:

![image](https://user-images.githubusercontent.com/33327131/39218738-c494e36e-47eb-11e8-9320-0a5294dcfc15.png)

![image](https://user-images.githubusercontent.com/33327131/39218766-ed8b986c-47eb-11e8-89c9-19de8b148dd2.png)

![image](https://user-images.githubusercontent.com/33327131/39219343-6c782fca-47ef-11e8-8310-9efcf7623d05.png)

![image](https://user-images.githubusercontent.com/33327131/39219277-1c86cb16-47ef-11e8-9f3a-9cd145739a90.png)

**Comment by matentzn** [comment]
I will close this issue for now, if you need further help, please open a new one! :) Thanks.

**Comment by citmejia** [comment]
Ok, I will resume with the development of my ontology soon and probably
come back here.

Best regards,

Le ven. 2 nov. 2018 à 05:55, Nico Matentzoglu <notifications@github.com> a
écrit :

**Comment by srobb1** [comment]
Hello All,
Can we open this issue again? I see that since EFO is not at http://purl.obolibrary.org/obo/efo.owl it cannot be loaded with ODK. 
Is there someway to specify/configure the correct url to use for an ontology if it is not in the obo?

Thanks,
Sofia

**Comment by cmungall** [comment]
This will be solved when we switch to the more flexible template-driven 
model, currently in a PR

**Comment by srobb1** [comment]
@cmungall Thanks for the info. That sounds super helpful.

**Comment by matentzn** [comment]
This is now possible using the odk config file!
