### ISSUE TITLE
Complete DOSDP setup for a new project

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-development-kit#490]
This issue serves as both a coordination point for manually tuning existing repos as well as requirements for the complete final setup within odk

 - [X] directory layout. Assume mondo is standard?
 - [X] validation of templates
 - [x] validation of tables (structural)
 - [ ] validation of tables (dosdp)
 - [x] Makefile targets for dosdp-query
 - [ ] [github actions to keep /data/ folder in sync](https://github.com/INCATools/ontology-development-kit/issues/545)
 - [ ] [Generation of documentation](https://github.com/INCATools/ontology-development-kit/issues/389)

For the folder layout, this seems to be standard

 * src/patterns
     * dosdp-patterns
          * PATTERN.yaml <-- authored
     * data
          * PATTERN.tsv <-- from dosdp-tools query

Question: for an ontology that doesn't use mkdocs, where should generated md files go?

For generation of documentation, we currently have two codebases

 - Dazhi's python: in use in mondo
        - mondo: https://github.com/monarch-initiative/mondo/blob/master/src/scripts/patterns_create_docs.py
        - called by https://github.com/monarch-initiative/mondo/blob/master/.github/workflows/docs.yaml
        - cl: looks like it is used here too but I don't see how @shawntanzk 
 - dosdp-tools docs: in use for GO

GO is currently also generating md files and placing in the repo (we aren't using rtd/mkdocs):
https://github.com/geneontology/go-ontology/blob/master/docs/patterns/import_across_membrane.md

**Comment by cmungall** [comment]
This is informing work on

 - uberon: https://github.com/obophenotype/uberon/pull/2146

**Comment by shawntanzk** [comment]
> * - cl: looks like it is used here too but I don't see how @shawntanzk

cant say I know where the script to generate it lives, sorry about that, @matentzn do you know?

**Comment by cmungall** [comment]
@shawntanzk @matentzn maybe such a big deal if we just coalesce on dosdp-tools

```bash
✗ dosdp-tools docs --help
Command: docs
output Markdown documentation for patternsUsage: dosdp-tools docs
  --ontology  <file or URI>
        OWL ontology (provide labels, query axioms)
  --catalog  <file>
        A catalog XML file to use for resolving mapping ontology IRIs to URLs
  --template  <file>
        DOSDP file (YAML). If a local file is not found at the given path, the path will be attempted as a URL.
  --prefixes  <file>
        CURIE prefixes (YAML)
  --obo-prefixes  <true|false>
        Assume prefixes are OBO ontologies; predefine rdf, rdfs, owl, dc, dct, skos, obo, and oio
  --outfile  <file>
        Output file (OWL or TSV)
  --table-format  <tsv|csv>
        Tabular format: TSV (default) or CSV
  --batch-patterns  <names>
        List of patterns (without file extension) to process in batch (space separated, enclose list in quotes)
  --infile  <file>
        Input file (TSV or CSV)
  --data-location-prefix  <URL>
        URL prefix for linking to data files

```

**Comment by matentzn** [comment]
Very nice, yeah, I think we should give this the final push. I think a meeting is more effective then asynchronously debating it, so maybe we can raise this at the next "great pattern call" next week (8th November). -  @shawntanzk feel free to join us there!

**Comment by shawntanzk** [comment]
During next great pattern call - we should discuss this

**Comment by matentzn** [comment]
Consensus at the meeting was that the structure looks good as it is, and the mean thing to deal with is to get the match and document pipelines into ODK. I will spearhead this.

**Comment by matentzn** [comment]
I have created separate issues for the remaining action items. Will close this one now, as the rest is addressed.
