### ISSUE TITLE
ODK no longer includes scp

### ISSUE THREAD

**Issue by balhoff** [INCATools/ontology-development-kit#494]
Apparently ODK used to include `scp` and no longer does: https://github.com/geneontology/pipeline/issues/258

Is there any particular reason for this? Should we just add it to the list of installed packages?

**Comment by matentzn** [comment]
We had a huge spring clean, I will add it back.

**Comment by matentzn** [comment]
@gouttegd I am working on the makefiles now, do should we ad `openssh-client` to odkfull? in the list of "install tools provided by ubuntu"?

**Comment by gouttegd** [comment]
Sounds good.

**Comment by gouttegd** [comment]
This was fixed in December as part of #496. The change is present in ODK 1.2.31 and newer. Closing here.
