### ISSUE TITLE
Atomic (base) module proposal

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-development-kit#50]
@balhoff's proposal 
https://docs.google.com/document/d/1eCo5C3aZ9kjhBu98-24c2FHZIHEeFV7I2TJ4Vd6qw6k/edit#

We can merge this into the template:
https://github.com/balhoff/ultimate-ontology-makefile

**Comment by cmungall** [comment]
Some ontologies provide base, some do not.

For now we can hardcode the list in the generator script. If a dependency is passed, and the ontology is known to have a base, then we can switch to using this to build the import

eventually this could be pulled from the OBO central repo

**Comment by matentzn** [comment]
There is a PR for that, so closing for now.
