### ISSUE TITLE
missing my .travis.yml

### ISSUE THREAD

**Issue by srobb1** [INCATools/ontology-development-kit#51]
Hello. Just a question.

I do not have a .travis.yml file in the root of my ontology repo that I initialized using the ontology-starter-kit a while ago. Is this the best version to add: https://github.com/INCATools/ontology-starter-kit/blob/master/.travis.yml? Can I just add it as is to my repo?

Thank you,
Sofia

**Comment by cmungall** [comment]
We're now trying to include migration notes with each release: 

https://github.com/INCATools/ontology-development-kit/releases/tag/v1.1.2
https://github.com/INCATools/ontology-development-kit/releases/tag/v1.1.1

but these don't go back to when you started, so it's a bit more ad-hoc.

In general, you should be able to take the files from the template folder, copy them and adapt them (changing the FOOBARs to your repo). OR you can do a fresh run of the seed script, and copy individual files across. This has the advantage of having had the template values filled in. Of course, if you have made your own local adjustments then you will have to be careful about overwriting.

**Comment by cmungall** [comment]
Oh, you definitely should not use https://github.com/INCATools/ontology-development-kit/blob/master/.travis.yml

This is the travis for this repo, it tests generation of projects, not projects themselves

This is the one that gets used to make the version that ends up in the repo
https://github.com/INCATools/ontology-development-kit/blob/master/template/.travis.yml

(sorry sometimes it gets a bit inception in this repo)
