### ISSUE TITLE
Documentation for managing ontologies with merged/base file imports 

### ISSUE THREAD

**Issue by shawntanzk** [INCATools/ontology-development-kit#514]
We need to write up documentation on how to manage ontologies that have switched to base file imports such as CL and PATO. 
Suggest that we edit UpdateImports section in https://github.com/INCATools/ontology-development-kit/edit/master/template/_dynamic_files.jinja2 to include a subsection on base file imports. 

We further need documentation on how to switch ontologies to base file imports but that can come later

**Comment by shawntanzk** [comment]
Related to https://github.com/obophenotype/cell-ontology/issues/1404

**Comment by matentzn** [comment]
I would not recommend this strategy anymore, especially for people that are able to run odk: the main strategy should be to add the id, as we previously did to the `imports/cl_terms.txt` file, then refresh the import. However, documenting as you have done is good, as editors with no ability to run odk may need to do it using the Protege-based strategy.

**Comment by shawntanzk** [comment]
oh I thought that the individual import files are not used anymore - so basically if we add it to terms then refresh merged it will work?

**Comment by matentzn** [comment]
Yes, if everything goes as planned, this here:
https://github.com/INCATools/ontology-development-kit/blob/master/template/src/ontology/Makefile.jinja2#L273

Should merge all the term files into one big heap and then use that to extract the module.

**Comment by shawntanzk** [comment]
Thanks @matentzn - I'll update the docs accordingly
