### ISSUE TITLE
Deploy docs is failing

### ISSUE THREAD

**Issue by shawntanzk** [INCATools/ontology-development-kit#518]
see https://github.com/INCATools/ontology-development-kit/runs/4816849013?check_suite_focus=true

**Comment by shawntanzk** [comment]
@gouttegd  do you mind helping take a look at this when you have time please? thanks heaps :)

**Comment by gouttegd** [comment]
This is the same problem as in #506. Should be fixed once #517 is tested and merged. Closing as duplicate.
