### ISSUE TITLE
generate non-fake seed terms.txt files

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-development-kit#52]
currently these are junk

```
http://purl.obolibrary.org/obo/XXX_0000001 ## Optional Label
http://purl.obolibrary.org/obo/BFO_0000050 ## part of
http://purl.obolibrary.org/obo/CHEBI_24431 ## chemical entity
http://purl.obolibrary.org/obo/UBERON_0002048 ## lung
http://purl.obolibrary.org/obo/CL_0000540 ## neuron
http://purl.obolibrary.org/obo/GO_0008150 ## biological_process
```

this causes some versions of robot to trip.

we should have real examples. This can't be static as it depends on user params. osk should do a query for first ~5 in any ontology

**Comment by cmungall** [comment]
`SELECT ?x WHERE {GRAPH ?v1 {?x <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?v0} . FILTER (?v1 = URI(concat("http://purl.obolibrary.org/obo/merged/", ucase("go")))) . ?x <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2002/07/owl#Class>}`

**Comment by matentzn** [comment]
I dont think this is important anymore, as ROBOT allows extraction with empty seed. If you disagree, please re-open.
