### ISSUE TITLE
Add SPARQL test for taxon annotation property range

### ISSUE THREAD

**Issue by dosumis** [INCATools/ontology-development-kit#520]
never_in_taxon (RO_0002161) and present_in_taxon (RO_0002175) are annotation properties that require a taxon (NCBI taxon class) as a value.  Ideally this range would be specified in RO, but limitations on specifying range for annotationProperties means there is no obvious way to do this.  To compensate, we need a SPARQL check.  

I think this should have two components:
1. test that the value is an IRI
2. cast to string and test that it begins with 'http://purl.obolibrary.org/obo/NCBITaxon_'

**Comment by matentzn** [comment]
For now, lets add this to Uberon - There are hundreds of SPARQL checks that we use across our projects, and we only want the very most general ones in ODK. Think of ODK SPARQL QC is those queries that are just an inch outside the criterion for ROBOT report.. Eventually, we want to find a better way to re-use and share SPARQL QC across repos, but for now, we can continue as we were I think.

**Comment by matentzn** [comment]
Ok, I changed my mind on this. Lets have two checks:

1. That we can extend over time that checks the range of certain APs to be IRIs.
2. One that checks taxon APs have a range that starts with the NCBITaxon URI prefix

@anitacaron after you made sure both tests work for Uberon, you can make a PR here and add them to the ODK template/src/sparql directory as well.

I would also like to be more selective about the SPARQL checks checked into a given repo, will make a new ticket for that.
