### ISSUE TITLE
Better diff options?

### ISSUE THREAD

**Issue by gouttegd** [INCATools/ontology-development-kit#524]
The ODK could/should provide better options to visualise diffs between two versions of an ontology, either locally (on the editor’s machine) or on GitHub.

This is especially important for ontologies that don’t use the diff-friendly OBO format.

Possible paths to explore:

* Provide instructions on how to setup a custom diff generator for Git, based on `robot diff` (would only benefit the two people that still uses Git in a terminal instead of GitHub Desktop, though);
* Have a GitHub Action that runs on a PR and uses `robot diff --format markdown` to generate a comment showing the changes introduced by the PR, that the PR reviewer could then use instead of the GitHub-generated web diff.
* Add a new rule to the ODK-generated Makefile to automatically generate a HTML rendering of a diff (using `robot diff --format html`), that the editors could then open locally in their browser.
* Other options?

Related issue: #480 , where the possibility of generating a diff on the _reasoned_ version of the ontology is discussed.

**Comment by shawntanzk** [comment]
just adding a small comment to make sure that `--labels True` would be there - it would be the biggest enhancement heh

**Comment by matentzn** [comment]
@ubyndr assign to yourself once you have accepted ODK invite

**Comment by cmungall** [comment]
of relevance: https://cmungall.github.io/knowledge-graph-change-language/home/

**Comment by matentzn** [comment]
We will move to KGCL later when it is ready - for now, @ubyndr is cooking up a robot diff process.

Ideally we should be able to make the action configurable to show consequences for all sorts of targets (subsets etc), but for now, lets just do a ROBOT merge reason on master, on branch, diff -f markdown, make comment.

**Comment by anitacaron** [comment]
Superceded by #547
