### ISSUE TITLE
DOSDP = True should automatically enable CI testing

### ISSUE THREAD

**Issue by shawntanzk** [INCATools/ontology-development-kit#534]
Currently CI checks for DOSDP need to be set in the config manually after using DOSDP = True
This should ideally be automated if possible

**Comment by gouttegd** [comment]
This is already done in master (commit 7978ed84039d18f9af466e44b02f74f9b9c69e34, merged with PR #515). But we have not done an ODK release since then, so this is not visible from Uberon (or any other ODK-managed ontology).
