### ISSUE TITLE
Adding check to look for IRIs in textual annotations

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#536]
When running DOSDP or similar pipeline, it can happen that DOSDP tools does not have access to a term to autogenerate its metadata, resulting in something like this:

```
AnnotationAssertion(<http://purl.obolibrary.org/obo/IAO_0000115> <http://purl.obolibrary.org/obo/CATO_0000001> "A coat of hair with a http://purl.obolibrary.org/obo/PATO_0000333 colour pattern."^^xsd:string)
```

We need a check that:

- [x] Is added to custom_sparql_queries
- [x] Looks for `http[s]?[:]` in rdfs:label and IAO:0000115
- [x] Is restricted to the looking at entities from the namespace of the ontology (see `^^^ src/sparql/{{ project.id }}_terms.sparql` in dynamic jinja2

**Comment by anitacaron** [comment]
Maybe need to restrict rdfs:label/IAO:0000115 value to OBO IRI?

For example, in UBERON, there're 24 cases that some link is present https://api.triplydb.com/s/8OP8K9sy9

**Comment by matentzn** [comment]
I think these are legitimate. Lets constraint the test just to labels!

**Comment by anitacaron** [comment]
Yes, but I think your example will never appear in the checks. Instead of checking only for `HTTP`, why not check for OBO URI?

**Comment by anitacaron** [comment]
Because you said to only check `rdfs:label` and in your example is using `description` where the chance to have `HTTP` is higher.

**Comment by matentzn** [comment]
Yeah, but the error i am trying to catch is the DOSDP error where someone compiles a DOSDP template and accidentally does not import a term first.. Were you at the OBO academy training on Tuesday?

**Comment by anitacaron** [comment]
yes, that's why I'm suggesting to have a more specific filter, instead of just `http` use `http://purl.obolibrary.org/`

**Comment by matentzn** [comment]
I think having a label containing the string http:// or https:// sounds so outlandish that we should warn about it! Not all uses of DOSDP require OBO purls!
