### ISSUE TITLE
Add tmp/{oid}-edit.owl as a goal to all pipeline to allow arbitrary preprocessing 

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#544]
Right now, running ontology preprocessing is cumbersome, in fact, not really possible: we kinda have to apply any changes like taxon constraint materialisation and others in complex custom chains, and even use tricks like SRC="tmp/edit.owl" in make, see FBbt pipeline. I think we should simply add a single preprocessing step:

```
SRCBUILD=tmp/$(ONT)-edit.owl
$(SRCBUILD): $(SRC)
      cp $< $@
```

and replace all references in the Makefile from $(SRC) to $(SRCBUILD). So by default, no global preprocessing is applied. If the user wants to apply global preprocessing, they simply overwrite `$(SRCBUILD)`.

Feedback to this idea welcome.

**Comment by matentzn** [comment]
Explainer: customised preprocessing is currently not possible at all because there is no _common_ goal on which all release artefacts depend other than $(SRC).

**Comment by anitacaron** [comment]
@matentzn reminder

**Comment by shawntanzk** [comment]
in Dev version already https://github.com/INCATools/ontology-development-kit/pull/639, will be released in next version.

**Comment by matentzn** [comment]
Re-opening as there is a serious bug: --catalog does not work correctly.

**Comment by matentzn** [comment]
Bug was not real. Imagined.
