### ISSUE TITLE
Extend OSK target repo structure to incorporate design pattern files and related infrastructure

### ISSUE THREAD

**Issue by dosumis** [INCATools/ontology-development-kit#56]
Draft repo structure:

\# release files live at the top level
Bar.owl 
Bar-simple.owl
.travis.yaml 
src/
.    patterns/ # DOSDPs used to actively generate ontology live here.
.    .    Dosdp1.yaml
.    .    Dosdp2.yaml
.    .    Dosdp1.tsv
.    .    Dosdp2.tsv
.    .    imports/
.    .    .    fu_imports.owl # SLIME generated modules to support
.    .      pattern_ontology.owl  # Ontology of patterns - default fillers. FOR REF ONLY Imports modules 
              from imports/ in this dir
.    .   definition_ontology.owl #  
.    ontology/
.    .    Makefile # continues to live in ontology directory.  Make commands from here drive all ODK processes.
.    .    README.md  # This should be updated with commands to run pattern generation etc.
.    .    bar-edit.owl  # imports definition_ontology.owl + modules in imports dir
.    .    imports/
.    .    .    fu_imports.owl #

**Comment by matentzn** [comment]
Done
