### ISSUE TITLE
sparql_test: make ontology configurable

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#565]
Should be able to use base/full instead of src.

**Comment by anitacaron** [comment]
Can you give more detail? Do you think adding a parameter in the top level, like `sparql_test_ontology: base/full/edit`?

**Comment by matentzn** [comment]
I was thinking something along the lines of this: https://github.com/pato-ontology/pato/blob/master/src/ontology/pato-odk.yaml#L67

So if I understand your suggestion, then yes, that is what I was thinking. sparql_test_ontology defaults to what it is right now (I think edit_preprocessed). `edit` should be mean the `edit preprocessed" file.

**Comment by anitacaron** [comment]
So do you mean to add a list or only one value?

**Comment by matentzn** [comment]
Maybe list, so it mirrors the functionality of report?
