### ISSUE TITLE
New verison of dosdp pypi released

### ISSUE THREAD

**Issue by hkir-dev** [INCATools/ontology-development-kit#566]
New version of the DOS-DP pypi is released (dosdp 0.1.10.dev1) with some bug fixes: https://pypi.org/project/dosdp/

Can we use the newest dsodp version in the upcoming ODK release?

**Comment by gouttegd** [comment]
I believe we're already using 0.1.10.dev1. Since it is on PyPI it must have been automatically picked up with the base system upgrade (all Python packages were also upgraded in the process).

Check the constraints.txt file.

**Comment by gouttegd** [comment]
Checked. We are indeed already using the latest version:

> dosdp==0.1.10.dev1
