### ISSUE TITLE
Update Makefile to support pattern-based ontology development with DOSDP / DOSDP-tools

### ISSUE THREAD

**Issue by dosumis** [INCATools/ontology-development-kit#57]
Spec:

`make pattern_imports`:  Use dictionaries in pattern YAML to generate OWL import seeds.  Use these seeds with ROBOT extract commands to generate import files.  

Potential problem - How can we reliably specify the ontologies to import from?  Should we reply on parsing curies?

`make pattern_ontology`:  DOSDP-tools command TBA +   **make pattern_imports**

`make definitions.owl`* This needs to wrap generation of all patterns + corresponding TSVs -> a single OWL file.  
@balhoff Will dosdp-tools wrap this, or should the Makefile run a set of individual build jobs (one for each pattern) & merge the results using Robot?

`make patterns`: Wraps all of the above steps;  Runs standard travis checks on the edit file + imports.

**Comment by dosumis** [comment]
Potentially useful for reference: https://github.com/balhoff/ultimate-ontology-makefile/blob/master/Makefile

**Comment by matentzn** [comment]
Closing for now, as this works, but it needs improvement.
