### ISSUE TITLE
run.sh parameters should be configurable at runtime

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#580]
Right now this is written by the config, but a parameter would streamline development a bit, eg:

```
MEMORY=15GB
```

**Comment by gouttegd** [comment]
If we go that route I’d recommend using variable names that are more explicitly tied to the ODK (maybe simply by prefixing `ODK_`, as in `ODK_MEMORY` — we already have `ODK_DEBUG`, so it’d make sense to continue like that).

This would allow some users to set those variables once and for all in their environments (`~/.bash_profile` or whatever file is suitable for their system and their shell) without worrying that the variables may be interpreted by multiple programs and therefore have unintended effects.

**Comment by matentzn** [comment]
Yes!

**Comment by matentzn** [comment]
Pretty sure we fixed this?

**Comment by gouttegd** [comment]
What can currently be configured at runtime when calling the `run.sh` script:

* any Java parameters (variable `ODK_JAVA_OPTS`);
* the image and/or tag to use (variables `ODK_IMAGE` and `ODK_TAG`);
* whether to display elapsed time and memory consumption at the end (variable `ODK_DEBUG`);
* extra directories to bind inside the container (variable `ODK_BINDS`).

Was there something else you wanted to be able to configure?

**Comment by matentzn** [comment]
This is by far great enough for this issue to deserve a good retirement. Thanks!
