### ISSUE TITLE
Upgrade from 1.2.25 to 1.3 error

### ISSUE THREAD

**Issue by DanBerrios** [INCATools/ontology-development-kit#581]
Hi guys. I'm getting this error trying to "run make update_repo" (Windows Docker) ...any idea why? :

```
C:\Users\Dan\Documents\GitHub\RBO\src\ontology>docker run --env ROBOT_JAVA_ARGS=-Xmx12G -v C:\Users\Dan\Documents\GitHub\RBO\src\ontology\..\..\:/work -w /work/src/ontology --rm -ti --memory=12g obolibrary/odkfull make update_repo
sh ../scripts/update_repo.sh
This (experimental) update script will create a new repo according to your config file. It will:
(1) overwrite your repositories Makefile, ODK sparql queries (your custom queries wont be touched) and docker wrapper (run.sh).
(2) and add missing files, if any.
: not foundupdate_repo.sh: 4:
../scripts/update_repo.sh: 5: set: Illegal option -
make: *** [Makefile:517: update_repo] Error 2
```

**Comment by matentzn** [comment]
Did you try running this twice?

**Comment by gouttegd** [comment]
This looks like it could be caused by DOS-style line endings in the `update_repo.sh` script (`\r\n` instead of `\n` only).

The Bourne shell would not be expecting the extra `\r` characters, which would cause both the error in line 4 (which the shell is reading as containing a single command `\r`, which of course it cannot find) and the error in line 5 (read as `set -e\r`, which is invalid as `\r` is indeed not a legal option for `set`).

Now _why_ would there be DOS-style line endings in that script is beyond me, but I have no experience running the ODK (or any other Docker containers for that matter) under Windows…

**Comment by matentzn** [comment]
@gouttegd thank you very much, great thinking.. Would have never thought of that!

@DanBerrios did you open and save `update_repo.sh` on your windows machine?

**Comment by DanBerrios** [comment]
@matentzn No, I didn't..but Git probably changed the file EOLs automatically as I am on a Windows machine and it does that as a default behavior. I checked the file and manually reset the line endings to \n and then it ran correctly (well I had to run it twice, as expected).  You might want to put that note into the docs for other Windows ODK users....

**Comment by DanBerrios** [comment]
Trying to test my repo after the succesful update, I see this error....any idea?:

```
C:\Users\Dan\Documents\GitHub\RBO\src\ontology>docker run --env ROBOT_JAVA_ARGS=-Xmx12G -v C:\Users\Dan\Documents\GitHub\RBO\src\ontology\..\..\:/work -w /work/src/ontology --rm -ti --memory=12g obolibrary/odkfull make test
echo "ODK Makefile version: v1.2.32 (this is the version of the ODK with which this Makefile was generated, not the version of the ODK you are running)" &&\
echo "ROBOT version (ODK): " && robot --catalog catalog-v001.xml --version
ODK Makefile version: v1.2.32 (this is the version of the ODK with which this Makefile was generated, not the version of the ODK you are running)
ROBOT version (ODK):
ROBOT version 1.8.3
robot --catalog catalog-v001.xml remove --input rbo-edit.owl --select imports --trim false \
        merge   -i components/all_templates.owl -o tmp/merged-rbo-edit.owl
robot --catalog catalog-v001.xml report -i tmp/merged-rbo-edit.owl -l true  --fail-on None --print 5 -o reports/rbo-edit.owl-obo-report.tsv
Violations: 400
-----------------
ERROR:      14
WARN:       386
INFO:       0

First 5 violations:
ERROR   label_whitespace        Social science and humanities study     rdfs:label      Social science and humanities study
ERROR   label_whitespace        Meteorology study       rdfs:label      Meteorology study
ERROR   deprecated_boolean_datatype     Cobalt-57 gamma radiation       owl:deprecated  radionuclide
ERROR   deprecated_boolean_datatype     biological process      owl:deprecated  owl:deprecated
ERROR   deprecated_boolean_datatype     cellular process        owl:deprecated  owl:deprecated
make: *** No rule to make target 'reports/.owl-obo-report.tsv', needed by 'all_reports'.  Stop.
```

**Comment by DanBerrios** [comment]
@matentzn I was able to get past the error above by prepending the ontology var to the dependency name (as in $(ONT).owl-obo-report.tsv). Then I ran to into the OBO export error we had been seeing even before upgrading the ODK.  Once I deactivated the OBO exports in the Makefile, I could build without error.  Ruth Duerr has also reported the same obo export error with the SDDO ontology, so we can follow up that one separately.

**Comment by matentzn** [comment]
You have a small error in your config:

```
robot_report:
  custom_profile: false
  fail_on: null
  report_on:
  - edit
  - rbo.owl
  use_labels: true
```

(rbo.owl, not .owl).

Also, make sure you update ODK:

```
docker pull obolibrary/odkfull
```

Then:

```
sh run.sh make update_repo
```

Then try again. It will fail elsewhere:

![image](https://user-images.githubusercontent.com/7070631/161748478-5d734230-7b51-4108-86fb-eedd671fd427.png)


This is an ENVO axiom that needs to be dropped manually from the import I think.. I will help you with this!

**Comment by matentzn** [comment]
@DanBerrios Please reopen if you still have issues, happy to help sort them out.
