### ISSUE TITLE
Setting uribase in ontology-odk.yaml has no effect on generated ontology

### ISSUE THREAD

**Issue by henrietteharmse** [INCATools/ontology-development-kit#582]
Setting a `uribase: "https://myorganization.org/"` seems to have no effect. In specific the generated ontology still has 
`xml:base http://purl.obolibrary.org/obo....`. 

If there is some workaround for this issue, that will be helpful to know as well.

**Comment by StroemPhi** [comment]
I was having the same question.

**Comment by matentzn** [comment]
It seems we cant set the URI at inception time atm - I will look into it soon.

**Comment by matentzn** [comment]
Moved this to next milestone, but should be done relatively soon. Sorry about the wait.

**Comment by allysonlister** [comment]
Thank you! Just adding that I'm running into this for the new SWO build using the ODK too, as SWO has historically had an ebi.ac.uk-based IRI. Thanks for working on it!

**Comment by matentzn** [comment]
This will be in the next 1.3.2 release.
