### ISSUE TITLE
Add oaklib (libraries in path and runoak CLI) to ODK

### ISSUE THREAD

**Issue by kltm** [INCATools/ontology-development-kit#584]
This is a request to add OAK (ontology access kit) to the ODK.

https://github.com/INCATools/ontology-access-kit

Tagging @cmungall

**Comment by matentzn** [comment]
What is needed, just a PR on https://github.com/INCATools/ontology-development-kit/blob/master/requirements.txt.full?

**Comment by gouttegd** [comment]
It is [on PyPI](https://pypi.org/project/oaklib/) (despite what the README says) under the name `oaklib`, and it does not seem to have any non-Python dependencies, so yes, it shouldn’t require anything more than updating that file.

**Comment by matentzn** [comment]
Thank you @gouttegd :)

The tool does so many things, not sure if it has some undocumented dependencies, like `dot` or similar.

**Comment by gouttegd** [comment]
Argh, the `viz` command requires [obographviz](https://github.com/cmungall/obographviz) which requires Node.js!

(_Runs away in fear_)

**Comment by gouttegd** [comment]
Only for creating graph images, if I understand correctly?

But still, that may be useful and after all one point of the ODK is to provide the tools ontology editors/engineers might need, without asking them to deal with Python or Node packages.

I did a quick check, apparently adding Node.js, NPM, and the Node packages required by `obographviz` would add ~100 MB to the ODK. If there’s a need for OAK’s `viz` command, I’d be in favour of adding that to `odkfull`.
