### ISSUE TITLE
Please incorporate checks for the dateTime property 

### ISSUE THREAD

**Issue by bvarner-ebi** [INCATools/ontology-development-kit#587]
Context: https://github.com/obophenotype/uberon/pull/2379#discussion_r845999223

To ensure users enter **date property** values using 'dcterms:date', will you please incorporate a quality control step that confirms these are entered as 'dcterms:date' and not a URL?

For example:

WRONG: property_value: **http://purl.org/dc/elements/1.1/date** 2022-04-04T11:06:09Z xsd:dateTime
CORRECT: property_value: **dcterms:date ** 2022-04-04T11:06:09Z xsd:date

**Comment by shawntanzk** [comment]
I think there was an agreement in uberon call that we should in general use dcterms instead of dce - wonder if its worth having a blanket dcterms instead of dce check? I remember @anitacaron wrote a SPARQL query check for this, we can probably repurpose?

**Comment by matentzn** [comment]
We will do that, but we are proposing a motion to use `dcterms:` with `xsd:date` (`2022-04-18`) rather than `dateTime`.

**Comment by bvarner-ebi** [comment]
To confirm, should it be the following?

property_value: dcterm: 2022-04-04T11:06:09Z xsd:date

**Comment by matentzn** [comment]
@bvarner-ebi you can do that for now, but we do not know the answer yet. There is another proposal in now that wants to use:

```
property_value: dcterms:modified 2022-04-04T11:06:09Z xsd:date
```

and

```
property_value: dcterms:created 2022-04-04T11:06:09Z xsd:date
```

instead.

**Comment by bvarner-ebi** [comment]
OK, thank you. Is there a reference or could you provide an explanation on the impact these changes will make?

**Comment by shawntanzk** [comment]
> an explanation on the impact these changes will make?

Having both shows when the term was created, and when it was last modified. I think the logic is many times you want to find out when the term was last modified so you can trace changes back to a PR for example, which can be useful for fixing problems.

**Comment by matentzn** [comment]
do you mean positive or negative impact?

positive is
- using meaningful standard vocabulary
- using less error prone date strings rather than  complex dateTime

negative is
- people need to change their habits (costly)
- validation tools need to be introduced

I don't think date is a really risky one.. its probably the most straight forward of our current data standardisation issues..

@shawntanzk we really want to link issues to terms as well moving forward - this is super useful to just do it.. for everything. even multiple ones!

**Comment by bvarner-ebi** [comment]
> do you mean positive or negative impact?

Both... trying to wrap my head around why we are proposing changes and what the outcome would be. 

Once this change is solidified, please confirm and I can update the OBOOK documentation.

**Comment by bvarner-ebi** [comment]
> > an explanation on the impact these changes will make?
> 
> Having both shows when the term was created, and when it was last modified. I think the logic is many times you want to find out when the term was last modified so you can trace changes back to a PR for example, which can be useful for fixing problems.

I actually meant the difference between dcterms:date and the URL.

**Comment by matentzn** [comment]
You are always implicitly using the URL.. `dcterms:date` is a shortcut used in RDF to mean the URL!

**Comment by shawntanzk** [comment]
> I actually meant the difference between dcterms:date and the URL.

OH! lol, neatness - dcterms: expands out the URL http://purl.org/dc/terms/ I think
Something like how we use CL:0000000 to represent http://purl.obolibrary.org/obo/CL_0000000

**Comment by bvarner-ebi** [comment]
Got it, thank you both! Didn't realise it was just serving as a prefix.

Should this be the screenshot in OBOOK:
![Screenshot 2022-04-25 at 16 56 52](https://user-images.githubusercontent.com/95643797/165173848-ec934eb7-d522-4530-b5a6-aa7d21f27d91.png)

Any changes to the contributor property?

**Comment by matentzn** [comment]
@bvarner-ebi if you feel your questions are addressed can you close this ticket?

**Comment by bvarner-ebi** [comment]
@matentzn, can you point me to the PR where this check was added to the QC checks?

**Comment by matentzn** [comment]
Oh sorry, I was not only looking at the last 4 comments, you are right, that has not happened yet:

- [ ] add (optional) check to ensure range of dct:date, dct:issued, dct:created is xsd:date with "2022-02-04"

**Comment by bvarner-ebi** [comment]
Would it help to rename the annotation properties in Protégé so users know to not use the undesired ones or delete them altogether? For example, 'dc:date' --> 'dc:date - OBSOLETE'.

**Comment by matentzn** [comment]
It is very much against policy to rename entities (by the properties or classes) from upstream sources.. The correct solution is to add QC to simply disallow the presence of a property. ODK can then filter them out from the imports.

**Comment by shawntanzk** [comment]
seems the check is already there: 
https://github.com/obophenotype/uberon/blob/8457cbd0a47f7a0452caeba4c64cae124267fd2d/src/sparql/illegal-annotation-property-violation.sparql#L54 

>   add (optional) check to ensure range of dct:date, dct:issued, dct:created is xsd:date with "2022-02-04"

Happy to add this, but currently (at least according to ubergraph), nothing is in xsd:date (mostly in xsd:string or xsd:dateTime

```SPARQL
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>

# selecting only unique instances of the three variables
SELECT DISTINCT ?term ?property ?value WHERE
{
  # order of the variables in the triple
    ?term ?property ?value .
    # the variable property is an annotation property
    ?property a owl:AnnotationProperty .
  FILTER (?property IN (dct:date, dct:issued, dct:created))
FILTER (datatype(?value) = xsd:date)
}
LIMIT 10
``` 
Alternative is to use something like
```
  FILTER (regex(str(?value), '\\d{4}-\\d\\d-\\d\\d'))
```
allows both date and dateTime as string but can be either

**Comment by shawntanzk** [comment]
Fixed: 

```SPARQL
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>

# selecting only unique instances of the three variables
SELECT DISTINCT ?term ?property ?value WHERE
{
  VALUES ?property {dct:date dct:issued dct:created}
  # order of the variables in the triple
    ?term ?property ?value .
  FILTER (datatype(?value) != xsd:date || !regex(str(?value), '^\\d{4}-\\d\\d-\\d\\d$'))
}
```
