### ISSUE TITLE
bump oaklib version 

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-development-kit#591]
I tried to bump up to 0.1.12 in #590 this seemed to cause issues..

**Comment by gouttegd** [comment]
The problem is that since version 0.1.4, `oaklib` requires Python 3.9. The ODK is currently built on Ubuntu 20.04, which only provides Python 3.8.

It might be time to consider moving the ODK to Ubuntu 22.04…

**Comment by cmungall** [comment]
We could look into 3.8 support it may not be hard… but otoh there may be
other advantages to 22.04? Cc @kltm

**Comment by gouttegd** [comment]
> but otoh there may be other advantages to 22.04?

Even just having a newer Python than 3.8 is already a good reason to upgrade IMHO. I am testing the upgrade right now.
