### ISSUE TITLE
gh should get an login step with token

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#599]
```
gh auth login --with-token < mytoken.txt
```

See 

https://cli.github.com/manual/gh_auth_login

Else we cant use the shiny new deploy release step

**Comment by matentzn** [comment]
Here is the [PR](https://github.com/INCATools/ontology-development-kit/pull/618/files) to make a start, but should be aligned with:

https://github.com/monarch-initiative/mondo-ingest/blob/main/src/ontology/mondo-ingest.Makefile#L283

Which works well in production.

**Comment by gouttegd** [comment]
So if the user already has a GitHub token (which she can get here: https://github.com/settings/tokens), all we have to do to allow using GH from within the ODK is to pass a `GH_TOKEN` environment variable with said token.

So I’ll update the `run.sh` script to:

* check if `GH_TOKEN` is already defined in the environment, and use it if that’s the case (that would also cover the case where the token is stored in the `run.sh.conf` file, for people who would want to do that – hopefully not the same people as those who commit the `run.sh.conf` file :p );
* if no `GH_TOKEN` in the environment, look for a `token` file in the `.github` directory at the top of the repository;
* if still no token, look for a `token` file in `$XDG_CONFIG_HOME/ontology-development-kit/github` (on well-educated, Freedesktop-compliant systems) or in `$HOME/Library/Application Support/ontology-development-kit/github` (on mac OS).

Once (if) we have a token, we’ll convey it into the container using `docker run`’s `--env-file` option (to avoid passing the token on the command line, where it would end up in the shell history).
