### ISSUE TITLE
Adding psycopg2 to the ODK

### ISSUE THREAD

**Issue by gouttegd** [INCATools/ontology-development-kit#600]
I’d like to request that [psycopg2](https://www.psycopg.org/) (a Python library to communicate with PostgreSQL servers) be added to the ODK.

Some parts of FBbt’s release pipeline involve querying our Chado database. In order to do that, we are currently installing _psycopg2_ from within our custom `fbbt.Makefile`. Not a big deal, but it’d be nice if this could already be available in the ODK.

This may be stretching the scope of the ODK (_psycopg2_ has nothing to with ontology development), but on the other hand this would only add barely 1~MB to the final image – we’ve added much larger pieces of software to the ODK before.

**Comment by matentzn** [comment]
Are you sure its not already there? I think that James Overtons tooling need this.. In any case, 100%, by all means add it.
