### ISSUE TITLE
Upgrading the base system?

### ISSUE THREAD

**Issue by gouttegd** [INCATools/ontology-development-kit#601]
The ODK is currently built on top on Ubuntu 20.04, which is more than 2 years old.

As a result, we’re going to see the first problems caused by the age of the underlying system, such as #591 (`oaklib` being stuck to version 0.1.2 because more recent versions require Python 3.9 while we only have Python 3.8).

We should consider moving to a more recent Ubuntu base (22.04?).

**Comment by matentzn** [comment]
oh, oh... YES we should do that.. If you make a PR, I will run tests. The most recent ubuntu stable could work, and we will work our way backwards if we have issues
