### ISSUE TITLE
CHEBI and RO mirror issue 

### ISSUE THREAD

**Issue by LilyAndres** [INCATools/ontology-development-kit#623]
Thanks @matentzn 
When running the import commands:

`./run.sh make all_imports` or `./run.sh make imports/chebi_import.owl` from the [Intermediate CDNO Compile Instructions](https://github.com/Southern-Cross-Plant-Science/cdno/wiki/Intermediate-CDNO-Compile-Instructions)

I get the following errors: 

```
ontology git:(issue-88) ./run.sh make all_imports
make: /bin/sh: Operation not permitted
make: *** [Makefile:269: mirror/ro.owl] Error 127
```

```
./run.sh make imports/chebi_import.owl
owltools  --no-debug mirror/chebi-local.owl --log-debug -o mirror/chebi.owl
make: owltools: Operation not permitted
make: *** [Makefile:377: mirror/chebi.owl] Error 127
```

The MakeFile module for RO looks like this:

```
mirror/ro.owl: mirror/ro.trigger
	@if [ $(MIR) = true ] && [ $(IMP) = true ]; then $(ROBOT) convert -I $(URIBASE)/ro.owl -o $@.tmp.owl && mv $@.tmp.owl $@; fi
.PRECIOUS: mirror/%.owl 
```

The MakeFile module for CHEBI looks like this:

```
mirror/chebi-local.owl:
	wget --no-check-certificate $(URIBASE)/chebi.owl -O $@ && touch $@
mirror/chebi.owl: mirror/chebi-local.owl
	owltools  --no-debug $< --log-debug -o $@
.PRECIOUS: mirror/%.ow
```

This is the pull request I'm working on
https://github.com/Southern-Cross-Plant-Science/cdno/pull/91

I hope I'm not missing something, this used to run ok before, thanks.

**Comment by matentzn** [comment]
Are you in the src/ontology directory?

I assume you are on a Mac or Linux machine.

Try sh run.sh instead of ./run.sh. 

Alternatively you have to first make run.sh executable: chmod +x run.sh

Let me know how it goes

**Comment by LilyAndres** [comment]
Thanks @matentzn, yes I am in src/ontology dir in a Mac

I made ./run.sh executable but I'm still getting the same errors:

```
➜  ontology git:(issue-88) sh run.sh make imports/chebi_import.owl
owltools  --no-debug mirror/chebi-local.owl --log-debug -o mirror/chebi.owl
make: owltools: Operation not permitted
make: *** [Makefile:377: mirror/chebi.owl] Error 127
➜  ontology git:(issue-88) sh run.sh make all_imports             
make: /bin/sh: Operation not permitted
make: *** [Makefile:269: mirror/ro.owl] Error 127
```

:(

**Comment by matentzn** [comment]
Do you have a src/ontology/mirror directory?

**Comment by LilyAndres** [comment]
Yes, I do

`/Users/Lily/Documents/Github/cdno_minerals/cdno/src/ontology/mirror`

**Comment by matentzn** [comment]
Try updating your ODK: docker pull obolibrary/odkfull

We will get to the bottom of this :)

**Comment by LilyAndres** [comment]
Thanks. 

Ok, I have updated the ODK, I ran the commands again `sh run.sh make all_imports` and `./run.sh make all_imports`
And same error.

**Comment by matentzn** [comment]
So I tried:

```
(base) matentzn@mbp.local:~/ws/cdno/src/ontology (issue-88) $ sh run.sh make imports/ro_import.owl 
robot --catalog catalog-v001.xml remove --input cdno-edit.owl --select imports --trim false \
	merge   -o tmp/merged-cdno-edit.owl
robot --catalog catalog-v001.xml query -f csv -i tmp/merged-cdno-edit.owl --query ../sparql/terms.sparql tmp/pre_seed.txt.tmp &&\
cat tmp/pre_seed.txt.tmp | sort | uniq >  tmp/pre_seed.txt
rm imports/ro_terms_combined.txt
(base) matentzn@mbp.local:~/ws/cdno/src/ontology (issue-88) $ 
```

And it works fine. So its not an ODK issue. Lets dig deeper.

1. Have you ever run an import successfully on your exact machine on that terminal?

**Comment by LilyAndres** [comment]
> Have you ever run an import successfully on your exact machine on that terminal?

Yes, last week I ran the workflow.

**Comment by matentzn** [comment]
What docker version do you have installed?

<img width="956" alt="image" src="https://user-images.githubusercontent.com/7070631/174949569-e1b9a32f-6db5-448b-ae4e-27b0d0e56837.png">

**Comment by LilyAndres** [comment]
<img width="748" alt="Screen Shot 2022-06-22 at 3 22 53 pm" src="https://user-images.githubusercontent.com/25215773/174949934-f77d0ae9-2bee-4aa1-9d7c-c58c7cfcfc00.png">

**Comment by matentzn** [comment]
- So you are on the latest docker engine
- You have updated to the latest odk with docker pull
- Are on a mac
- Chebi and RO on your branch work on my machine but not on yours.
- Your error is associated with some ancient alpine images... ancient..
- Whats your operating system?

I think I will have to ask for outside help now! Maybe @gouttegd can help later today with an idea. In the meantime, restart your computer and try again. I will be back in 2 or 3 hours, have to do some stuff outside now!

**Comment by LilyAndres** [comment]
No worries, thanks a lot for help. I will restart now...

**Comment by LilyAndres** [comment]
Just to have a record, I have updated the system and ran the commands again without success, not really sure what is happening.

I have now **macOS Catalina Version 10.15.7**

**Comment by matentzn** [comment]
This Mac OS version is possibly ancient, and it's possible there is an adverse interaction between the latest docker and that. Can you run 

sh run.sh robot --version

And tell us what it says?

**Comment by LilyAndres** [comment]
OK, it says the following:

```
[0.055s][warning][os,thread] Failed to start thread - pthread_create failed (EPERM) 
for attributes: stacksize: 1024k, guardsize: 4k, detached.
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Cannot create worker GC thread. Out of system resources.
# An error report file with more information is saved as:
# /work/src/ontology/hs_err_pid1.log
```

**Comment by matentzn** [comment]
Interesting. 

Can you check what your docker memory config is saying?

https://oboacademy.github.io/obook/howto/odk-setup/#problems-with-memory-important

**Comment by gouttegd** [comment]
I wonder if it’s again a problem with the `clone3` syscall that is used by recent versions of the GNU libc…

Can you try running

```sh
docker run --rm -ti --security-opt seccomp=unconfined obolibrary/odkfull robot --version
```

**Comment by LilyAndres** [comment]
Thanks @matentzn and @gouttegd 

I have made the changes for the docker memory as suggested and it ran:

<img width="836" alt="Screen Shot 2022-06-22 at 5 52 05 pm" src="https://user-images.githubusercontent.com/25215773/174974931-bc243875-05e0-451d-ab46-3c02afe0b075.png">

I didn't change anything in the run.sh file though. I use to run the imports in this same machine before without any issues, not sure what happened but it seems it's all good now. 

> Can you try running

Yes, this is what I got: `ROBOT version 1.9.0`

Thanks a lot.

**Comment by matentzn** [comment]
Did you try refreshing RO again? Does everything work now?

**Comment by LilyAndres** [comment]
Just for the record, the for the docker was at 2.5 GB so I increased it to 14 GB, that's why it's working now.

**Comment by matentzn** [comment]
🎉  Pheeeew! Thanks for persevering and debugging :D @gouttegd thanks for chiming in!

Will close now, at least one issue solved for the day 🥷

**Comment by kaiiam** [comment]
Thanks @matentzn for helping here!

**Comment by matentzn** [comment]
Of course :)
