### ISSUE TITLE
mkdocs gh-deploy Error

### ISSUE THREAD

**Issue by StroemPhi** [INCATools/ontology-development-kit#628]
Hi, unfortunately I encountered the following error when trying to generate documentation from an ODK repo.

I set the respective flag
```
documentation:
  documentation_system: mkdocs
```
in my project.yaml and updated my repo. Yet when I call `sh run.sh make update_docs` I get:
```
mkdocs gh-deploy --config-file ../../mkdocs.yaml
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: /work/site
INFO     -  Documentation built in 0.32 seconds
ERROR    -  Cannot deploy - this directory does not appear to be a git repository
WARNING  -  Version check skipped: No version specified in previous deployment.
INFO     -  Copying '/work/site' to 'gh-pages' branch and pushing to GitHub.
ERROR    -  Failed to deploy to GitHub with error:
            unsafe repository ('/work' is owned by someone else)
            To add an exception for this directory, call:

                    git config --global --add safe.directory /work
Deployment Aborted!
make: *** [Makefile:555: update_docs] Error 1
```

Running `git config --global --add safe.directory /work` didn't do anything, unfortunately.

System Specs:
VM with Ubuntu 20.04.4 LTS in Win 10 using HyperV
Python 3.8.10
Docker version 20.10.17, build 100c701
ODK 1.3.1

**Comment by StroemPhi** [comment]
Added my user to docker group as described [here](https://docs.docker.com/engine/install/linux-postinstall/), but with no effect.

I was able to build the docs though by using `mkdocs gh-deploy --config-file ../../mkdocs.yaml` directly without docker, for which I had to install mkdocs and the material theme before.

**Comment by matentzn** [comment]
Did you manage to use GH actions yet?

**Comment by StroemPhi** [comment]
yes, all good can be closed
