### ISSUE TITLE
Add docker requirements to documentation

### ISSUE THREAD

**Issue by kltm** [INCATools/ontology-development-kit#636]
Doing some recent work, I noticed that ODK v1.3.1 seems to have a docker requirement somewhere between 20.10.7 (about a year ago) and 20.10.17 (latest).
ODK version v1.3.0 seemed to work fine with docker 20.10.7. I'm not sure if this is generally tracked or checked, but it would be good to add mention of things like this to the docs.

(Another approach would be to figure out if this is an undesired change and rollback the requirement.)

PR for one possible location: https://github.com/INCATools/ontology-development-kit/pull/635

**Comment by gouttegd** [comment]
The minimum Docker version depends on the underlying Ubuntu system. Docker versions prior to 20.10.8 are incompatible with some changes in the GNU libc that comes with Ubuntu 22.04.

Rolling back to an older Ubuntu is not really an option, but you are absolutely right that the requirement for a recent Docker version should be explicitly stated. Thanks for the PR! It has now been merged, so I’m closing here.
