### ISSUE TITLE
Files managed in OBO format have replaced by values as CURIE strings

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#642]
We should try and make sure they are correctly rewritten to URIs before moving out. Maybe use the new intermediate call #639 

see https://github.com/monarch-initiative/mondo/issues/2636

**Comment by gouttegd** [comment]
Any chance we could fix the OBO parser to recognise a CURIE value in a `replaced_by` tag, and replace it by a proper IRI value in the parsed ontology?

OBO files would then still use CURIEs, but they would automatically become IRIs upon transformation into any other format, without requiring any special processing at the ODK level.

**Comment by balhoff** [comment]
I've been keeping some notes on things we could clean up in the OBO parser. I would love if there were a syntactic difference between CURIEs and full IRIs so that either could be used, and a way to define prefixes. Maybe some interested folks could join a working group to create a revision.

**Comment by gouttegd** [comment]
@balhoff Not sure I understand why we would need a “syntactic difference between CURIs and full IRIs“?

Doesn’t the [`loadOboToIRI` method](https://github.com/owlcs/owlapi/blob/e0e9ef7690caa7f182bcf4d45b0a443545ac8bb3/oboformat/src/main/java/org/obolibrary/obo2owl/OWLAPIObo2Owl.java#L1486) in `owlapi-oboformat` already do everything that we need here? It recognises a “full IRI” as well as a “Prefixed ID” (i.e. a CURIE) and resolves the latter into a proper IRI. What else would we need?

**Comment by balhoff** [comment]
I need to go back and look at some of the specific cases, but the OBO parser makes some wrong assumptions in various situations. In every other OWL format a full IRI is surrounded by `<...>` and a CURIE is un-bracketed with a possibly empty prefix string followed by a colon. There shouldn't be a need for the parser to guess.

**Comment by balhoff** [comment]
Also—there is no way to define non-OBO namespace CURIEs, which is pretty limiting.

**Comment by matentzn** [comment]
I think in the interest of the future, it would be great to collect all obo-format problems together in some issue and organise a hackathon to fix the parsers, but in the interim, I would still like to implement a method to hack this. As I will now introduce formal contexts to each ontology repos (which contain prefix maps), my idea was to add a python script that reads the context and the intermediate ontology, replaces all prefixes that are known according to the context drop the rest with a warning.

**Comment by gouttegd** [comment]
> it would be great to collect all obo-format problems together in some issue and organise a hackathon to fix the parsers

Do we want to fix the _parsers_ or the _format_?

To be clear, I was talking about the parser, but I read @balhoff ’s comments above as if he would like a new version of the OBO format.

**Comment by matentzn** [comment]
I think its mostly about fixing the parser, but I think you need to add prefix maps to be able to curate non-OBO curies, for example in the replaced by section. Not sure of OBO format has that..

**Comment by gouttegd** [comment]
> Not sure of OBO format has that..

I believe it does: the OBO Flat File Format specification describes a `idspace` header tag to map a prefix to a base URL.

The owlapi’s OBO parser recognises that tag but doesn’t seem to do anything with it.

I suspect that if we used the mappings declared in `idspace` clauses to populate the `idSpaceMap` hashmap (which is used [here](https://github.com/owlcs/owlapi/blob/e0e9ef7690caa7f182bcf4d45b0a443545ac8bb3/oboformat/src/main/java/org/obolibrary/obo2owl/OWLAPIObo2Owl.java#L1551) when converting a CURIE to a IRI), we may have all what we need for this particular issue.

**Comment by gouttegd** [comment]
I don’t think there is anything left for the ODK to do here?

The OWLAPI OBO parser does expand CURIEs found in `replaced_by` tags since version 4.5.29, and therefore so does ROBOT since version 1.9.6.

@matentzn Anything else you wanted to be done as part of this issue?

**Comment by matentzn** [comment]
Nope, this is all we needed! Thanks for cleaning out!
