### ISSUE TITLE
Replace base specification by introducing the possibility of reasoning

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#646]
The current base specification is simply "all axioms belonging into that ontology, and not to one of its imports, merged into a single file". After thorough discussions with @cmungall @dosumis @balhoff and a few more we are now proposing to change that definition slightly to include "all axioms _and inferences_ belonging into that ontology, and not to one of its imports, merged into a single file." The point here is that we provide a way to publish a base file with the classification as intended by the ontology curators, that can then be safely combined with others.

We will write a paper about this.

Note that the old "base" file should still be exportable, but renamed to "editors release".

**Comment by dosumis** [comment]
> Note that the old "base" file should still be exportable, but renamed to "editors release".

should -> will

I agree that the new file is useful & important, but why change the definition of an artefact in the middle of it being used by multiple projects.  Why not just use base-plus for base + inferences as originally planned?

**Comment by matentzn** [comment]
This has been done a long time ago here: https://github.com/INCATools/ontology-development-kit/pull/810
