### ISSUE TITLE
Adjust Makefile to allow pushing only :dev tag to dockerhub

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#648]
If I only push `obolibrary/odkfull:dev` tag to dockerhub, will people using

```
docker pull obolibrary/odkfull
docker pull obolibrary/odkfull:latest
```

be unaffected @gouttegd ?

**Comment by gouttegd** [comment]
If no tag is specified when pulling, the default tag is `latest`, so people using `docker pull obolibrary/odkfull` should still get the image tagged `latest` even if a more recent image with another tag (`dev`) is also available on the hub.

As for people using `docker pull obolibrary/odkfull:latest`, the tag is explicitly specified, so again, the mere presence of another and more recent image should not impact them.

**Comment by matentzn** [comment]
I am thinking of running more regular `dev` builds. Can you perhaps create a make goal for me (publish-multiarch-dev) that will safely build a multiarch image and push only a dev tag? Not urgent but I think this will make a lot of stuff easier because I can role experimental features out quicker..

**Comment by gouttegd** [comment]
I’m assuming you would only need `odkfull`, right? You can do without a `odklite:dev`?

(Not that we can’t do both if needed, of course. But I’d rather implement only what we actually need.)

**Comment by matentzn** [comment]
yes, only odkfull:dev is totally sufficient (probably better in case docker hub starts putting limits on the size of an org)

**Comment by matentzn** [comment]
Awesome, very very appreciated!
