### ISSUE TITLE
Standardizing ontology .owl metadata

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [INCATools/ontology-development-kit#67]
I suggest including certain ontology metadata fields into the ontology starter kit.  Our GEEM ontology driven data specification system already takes advantage of the versionIRI field that the Makefile adds in order to version any terms lifted from the ontology, in order to recreate related specifications in the future. As well all the stuff below is displayed with ontology resources when users are browsing them in GEEM - and other systems too I presume - . We added a DC terms date field as well, which is set to mirror the date dumped into the versionIRI, in case the versionIRI has some other scheme to it.

```
<rdf:RDF 
	…
     xmlns:terms="http://purl.org/dc/terms/"
	…

    <owl:Ontology rdf:about="http://purl.obolibrary.org/obo/genepio.owl">
        <owl:versionIRI rdf:resource="http://purl.obolibrary.org/obo/genepio/releases/2018-02-28/genepio.owl"/>
	…
        <terms:title xml:lang="en">Genomic Epidemiology Ontology</terms:title>
        <terms:description xml:lang="en">The Genomic Epidemiology Ontology aims to provide a comprehensive controlled vocabulary for infectious disease surveillance and outbreak investigations. It is an application ontology that draws on many other ontologies including anatomy, taxonomy, disease, symptoms, environment and food types.</terms:description>
        <oboInOwl:default-namespace rdf:datatype="http://www.w3.org/2001/XMLSchema#string">GENEPIO</oboInOwl:default-namespace>
        <terms:license rdf:resource="http://creativecommons.org/licenses/by/3.0/"/>
    </owl:Ontology>

```
Right now it seems this kind of stuff would go in https://github.com/INCATools/ontology-starter-kit/blob/master/template/src/ontology/foobar-edit.owl ?

The terms:date gets added too via Makefile:
`
	$(ROBOT) reduce -i $< -r ELK -s true annotate --xml-entities -V $(BASE)/releases/`date +%Y-%m-%d`/$(ONT).owl --typed-annotation http://purl.org/dc/terms/date `date +%Y-%m-%d` xsd:date -o "$@"
`

**Comment by cmungall** [comment]
Great suggestion!

I have tended to keep the date out of the edit file and add it purely through robot as you point out.

defaultNamespace is an oboformat hangover...

**Comment by Public-Health-Bioinformatics** [comment]
Is there another preferred annotation besides defaultNamespace that would indicate the ontology id structure & recommended namespace prefix within OBOFoundry? (So the ontology itself could indicate this to processes that consume it.)

**Comment by pbuttigieg** [comment]
Perhaps syncing with the various *portals, the OLS, OntoBee, and the ESIP
COR would be wise at this stage. If they can parse the metadata, it would
be a big step.

**Comment by Public-Health-Bioinformatics** [comment]
Good idea - I've just reached out to all those folks...

**Comment by matentzn** [comment]
Hey all! Do we have any concrete actions we should be doing to move forward on this issue?

**Comment by matentzn** [comment]
I will add at least the three new required ontology annotations to the default:
https://github.com/INCATools/ontology-development-kit/blob/master/docs/License.md

**Comment by matentzn** [comment]
Fixed in https://github.com/INCATools/ontology-development-kit/commit/b7f7cb15cb00435802977b647545c95aeb0b04c5
