### ISSUE TITLE
Request: Add `component-download-mondo` to `Makefile`

### ISSUE THREAD

**Issue by joeflack4** [INCATools/ontology-development-kit#677]
## Overview
This addition will help with the [`mondo-ingest`](https://github.com/monarch-initiative/mondo-ingest/). The make pipeline for `mondo-ingest` involves the download of several ontologies as 'mirrors', and then after some mutations, 'component' `.owl` files of each of these ontologies are created. However, Mondo does not need to undergo this same process. As it currently stands, we do need a 'component file' created for Mondo, but when we try to create this file, it gets pattern-matched with the existing "`component-%`" targets, and ends up running prerequisites that it should not.

The solution I've come up with along with @matentzn is to create a target for the creation of this component Mondo file specifically.

## Additional info
I've created a PR for this already: #676 

@matentzn Just copy/pasting what we have in `mondo-ingest` that will be removed once we can merge a PR on this. There is a second target that was commented out (`$(COMPONENTSDIR)/mondo.owl`). I think it's not needed, but I just wanted to leave it here just in case there's anything still needed there.

```
# TODO: (a) Move this to Makefile, or (b) refactor this away.
.PHONY: component-download-mondo.owl
component-download-mondo.owl: | $(TMPDIR)
	if [ $(MIR) = true ] && [ $(COMP) = true ]; then $(ROBOT) merge -I http://purl.obolibrary.org/obo/mondo.owl \
	annotate --ontology-iri $(ONTBASE)/$@ $(ANNOTATE_ONTOLOGY_VERSION) -o $(TMPDIR)/$@.owl; fi

# TODO: (a) Move this to Makefile, or (b) refactor this away, or (c) DELETE this goal.
# ...I think (c) is most likely, as `reports/mirror_signature-%.tsv` needs `component-download-%.owl`.
# ...`reports/component_signature-%.tsv` is what needs `components/%.owl`, but that shouldn't be needed here.
# $(COMPONENTSDIR)/mondo.owl: component-download-mondo.owl
# 	if [ $(COMP) = true ] ; then if cmp -s $(TMPDIR)/component-download-mondo.owl.owl $@ ; then echo "Component identical."; else echo "Component is different, updating." && cp $(TMPDIR)/component-download-mondo.owl.owl $@; fi; fi
```

**Comment by joeflack4** [comment]
This is probably a non-issue for ODK. @matentzn can you close this if so?

Links to previous discussion on this:
1. https://github.com/INCATools/ontology-development-kit/pull/676#discussion_r959714143
2. https://github.com/monarch-initiative/mondo-ingest/pull/36#discussion_r956728842

**Comment by matentzn** [comment]
Thank you @joeflack4 :)
