### ISSUE TITLE
Upgrade NPM to latest version

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#686]
The version the ubuntu store is very outdated. Follow:

https://www.freecodecamp.org/news/how-to-install-node-js-on-ubuntu-and-update-npm-to-the-latest-version/

Here is roughly where the fix should be done: https://github.com/INCATools/ontology-development-kit/blob/master/Dockerfile#L32

**Comment by matentzn** [comment]
- [ ] make PR on DOckerfile above
- [ ] Test locally by running `make build` and then `sh run.sh bash` in mondo-ingest repo

**Comment by gouttegd** [comment]
> `curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -`

People who write this kind of instructions should be hanged, drawn, quartered, boiled, torn to pieces, and then _really_ hurt. And they should also lose their commit rights forever.

**Comment by gouttegd** [comment]
Seriously. Please don’t follow the ”advice” on that page. If a more recent version of Node is absolutely needed, then either

* add **manually** (not by running a script fetched from the Internet) a new APT source pointing to the `deb.nodesource.com` repository prior to calling `apt-get install nodejs`, or
* build Nodejs from source.

**Comment by matentzn** [comment]
Thank you @gouttegd, lucky to have you to prevent us to do stupid things. Yes, we have a use case that required the latest node version. @hrshdhgd do you feel like you could figure out the first option? (add new `apt` source before running `apt install`? If not, Damien can maybe give us a hint.

**Comment by gouttegd** [comment]
You can have a look in the history of the `Dockerfile` for how we used to install `gh` from a third-party repository (before we switched to using the version from the Ubuntu repos in #683).
