### ISSUE TITLE
Auto-generate import statements on pattern.owl

### ISSUE THREAD

**Issue by dosumis** [INCATools/ontology-development-kit#69]
This should be straightforward to do by adding a pattern.owl file with the correct URL & and import statement structured as for -edit.owl and merging the generated prototype OWL file into it. This may also need some tweaks to `/seed-my-ontology-repo.pl`.

**Comment by matentzn** [comment]
@dosumis Can you clarify what this issue is about again? Sorry for being daft :P

**Comment by matentzn** [comment]
Closing for long inactivity, we are using the ontologies imports for pattern.owl.
