### ISSUE TITLE
ensure components (and imports?) are in OFN for better readability

### ISSUE THREAD

**Issue by allysonlister** [INCATools/ontology-development-kit#700]
This ticket covers the creation of the files from the template command are in (or are able to be configured as such) ofn format. Details of the originating question and ticket are below.

Thanks!

> How do I ensure that the resulting output is in ofn format, even if the filename remains .owl so as not to confuse the generated makefile? ofn seems a lot easier for diffs etc. I know robot has a diff feature, but it would be great to be able to use ofn please.

Very good point. This would have to be a feature request here at the ODK repo - you are totally right we should do that! Can you open a new issue "ensure components (and imports?) are in OFN for better readability"?

We will probably make the syntax configurable.

_Originally posted by @matentzn in https://github.com/INCATools/ontology-development-kit/issues/695#issuecomment-1259129091_

**Comment by matentzn** [comment]
@INCATools/odk-developers what do you think about this suggestion? I think this is a good idea, but it will create one massive _diff_ once when imports are updated for the first time..

**Comment by dosumis** [comment]
I think it's a good idea, esp for components.

**Comment by joeflack4** [comment]
I'm happy to give my opinion, but I need to understand OFN better. I believe it stands for "fun owl" or "owl fun" format. I'm only familiar with this: https://github.com/Harold-Solbrig/funowl. It looks like there's a bit more on it here: https://www.w3.org/TR/owl2-syntax/#Functional-Style_Syntax. Hmm, I think I'd need to dig into it a lot more or have it explained to me to be able to give my input on this, so I'll abstain for now.

**Comment by anitacaron** [comment]
This was fixed in the commit https://github.com/INCATools/ontology-development-kit/commit/f4751d0cb7ed426968964487e7dafd8479f59511 and has been available since ODK 1.4. 

It's a new configuration option, `import_component_format`, on the project level, with the default value of OFN.
