### ISSUE TITLE
Test run.sh.conf option for environment variables of run.sh

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#730]
many projects basically just want to use the development snapshot (not main ontologies, but more experimental pipelines). It is an overhead to keep setting the variable names. 

@gouttegd what happened with your .ENV idea? Did we ever implement that?

**Comment by gouttegd** [comment]
Yes, that was done as part of #678.

So for example, to always use the development snapshot in a given repository without having to set environment variables, create a `run.sh.conf` file in the `src/ontology` directory with:

```
ODK_TAG=dev
```

**Comment by matentzn** [comment]
@hrshdhgd can you try doing that for mondo-ingest?

**Comment by matentzn** [comment]
Thank you @gouttegd
