### ISSUE TITLE
Hard coded ODK version in dynamic jinja?

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#733]
The dynamic jinja files contain conditionals like:

```
{% if env is defined -%}{{env['ODK_VERSION'] or "v1.2.25" }}{%- else %}v1.2.25{% endif %}
```

in various places. This is weird, especially since `v1.2.25` is an ancient version of ODK. Should we replace this case by `latest`?

**Comment by anitacaron** [comment]
I don't understand the logic in this part:

```
{{env['ODK_VERSION'] or "v1.2.25" }}
```

This will return a bool value, no? Should this be kept?

**Comment by gouttegd** [comment]
> This will return a bool value, no?

I don’t think so. If there is an `ODK_VERSION` variable in the environment, it will return the value of that variable, and if there is no such variable (_i.e._ `env['ODK_VERSION']` is `None`), it will return `v1.2.25`.
