### ISSUE TITLE
DOSDP add option to add conformsTo provenance

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#742]
From slack discussion: classes created by a DOSDP pattern should get an option to be annotated with the pattern generating it. dosdp tools has this already.

```
--add-axiom-source-annotation  <true|false>
        Add axiom annotation to generated axioms linking to pattern IRI
```

**Comment by balhoff** [comment]
Keep in mind it annotates all the axioms, not the class. But a class annotation can be added directly inside the pattern I think (it works for a variable, not sure for a constant value).

**Comment by matentzn** [comment]
Since we can pass arbitrary options to dosdp tools, we don't need a specific option in ODK anymore.
