### ISSUE TITLE
Random failure of the `test-dosdp-matches` check

### ISSUE THREAD

**Issue by gouttegd** [INCATools/ontology-development-kit#743]
Over the last few days, we have observed repeated failures of the CI suite. The test that fails is always `test-dosdp-matches`, and the error is always in the RDF/XML validation:

```
Checking RDF/XML file tdm.owl...
  LightRDF: Unexpected EOF during reading Comment
```

While the failure is always the same _when it occurs_, it does not always occur; sometimes the check goes just fine.

I have managed to reproduce the failure just once on my local machine. I attach to this ticket the corresponding `tdm-bad.owl` file. Indeed, trying to parse that file with LightRDF consistently yields the “Unexpected EOF during reading Comment”, even though I can’t see anything wrong with that file (all other RDF/XML-consuming tools have no trouble to read it).

I also upload a `tdm-good.owl` file, obtained after a test run that didn’t produce any error. The only differences between the two is that a handful of `oboInOwl:hasDbXref` statements either have or have not a `rdf:datatype="http://www.w3.org/2001/XMLSchema#string"` qualifier.

> **Problem 1**: How comes that the produced `tdm.owl` file is not reproductible from one run to the next? Why do some `oboInOwl:hasDbXref` statements have a `rdf:datatype` qualifier while some others have not, and why does that change between runs?

The LightRDF error seems to be caused by anyone of the statements like this one:

```xml
<oboInOwl:hasDbXref rdf:datatype="http://www.w3.org/2001/XMLSchema#string">PRO:DAN</oboInOwl:hasDbXref>
```

Removing the `rdf:datatype` qualifier altogether clears the error. Changing the datatype to anything else than `XMLSchema#string` (even something that is not a valid XMLSchema type) clears the error. Keeping the qualifier as it is but removing the colon within the value (e.g., changing the value to `PRODAN`, without a colon) clears the error.

> **Problem 2**: What the hell is LightRDF doing here?

Suggestions:
* Investigate what clearly seems to be a hideous bug in LightRDF (or the underlying Rust parser). Try to produce a minimal file that reproduces the error so that we can report the bug to LightRDF upstream.
* In the meantime, disable the LightRDF-based RDF/XML validation check. Checking that our produced RDF/XML files are correct is sure nice, but not if we cannot trust the validator for not barking on what appears to be a perfectly correct RDF/XML file!
* Meditate on the value of a test suite that does not produce consistently reproductible results.
* Meditate on the brittleness of our tools.

The produced OWL files (renamed with a `.txt` extension as GitHub does not allow attaching `.owl` files):
* [tdm-bad.txt](https://github.com/INCATools/ontology-development-kit/files/10042121/tdm-bad.txt)
* [tdm-good.txt](https://github.com/INCATools/ontology-development-kit/files/10042122/tdm-good.txt)

**Comment by gouttegd** [comment]
The craziness goes on…

The `tdm-bad.owl` file has 99 lines that contain XML escape sequences (`&quot`, `&apos`, etc.). They are also present in the `tdm-good.owl` file.

Removing any single one of those sequences is enough to clear the error and allow the file to be parsed by LightRDF. **It does not matter which one is removed!**

What.The.Actual.Fudge?

**Comment by matentzn** [comment]
oh my word.. :/ Maybe we need to drop the check_rdfxml from the default checks? This sounds like a bug in LightRDF..

**Comment by gouttegd** [comment]
Clearly a bug in LightRDF, yes (or more probably, in the Rust `Rio` library that LightRDF is wrapping), _and_ a bug in our pipelines that are not idempotent.

**Comment by gouttegd** [comment]
Can’t reproduce the parsing error with a minimal RDX/XML parser from the Rust `Rio` library or with the `quick_xml` XML parser on which `Rio` is based…

Either I’m missing something (likely) or the problem is indeed in `LightRDF`.

**Comment by cmungall** [comment]
I don't think the fault is in LightRDF

I tried
https://pyoxigraph.readthedocs.io/en/latest/io.html

```python
from pyoxigraph import parse
triple_it = parse("tests/input/odk-issue-743.owl", "application/rdf+xml")
for s, p, o in triple_it:
    print(s,p,o)
```

and it happily churns out *all* of the triples, then fails with:

```
Traceback (most recent call last):
  File "/Users/cjm/repos/rdf-sql-bulkloader/pyoxitest.py", line 3, in <module>
    for s, p, o in triple_it:
OSError: Comment
```

I am not sure how to force it to give me more info. Changing PRO:DAN to PRODAN fixes the issue, consistent with the LightRDF behavior

What is mysterious is that when it fails, it still succeeds in writing all the triples, something happens at the end of iteration, most odd.

**Comment by gouttegd** [comment]
Thanks for investigating this!

So the problem must be in a layer that is common to both LightRDF and Pyoxigraph, which would point to Rust’s `rio_xml` module…

But when I try parsing the “bad” `tdm.owl` file in Rust with `rio_xml`, everything seems fine:

```rust
use rio_xml::{RdfXmlParser, RdfXmlError};
use rio_api::parser::TriplesParser;
use std::path::Path;
use std::fs::File;
use std::io::BufReader;

fn main() {
    let path = Path::new("tdm.owl");
    let file = match File::open(path) {
        Ok(f) => f,
        Err(e) => panic!("Cannot open file {}: {:?}", path.display(), e)
    };

    let mut count = 0;
    let reader = BufReader::new(file);
    let s = RdfXmlParser::new(reader, None).parse_all(&mut |t| {
        count += 1;
        println!("{} {} {}", t.subject, t.predicate, t.object);
        Ok(()) as Result<(), RdfXmlError>
    });
    match s {
        Err(se) => panic!("Error when reading triples: {:?}", se),
        Ok(()) => ()
    };

    println!("Triples read: {}", count);
}
```

This would correctly print out all the triples without throwing any error.

**Comment by gouttegd** [comment]
I tested with `rio_xml` 0.7.0 and `rio_api` 0.7.0, which are the same versions used by LightRDF since September 2022.

**Comment by matentzn** [comment]
@gouttegd are there any action items on this?

**Comment by gouttegd** [comment]
@matentzn Not for now. I already disabled the RDF/XML validation check that uses LightRDF (#745), that’s about all we can do for now.

Re-enabling the check will need to wait until the bug in either LightRDF or the underlying Rust parser is fixed, which may take a while since the bug is frankly a complete mystery.

**Comment by gouttegd** [comment]
The bug has been fixed in LightRDF.
