### ISSUE TITLE
Provide tutorial for importing orcidio

### ISSUE THREAD

**Issue by cthoyt** [INCATools/ontology-development-kit#751]
[Orcidio](https://github.com/cthoyt/orcidio) is a small ontology containing about 250 contributors to various obo ontologies as instances, using canonical https orcid URLs. Importing this ontology automatically gets protege to show label information for these people, hopefully pushing the debate about only using orcid IDs even further (because it effectively solves the issue of readability/transparency of names is addressed with orcidio)

can you provide an example/tutorial on how odk ontologies can start importing this?

**Comment by anitacaron** [comment]
It was created a tutorial on the OBOOK - [Import ORCIDIO](https://oboacademy.github.io/obook/howto/odk-add-orcidio-module/)

**Comment by cthoyt** [comment]
There are a few to-dos in the tutorial there that require either further explanation, or linking to other tutorials. As it stands, the tutorial isn't self-contained and requires prior knowledge to follow (i.e., I can't do it myself, so I would not consider it complete)
