### ISSUE TITLE
validation error when using orcid as value for dcterms:contributor

### ISSUE THREAD

**Issue by wdduncan** [INCATools/ontology-development-kit#752]
The validation query `iri-range-violation.sparql` fails when an orcid (defined as a string) is used as the value of `dcterms:contributor`. Here is an example of the output from the attached toy ontology.
```
FAIL Rule iri-range-violation.sparql: 1 violation(s)
term,property,value
http://example.com/contribution-error.owl/foo,http://purl.org/dc/terms/contributor,https://orcid.org/0000-0001-9625-1899
```
There are multiple workarounds in Protege. Here are a few.

1. Set the creation of new entities to use your orcid.

<img width="482" alt="image" src="https://user-images.githubusercontent.com/3186638/205352983-f9079594-99c9-4a4d-bb5c-8184dabba13b.png">

However, this creates an orcid with an `http` prefix, instead of `https`.

2. Manually edit the contributor annotation to use an IRI.

<img width="648" alt="image" src="https://user-images.githubusercontent.com/3186638/205353296-76ff3e21-a15d-4b90-8efc-1f09785cf597.png">

This is bit of a pain to do every time you create a `dcterms:contributor` annotation.

3. Set the range of `dcterms:contributor`  to be `xsd:anyURI`.

<img width="511" alt="image" src="https://user-images.githubusercontent.com/3186638/205353660-ae230c7d-208e-41f5-9493-6615e589799b.png">

If the range can be set in OMO, this might work for ontologies that import OMO.

[contribution-error.owl.zip](https://github.com/INCATools/ontology-development-kit/files/10143232/contribution-error.owl.zip)

**Comment by balhoff** [comment]
I think a fix for this is coming in the next Protégé release: https://github.com/protegeproject/protege/pull/1053

**Comment by matentzn** [comment]
There is a `#protege-testing` channel on the OBO slack for the brave, there already is a beta release on Protege and I just tested - it works correctly.

**Comment by wdduncan** [comment]
Thanks @matentzn !
I'm not that brave :)

**Comment by matentzn** [comment]
I will close this issue as it will be fixed by the next Protege iteration.
