### ISSUE TITLE
Add environment defaults for OWL API parsing behaviour

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#778]
For context read this thread: https://github.com/protegeproject/protege/issues/1096#issuecomment-1387292671

We should consider to make it easy in ODK to set some environment variable by default. Can we somehow do this in the Makefile? like `BANNED_PARSERS`?

**Comment by gouttegd** [comment]
Of note, as far as I can tell, environment variables _cannot_ actually be used to configure the OWL API. The only two ways are a `owlapi.properties` file that must be in the class path of whatever tool (e.g. ROBOT) is using the OWL API, or Java system properties passed directly on the command line with the `-D` option.

So what people can already do is to add whatever property they need in the `ODK_JAVA_OPTS` variable of the `run.sh` script. E.g, to ban a specific parser:

```sh
ODK_JAVA_OPTS=-Dorg.semanticweb.owlapi.model.parameters.ConfigurationOptions.BANNED_PARSERS=org.semanticweb.owlapi.rio.RioTrixParserFactory
```

I guess what we could do make that easier is to allow to use variable names such as `OWLAPI_BANNED_PARSERS`, and then in the `run.sh` script we detect such variables and convert them to appropriate `-D` options to append to `ODK_JAVA_OPTS`.

I would like to argue _against_ doing that for 1.4, though. The next ODK release is much overdue, I think such a feature can easily wait for another release.
