### ISSUE TITLE
Option to generate base for mixed-prefix ontologies fails due to case sensitivity

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-development-kit#784]
@hrshdhgd will provide a full reproducible test

We noticed when building bero that the step to make NCBITaxon as a component makes an empty file. It looks like we set this as a base module (I think this is pointless as the main NCBITaxon is a simple already-base ontology).

The Makefile has a robot remove command with

`--base-iri $OBO/NCBITAXON`

It looks like there is an assumption all OBOs are all upper case, but we have a handful of mixed case ontologies

Not urgent as I think we just use all of NCBITaxon for bero rather than base

**Comment by hrshdhgd** [comment]
[Here's an example PR](https://github.com/berkeleybop/bero/pull/6/files) where we noticed this happening. 

In `ber-odk.yaml` I had the following code block
```
    - id: ncbitaxon
       is_large: TRUE
       use_gzipped: TRUE
       make_base: TRUE
```

Then I ran `sh run.sh make update_repo` which autogenerated the following code block in the `MakeFile`:
```
## ONTOLOGY: ncbitaxon
 .PHONY: mirror-ncbitaxon
 .PRECIOUS: $(MIRRORDIR)/ncbitaxon.owl
 mirror-ncbitaxon: | $(TMPDIR)
 	if [ $(MIR) = true ] && [ $(IMP) = true ] && [ $(IMP_LARGE) = true ]; then curl -L $(URIBASE)/ncbitaxon.owl.gz --create-dirs -o $(MIRRORDIR)/ncbitaxon.owl.gz --retry 4 --max-time 200 &&\
 		$(ROBOT) convert -i $(MIRRORDIR)/ncbitaxon.owl.gz -o $@.tmp.owl && \
 		$(ROBOT) remove -i $@.tmp.owl --base-iri $(URIBASE)/NCBITAXON --axioms external --preserve-structure false --trim false -o $@.tmp.owl &&\
 		mv $@.tmp.owl $(TMPDIR)/$@.owl; fi
```

Notice the `$(URIBASE)/NCBITAXON`.

**Comment by matentzn** [comment]
You can already specify base IRIs manually:

https://github.com/obophenotype/uberon/blob/master/src/ontology/uberon-odk.yaml#L48

Would this address this issue?

**Comment by matentzn** [comment]
I assume this is fixed now, please re-open if still an issue.
