### ISSUE TITLE
The combination is_large: TRUE does not work with make_base: TRUE

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#785]

**Comment by anitacaron** [comment]
It's not working because this combination is combined with `module_type: mirror`. So it's expected to not apply these two options.

**Comment by matentzn** [comment]
Make base should work in combination with mirror if possible!

**Comment by anitacaron** [comment]
Sorry, it's already working the `make_base` with `module_type: mirror`. The `make_base` removes all external axioms in the mirror.

**Comment by matentzn** [comment]
Thanks for looking into it. Weird then this happened.

**Comment by anitacaron** [comment]
We need to review the condition `is_large` that is added in the mirror. At the moment, there isn't a difference.

**Comment by matentzn** [comment]
Thanks!
