### ISSUE TITLE
Create a `help` script that allows us to print all installed tools?

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#791]
Something like this, to get a list of all tools installed, plus a link to their documentation

**Comment by gouttegd** [comment]
Along with their versions, and maybe even (when relevant, mostly for ROBOT) the version of the OWL API.

**Comment by gouttegd** [comment]
@matentzn Inclined to close here. #1011 is missing the “link to their documentation” bit, but I don’t think this is really needed. Your call.
