### ISSUE TITLE
Add rdfs:isDefinedBy to imports

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#796]
ROBOT now has this cool option with merge to add provenance:

```
robot merge -I http://purl.obolibrary.org/obo/pato.owl -I http://purl.obolibrary.org/obo/ro.owl --annotate-defined-by true -o defined-by.owl
```

We should consider adding this by default to ODK.

**Comment by anitacaron** [comment]
Nico's comment from previous issue

> probably using isDefinedBy, whatever is standard.

>This way we can easily remove external axioms at a later step, also helps with provenance.
