### ISSUE TITLE
Switch qc.yml to ODK managed

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#797]
Right now, qc.yml GitHub actions is user managed. The idea was to make it customisable. The truth is this was a bad idea - I keep having to manually migrate this file because many comments touched by the test keep needing more up to date ODK versions.

**Comment by gouttegd** [comment]
Currently, only the `docs` workflow is automatically updated, right?

```python
 workflows : Optional[List[str]] = field(default_factory=lambda: ['docs'])
    """Workflows that are synced when updating the repo. Currently available: docs, diff, qc."""
```

So basically you propose to simply add `qc` to the list of automatically updated workflows?

No objection to that as long as users can still override the default if they so wish.
