### ISSUE TITLE
synchronizing versions of components

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-development-kit#80]
moving forward we should be more formal about versions

 * odk (repo) 1.1.1
 * odkfull (dockerhub) 1.1.1
 * robot 1.1.0
 * dosdp-tools 0.9
 * dosdp schema checker (master)

We have historically tied the docker builds to robot master, but moving forward we will tie to official robot releases.

should the seeded repo be tied to a particular docker build? Currently run.sh just uses the name obolibrary/odkfull but doesn't use a tag. If we tie it to a tag then we don't run the risk of accidentally breaking peoples setups with new docker releases. But it means people have to explicitly update to get newer features.

Should we try and harmonize the numbering? Currently we have robot release 1.1.0, and odk 1.1.1 but this may be hard to maintain, e.g. we may want to release robot patches.

**Comment by matentzn** [comment]
I think the way we have it is good.. It works well, and we have had no complaints so far. I don't think we should tie run.sh to some version, this is defeats the purpose of keeping everyone up to date!
