### ISSUE TITLE
Option to make base import fails when there is a custom URIBASE prefix

### ISSUE THREAD

**Issue by ehartley** [INCATools/ontology-development-kit#805]
In CPONT we use a custom uribase and found that when we use `make_base: TRUE` for an import, the resulting import file is empty.  

For example, when the `cpont-odk.yaml` file contains the following lines:
```
uribase: https://w3id.org/cpont
import_group:
  products:
    - id: obi
      make_base: TRUE
```
Then running `make update_repo` generates the following code block in the Makefile:
```
## ONTOLOGY: obi
.PHONY: mirror-obi
.PRECIOUS: $(MIRRORDIR)/obi.owl
mirror-obi: | $(TMPDIR)
	if [ $(MIR) = true ] && [ $(IMP) = true ]; then curl -L $(OBOBASE)/obi.owl --create-dirs -o $(MIRRORDIR)/obi.owl --retry 4 --max-time 500 &&\
		$(ROBOT) convert -i $(MIRRORDIR)/obi.owl -o $@.tmp.owl && \
		$(ROBOT) remove -i $@.tmp.owl --base-iri $(URIBASE)/OBI --axioms external --preserve-structure false --trim false -o $@.tmp.owl &&\
		mv $@.tmp.owl $(TMPDIR)/$@.owl; fi
```
It is the `--base-iri $(URIBASE)/OBI` in the robot remove line that is causing the import to be empty.  In this line `$(URIBASE)` should be changed to `$(OBOBASE)`.

**Comment by matentzn** [comment]
@ehartley would you be happy to actually provide a fix in https://github.com/INCATools/ontology-development-kit/blob/master/template/src/ontology/Makefile.jinja2? You can assign to me for review?
