### ISSUE TITLE
Makefile: importgroup.product.annotation_properties does not do anything

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#814]
Only importgroupt.annotation_properties works.

**Comment by anitacaron** [comment]
`import_group.annotation_properties` only works if used with `module_type` is `minimal` or `filter`. Is this still the intention?

**Comment by matentzn** [comment]
(and `merged` I hope?)

I think so far this is the case, because these are the ones based on ROBOT filter. If we want to make these work for the other module types, we need to add an entire clause to the ROBOT command that filters other APs out, right? Sorry I have not looked much at this.
