### ISSUE TITLE
Generating constraints.txt should fail if no constraints.txt is generated

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#845]
in this run #844 some ridiculous error happened:

https://github.com/INCATools/ontology-development-kit/actions/runs/4657721662/jobs/8242594679#step:5:880

The PR should not have gone ahead. At least, we should add a `test` statement to the shell script?

**Comment by gouttegd** [comment]
OMFG, what the hell happened here?

Adding that example to my list of “reasons why _automatic dependency management_ should really be called _automatically fucked-up dependency management_”…

Agree that we need some safety check here.
