### ISSUE TITLE
Generating markdown tables from custom reports in tsv

### ISSUE THREAD

**Issue by pfabry** [INCATools/ontology-development-kit#857]
There are existing mkdocs plugins that could do the job, like [table reader](https://github.com/timvink/mkdocs-table-reader-plugin), but is there an already available tool within ODK to automatically create a table in a doc page from a query result in tsv format?

**Comment by matentzn** [comment]
No, I dont think so! This is a great addition, feel free to make a PR that updates

https://github.com/INCATools/ontology-development-kit/blob/master/requirements.txt.full

and 

https://github.com/INCATools/ontology-development-kit/blob/master/template/_dynamic_files.jinja2#L1733

respectively!

**Comment by pfabry** [comment]
I tested the plugin locally and created the branch but it seems I don't have the rights to push it.

**Comment by matentzn** [comment]
Thank you @pfabry, we can either:

1) Add you to the ODK developer team, and you can make your PRs from that point on or
2) You create a Fork first, and create a PR from the fork! 

Let me know what you prefer.

**Comment by pfabry** [comment]
Let's go with the fork.

**Comment by pfabry** [comment]
cf. PR #861
