### ISSUE TITLE
Add a human readable reference guide explaining the project YAML parameters

### ISSUE THREAD

**Issue by StroemPhi** [INCATools/ontology-development-kit#864]
Spun out of a[ Slack discussion](https://obo-communitygroup.slack.com/archives/C01BKKED8R2/p1683707065645869?thread_ts=1683694703.704229&cid=C01BKKED8R2), we've identified the need to have a more practical overview of what project.YAML parameters are available and how to set them, based on https://github.com/INCATools/ontology-development-kit/blob/master/docs/project-schema.md.

**Comment by StroemPhi** [comment]
Is related to #866

**Comment by pfabry** [comment]
As a first step, maybe we could make `project-schema.md` more visible for ODK users? Personally, I wasn't aware of the files content before the Slack discussion. This file (and all the markdown files in /docs in fact) should be generated iin /docs when you generate a new repo.

**Comment by StroemPhi** [comment]
I agree that having `project-schema.md` in the docs folder that gets generated by ODK would be really helpful. The other MDs however are mostly redirects to the OBOOK. So wouldn't it thus be better to only add one or more links to the OBOOK in the default doc templates of ODK?

**Comment by StroemPhi** [comment]
Regarding the suggested first step of exposing the `project-schema.md` to ODK users, I would suggest to link to it under the [Where to get help](https://github.com/INCATools/ontology-development-kit#where-to-get-help) section of the ODK README. 

Regarding the integration into the autogenerated docs of an ODK based repo, I would add a link to the `project-schema.md` in a appropriate section of https://github.com/INCATools/ontology-development-kit/blob/master/template/_dynamic_files.jinja2. 

Regarding fleshing out the documentation of the schema itself, I would then suggest to iterativly improve the `project-schema.md`, as it then serves as single point of truth.  Although I wonder if it would be better to have such a more fleshed out MD live in the OBOOK instead of the ODK repo?

Any thought @matentzn or @gouttegd?

**Comment by matentzn** [comment]
Sure, if you can make a PR with a proposal, that would be great!

**Comment by StroemPhi** [comment]
point 1 & 2 from https://github.com/INCATools/ontology-development-kit/issues/864#issuecomment-1562437067 are addressed in the linked PR. Regarding Point 3, before fleshing it out, I need to know, if the `project-schema.md` is autogenerated. Woulnd't make much sense to edit it if so.

**Comment by StroemPhi** [comment]
I specified that #879 would close this issue, as I think it would be better to open a new issue for the actual fleshing out of the schema description/documention.
