### ISSUE TITLE
robot reason should have -e none

### ISSUE THREAD

**Issue by marieALaporte** [INCATools/ontology-development-kit#87]
Since ODK is used for new ontologies, having this -e none would allow to check for equivalent classes and die if any are found.
Can be useful for inca form too as it will let the ontology editors that the new term is already existing (in case of adding the term with a pattern that is not the most specific but would be still correct or something like that).

**Comment by marieALaporte** [comment]
and should this test happen when you make pattern too? (no need to make all every time so it's quicker)

**Comment by cmungall** [comment]
agreed

also thinking of including a SPARQL to inject a disjoint sibling for every class. I  shared a doc with your about this

E.g.

```
Class: PeripheralNerveSib
  SubClassOf: Nerve
  DisjointWith: PeripheralNerve
````


```
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>

CONSTRUCT {
  ?sibClass a owl:Class ;
            owl:disjointWith ?c ;
            rdfs:subClassOf ?p ;
            rdfs:label ?sibLabel
}
WHERE {
 ?c rdfs:subClassOf ?p .
 FILTER(isIRI(?c))
 FILTER(isIRI(?p))
 FILTER NOT EXISTS { ?c owl:deprecated "true"^^xsd:boolean }
 OPTIONAL {
   ?c rdfs:label ?clabel
   BIND(concat("DISJOINT-SIB-OF ", ?clabel) AS ?sibLabel)
 }
 BIND (UUID() as ?sibClass)
}

```

**Comment by matentzn** [comment]
@cmungall @rtauber Should this be moved to ROBOT repo?

**Comment by marieALaporte** [comment]
I don't think it should since this change should be integrated to the makefile (here. https://github.com/INCATools/ontology-development-kit/blob/master/template/src/ontology/Makefile#L48) 

ROBOT is already implementing it so that's not a ROBOT issue

**Comment by matentzn** [comment]
Cool thanks, I thought the flag did not exist in robot yet :P

**Comment by marieALaporte** [comment]
I am not sure it is part of the released version of ROBOT yet. But if you build it from the source, you can use it.

**Comment by marieALaporte** [comment]
To me, ODK is used when you want to start a new ontology. In that case it makes sense to not allow equivalent classes.

If people want to customize the makefile, they can still do it. But by default if you start from "scratch", not allowing equivalent classes would have my preference.

**Comment by matentzn** [comment]
I dont like arguing against myself at all, :). I agree with you! But this change does not only effect the initialisation of the repository: the make file you are pointing to is used for continuous integration as well. As the ontology swells with many more imports coming in, a 'intended equivalence mapping' is not completely out of the question to slip in. I vote for -e in output, but not death. You vote for -e + death. @cmungall @dosumis @balhoff ? I will do the change if we get a majority

**Comment by balhoff** [comment]
I support `-e`, since we are focused on the OBO community and even if you are depending on a lot of imports, it is likely you don't intend to "duplicate" another OBO class.

**Comment by matentzn** [comment]
Maybe I misunderstand what is going on here. Lets say I am HP and I want for some reason (let's assume for now legit) to import an MP module into my ontology. Now MP:Hypertension turns out to be equivalent to HP:Hypertension. Wouldn't -e refuse to compile the ontology?

**Comment by marieALaporte** [comment]
>  the make file you are pointing to is used for continuous integration as well

Is it really? I thought that the makefiles living in each repo was used for the CI.
I am asking that very naively as I would really like to understand the big picture here

**Comment by matentzn** [comment]
Yeah, as far as I understand, it goes like this: the template directory contains the blueprint for a new project (the one you were pointing at re makefile). When creating a new ontology the seed_repo.pl copies all files in the template dir into a new project dir (including that make file). Then, a new release is created using the recently copied make file. And now, I believe, all the stuff in the newly created directory will be commited to a fresh GitHub repo, including the makefile; which is then used for stuff like creating a new releases, compiling patterns etc.

**Comment by cmungall** [comment]
Thanks everyone, seems we have converged on `-e` as default, and some docs to make it clearer how to change (I am less concerned than Nico as I think the OBO community users who do have valid use cases for named class equivalence are experts with hotlines to us anyway).

I quite like the idea of moving some parameterization to the top of the Makefile - in general, not just for this

**Comment by cmungall** [comment]
And my comment from 29 days ago has been expanded into a post:

https://douroucouli.wordpress.com/2018/09/04/debugging-ontologies-using-owl-reasoning-part-2-unintentional-entailed-equivalence/

I tried to take all your comments into account, sorry if it's still not completely clear
