### ISSUE TITLE
Decide how to deal with 8 downregulated dependencies

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#897]
Discussed on slack, but adding here because I have to make some immediate progress with this. 

Because of the currently wrong way we are dealing with python dependencies in ODK (one mega environment rather than many focussed ones) we had to do some prioritisation of dependencies, leading to 8 transitive dependencies being down-regulated (funowl, kgx, docutils, neo4j, ontobio, Sphinx, tomli, tox, see #894).

- funowl
- kgx (@hrshdhgd working on this)
- docutils
- neo4j
- ontobio (@cmungall says remove, and I agree, so consider this a flag for removal)
- Sphinx
- tomli
- tox

**Comment by matentzn** [comment]
```
Because kgx (2.2.1) depends on networkx (>=2.8,<3.0)
 and no versions of kgx match >2.2.1,<3.0.0, kgx (>=2.2.1,<3.0.0) requires networkx (>=2.8,<3.0).
So, because test depends on both networkx (^3.1) and kgx (^2.2.1), version solving failed.
```

**Comment by anitacaron** [comment]
We have had two other minor releases and have not encountered any issues yet.

**Comment by matentzn** [comment]
We are going to close this because for a few months, versions where only ever upgraded. If a user comes that needs a newer kgx version, or network x, they can make a separate issue.
