### ISSUE TITLE
Deliver ROBOT plugins in ODK - whats the best way?

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#909]
We need to decide on a way to make ROBOT plugins easily configurable with ODK. 

There are basically two completely different approaches (at least)

1. We pass in a plugins dir to run.sh (as a volume) and require all custom plugins to be present
1. We add custom plugins into the build process. Basically, we depend on them the same way we depend on data artefacts, download them into a _local_ plugin directory in the project, and point `ROBOT_PLUGINS_DIRECTORY` at that. For example:

Makefile contents:

```
export ROBOT_PLUGINS_DIRECTORY=$(PWD)/tmp/plugins

$(ROBOT_PLUGINS_DIRECTORY)/monarch.jar:
	mkdir -p $(ROBOT_PLUGINS_DIRECTORY)
	wget ... -O $@

hp-eq.owl: | $(ROBOT_PLUGINS_DIRECTORY)/monarch.jar
	$(ROBOT) monarch:upheno-augment -i hp-edit.owl --relation has_phenotype_affecting  -o $@
```

While I appreciate the cleanliness of approach 1, it puts too much of a burden on most of the people I work with - I would just like to fold it into the general make process somehow, but I am open to add both alternatives.

Of course you could sort of do a hybrid: pass in the ~/.robot/plugins dir as a volume _and_ download dependencies as necessary. But I would like to keep dependencies on local file structures as minimal as possible.

**Comment by gouttegd** [comment]
A related question is: Should the ODK come with some bundled “default” plugins directly within the image, with ROBOT pre-configured to use them?

I don’t have a strong opinion on that question (I’ll just note that if we think a plugin is useful enough to be provided by the ODK, that’s probably a good indication that such a plugin should really be a ROBOT built-in command instead), but if do want to do that, it will have an impact on the issue you raise, because ROBOT will need to be configured to look for plugins in (at least) two places: one location within the image for bundled plugins, and one location outside of the image (e.g. `$(TMPDIR)/tmp/plugins`) for custom plugins provided by the user.

**Comment by gouttegd** [comment]
That is, in the standard Makefile we would have the following additions:

```Makefile
# Make sure ROBOT knows where to find plugins
export ROBOT_PLUGINS_DIRECTORY=$(TMPDIR)/plugins

# List of "repository plugins" (plugins permanently installed in top-level plugins directory, entirely managed by users)
ROBOT_REPOSITORY_PLUGINS=$(wildcard ../../plugins.jar)

# Standard rule to create symlinks in $(TMPDIR)/plugins, so that the repository plugins
# are visible to ROBOT
repository_plugins:
        for plugin in $(ROBOT_REPOSITORY_PLUGINS) ; do ln $plugin $(TMPDIR)/plugins ; done
```

Then in the custom Makefile, the repository’s workflow engineers would have to either:

* if they prefer to download whatever plugins they need as part of their workflows, create custom rules to download those plugins and put them in `$(TMPDIR)/plugins` (as is done in the example in the ticket), then make sure that any custom rule that is needing those plugins depend on the plugin-downloading rule;
* if instead they have already put the plugins “manually” into the top-level `plugins` directory, then they just need to make sure that any rule that is needing those plugins depend on the standard `repository_plugins` rule.

**Comment by matentzn** [comment]
@gouttegd testing this a bit in HPO: https://github.com/obophenotype/human-phenotype-ontology/pull/9952/files
so far so good.

If you have time to look this over at some point..
