### ISSUE TITLE
In Makefile template, do not trigger rebuild of imports when source changes

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-development-kit#91]

**Comment by balhoff** [comment]
From what I can tell from the makefile, if the source changes and it causes a change in the seed terms, imports will be rebuilt (but not re-downloaded). This is good (and why we have `sort | uniq` in the seed outputs). So I think this ticket is more about not triggering rebuild of the mirror, which just has to be done manually.

**Comment by cmungall** [comment]
I haven't looked in detail since David added patterns, but I *think* the seed still needs manual rebuilding. Which is OK I think since it prevents unexpected changes (and makes travis builds much faster and more consistent)
