### ISSUE TITLE
Next ODK Release

### ISSUE THREAD

**Issue by cthoyt** [INCATools/ontology-development-kit#925]
I'm keen to get a v 1.4.3 or v1.5 release containing https://github.com/INCATools/ontology-development-kit/pull/923. Just creating this issue as a placeholder for discussion

**Comment by gouttegd** [comment]
The plan is to get a 1.4.3 release (with #924) by next week. Version 1.5 will come later.

**Comment by cthoyt** [comment]
@gouttegd cheers! Thanks
