### ISSUE TITLE
Update URL to show CI status badge 

### ISSUE THREAD

**Issue by anitacaron** [INCATools/ontology-development-kit#948]
https://github.com/INCATools/ontology-development-kit/blob/ffb561e212b0c4b75b125b09f761f474bd129fe7/template/README.md.jinja2#L4

The URL format should be, [according to source](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge#using-the-workflow-file-name):

```
https://github.com/OWNER/REPOSITORY/actions/workflows/WORKFLOW-FILE/badge.svg
```

**Comment by matentzn** [comment]
I recently stumbled across this, and wonder if something has changed. What I find annoying is that clicking on the "fail" does not immediately get you to the last failed action..

**Comment by matentzn** [comment]
@anitacaron can you take this issue?
