### ISSUE TITLE
BAT files to execute docker tools do not work with Windows Docker Toolbox  

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#95]
Probably because of a filepath issue.

**Comment by cmungall** [comment]
Will you be able to investigate? We have no windows machines here

**Comment by matentzn** [comment]
Yeah I do. This item is not of critical importance: Most modern Windows machines support docker CE, and for them it all works fine. Its just for the older machines that only support this Docker Toolbox for which we should try and find a solution. I will try to take care of it, but a bit further down the line.

**Comment by matentzn** [comment]
Refer to this:

https://github.com/INCATools/ontology-development-kit/issues/329

My canonical answer is now that we do not support Docker toolbox.
