### ISSUE TITLE
Add a link to issues ranked by votes

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-development-kit#950]
Let's encourage the practice of each repo linking to a list of all issues sorted by vote. This could be implemented as a link in the README or in the docs.

Another thing we can do is pin the issue

See for example https://github.com/oborel/obo-relations/issues

<img width="777" alt="image" src="https://github.com/INCATools/ontology-development-kit/assets/50745/4e5a6e20-87ff-411a-b718-eb88d6d67c79">

links to:

https://github.com/oborel/obo-relations/issues/765

Seeding a new repo with issues using the GH API may be a bit much for ODK though

**Comment by matentzn** [comment]
https://github.com/INCATools/ontology-development-kit/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by matentzn** [comment]
I did this for ODK: https://github.com/INCATools/ontology-development-kit/issues/966

I think it is not too much to ask for ontology repos doing this by themselves rather than ODK automating this;

Please reopen if you disagree, and we will pursue this avenue!
