### ISSUE TITLE
License updated issue

### ISSUE THREAD

**Issue by Crispae** [INCATools/ontology-development-kit#957]
Hi, 

While seeding the repo, I missed adding appropriate license. I tried to changes it configuration file (`onto-odk.yml`) and run update_repo (I am directly running docker command instead of run.sh like `docker run -v .:/work -w /work/src/ontology -ti obolibrary/odkfull make update_repo`) and then run `prepare_release`. But the license remain default  i.e. `https://creativecommons.org/licenses/unspecified`.

I tried to add both `https://creativecommons.org/licenses/by/4.0/` and `CC-BY 4.0` but no luck. From the code-base it looks, like license configuration is only handled while seeding , their is no option to update it later or by config file. Please clarify this, do we need to re initiate the project to change the license.

Regards

**Comment by anitacaron** [comment]
Hi @Crispae, you're right. Some of the configuration is only used once during the seed process. To update the ontology's license, you can do it directly into the [src/ontology/pko-edit.owl](https://github.com/Crispae/pkonto/blob/a2496fdea142c90f1ba636f3b5af30e1d66925d9/src/ontology/pko-edit.owl#L18C79-L18C79) (assuming this is the ontology you want to change).

```
Annotation(dcterms:license <https://creativecommons.org/licenses/unspecified>)
```

**Comment by Crispae** [comment]
@anitacaron, thank you for your reply. It would greatly assist developers to have clarification on what aspects are changeable and what remain unchangeable after the seeding process.

**Comment by anitacaron** [comment]
Thank you for your suggestion. I created an issue for this, and I'll close this one.
