### ISSUE TITLE
Untracked files in the initialized repository

### ISSUE THREAD

**Issue by marijane** [INCATools/ontology-development-kit#98]
I see this when I seed my ontology:
```
EXECUTING: git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	src/ontology/ed_definitions_merged.owl
	src/ontology/patterns
	src/patterns/imports/pato_import.owl
	src/patterns/imports/po_import.owl
	src/patterns/imports/ro_import.owl
	src/patterns/imports/seed_sorted.txt
	src/patterns/pattern.owl

nothing added to commit but untracked files present (use "git add" to track)
```
If these are mentioned in the documentation, I missed it.  Are these intentionally untracked or is this a bug?  I'm not sure if I'm expected to add and commit them, keep them untracked and add them to my .gitignore file, or if the seeding script was supposed to take care of this for me and not leave me wondering about them.

**Comment by dosumis** [comment]
1. We need to do some work to move temp files into a working folder and add them to .gitignore.  This applies to:

src/ontology/ed_definitions_merged.owl
src/patterns/imports/seed_sorted.txt

2. We should add a minimal (header-only) pattern.owl to the git as part of the starter kit template.

3. We need to add instructions to README for users to add anything generated under 
`patterns/imports/` to git.

**Comment by cmungall** [comment]
no deletions, that could interfere with makefile dependency reasoning.

Leaving intermediate files around is fine. We just need to add them to the .gitignore

**Comment by matentzn** [comment]
Okay I am almost there:

These are now in gitignore
```
src/ontology/ed_definitions_merged.owl
src/patterns/imports/seed_sorted.txt
```
Also in gitignore, but should it be dealt with differently?
```
src/ontology/patterns 
```
This is a very strange one, and may be avoidable: it is generated automatically by the makefile when running the new 'patterns' target. I am not sure whether it is used for anything. If you find check the log after creating a new file, you will find a line. Advise? @cmungall @dosumis 

```
cat patterns.sh >patterns 
```

Right after running the module extraction for the pattern imports. 

This is now tracked (I added a completely empty pattern.owl (empty ontology) to the template):
```
src/patterns/pattern.owl
```

What do we do about those? @dosumis you say 'add some comments in readme', but should we just leave them untracked for now?

```
src/patterns/imports/pato_import.owl
src/patterns/imports/po_import.owl
src/patterns/imports/ro_import.owl
```

**Comment by matentzn** [comment]
Please re-open if issue persists.
