### ISSUE TITLE
Incomplete imports from AISM to COLAO

### ISSUE THREAD

**Issue by JCGiron** [INCATools/ontology-development-kit#991]
[AISM](https://github.com/insect-morphology/aism) is an intology for insect anatomy meant to be the base for order-specific ontologies (beetles, butterflies, etc.). The latest iterations of AISM (cleaned up of errors and updated with newly added terms) have not been fully/properly imported into [COLAO](https://github.com/insect-morphology/colao) using our [usual workflow](https://github.com/insect-morphology/Manual/blob/main/Sections/Creating-AISM-based-insect-ontology.md#setup-aism-based-ontology-imports) that used to work in the past.
AISM has lots of extra vertebrate-specific terms imported from UBERON and other ontologies that are not needed for insect descriptions. In our workflow to import the actually necessary AISM terms in a "cleaner" version, we have some comands added to our ontology.Makefile file to eliminate extra annotation properties and import AISM terms along with all the other basic terms needed.
AISM v2024-01-17 was imported into COLAO v2024-01-18 but the imports are incomplete. For example: 
- The term 'insect external male genitalia' [AISM:0004316] is missing its definition.
- AISM:0000407 ('cuticular tooth') does not have its label (although it might have been an error now corrected in AISM v2024-01-31)
- AISM:0000390 ('protibial apex below protibio-protarsal articulation'), AISM:0000412 ('cuticle with setigerous punctures'), among several others (see image below) are missing all their annotations.
![image](https://github.com/INCATools/ontology-development-kit/assets/37313282/8847f712-2639-498a-aaea-8a330b32f32c)

In addition, the latest releases of COLAO are not passing [Quality Controls in GitHub](https://github.com/insect-morphology/colao/actions/runs/7575837863/job/20633348294).

I suspect there might be something in the comands added to our ontology.Makefile that have changed in the latest versions of ODK. Any help is welcome.
@matentzn

**Comment by matentzn** [comment]
@JCGiron is all of this information already committed to the COLAO repo? Generally in such cases, it is easiest for me if you point me to a branch of the affected ontology after you refreshed the imports.

**Comment by matentzn** [comment]
Ok, someone messed a bit with the aism_import.owl in `colao.Makefile`. The correct command is:


```
imports/aism_import.owl: mirror/aism.owl tmp/seed_aism_base.txt
	if [ $(IMP) = true ]; then $(ROBOT) remove -i $< -T tmp/seed_aism_base.txt --select complement --select "classes individuals" \
		remove -T keep_obp.txt --select complement --select object-properties --signature true \
		remove -T keep_ann.txt --select complement --select annotation-propertie --signature trues \
		annotate --ontology-iri $(ONTBASE)/$@ --version-iri $(ONTBASE)/releases/$(TODAY)/$@ --output $@.tmp.owl && mv $@.tmp.owl $@; fi
.PRECIOUS: aism_import.owl
```

The problem was that because you have axiom annotations like this in AISM:

```
    <owl:Axiom>
        <owl:annotatedSource rdf:resource="http://purl.obolibrary.org/obo/AISM_0000407"/>
        <owl:annotatedProperty rdf:resource="http://www.w3.org/2000/01/rdf-schema#label"/>
        <owl:annotatedTarget xml:lang="en">cuticular tooth</owl:annotatedTarget>
        <term:contributor>gmontanaro https://orcid.org/0000-0003-0836-1364</term:contributor>
        <oboI:creation_date>18-11-2023</oboI:creation_date>
    </owl:Axiom>
```

you end up removing everything `oboI:creation_date` and some others are not in the annotations to keep.

The key change in my fix above is the use of `--signature true` which ignores axiom annotations.

**Comment by matentzn** [comment]
@JCGiron closing this hear, as this is not an ODK issue - feel free to ping me on slack if there is a problem!

**Comment by matentzn** [comment]
(EDIT there was a copy paste error in the above command fixed now)
